using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cervantes.DAL.Migrations
{
    public partial class AddedMASTG : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MASTG",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TargetId = table.Column<Guid>(type: "uuid", nullable: false),
                    UserId = table.Column<string>(type: "text", nullable: true),
                    ProjectId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    ArchNote01 = table.Column<string>(type: "text", nullable: true),
                    ArchNote02 = table.Column<string>(type: "text", nullable: true),
                    ArchNote03 = table.Column<string>(type: "text", nullable: true),
                    ArchNote04 = table.Column<string>(type: "text", nullable: true),
                    ArchNote05 = table.Column<string>(type: "text", nullable: true),
                    ArchNote06 = table.Column<string>(type: "text", nullable: true),
                    ArchNote07 = table.Column<string>(type: "text", nullable: true),
                    ArchNote08 = table.Column<string>(type: "text", nullable: true),
                    ArchNote09 = table.Column<string>(type: "text", nullable: true),
                    ArchNote10 = table.Column<string>(type: "text", nullable: true),
                    ArchNote11 = table.Column<string>(type: "text", nullable: true),
                    ArchNote12 = table.Column<string>(type: "text", nullable: true),
                    StorageNote01 = table.Column<string>(type: "text", nullable: true),
                    StorageNote02 = table.Column<string>(type: "text", nullable: true),
                    StorageNote03 = table.Column<string>(type: "text", nullable: true),
                    StorageNote04 = table.Column<string>(type: "text", nullable: true),
                    StorageNote05 = table.Column<string>(type: "text", nullable: true),
                    StorageNote06 = table.Column<string>(type: "text", nullable: true),
                    StorageNote07 = table.Column<string>(type: "text", nullable: true),
                    StorageNote08 = table.Column<string>(type: "text", nullable: true),
                    StorageNote09 = table.Column<string>(type: "text", nullable: true),
                    StorageNote10 = table.Column<string>(type: "text", nullable: true),
                    StorageNote11 = table.Column<string>(type: "text", nullable: true),
                    StorageNote12 = table.Column<string>(type: "text", nullable: true),
                    StorageNote13 = table.Column<string>(type: "text", nullable: true),
                    StorageNote14 = table.Column<string>(type: "text", nullable: true),
                    StorageNote15 = table.Column<string>(type: "text", nullable: true),
                    CryptoNote01 = table.Column<string>(type: "text", nullable: true),
                    CryptoNote02 = table.Column<string>(type: "text", nullable: true),
                    CryptoNote03 = table.Column<string>(type: "text", nullable: true),
                    CryptoNote04 = table.Column<string>(type: "text", nullable: true),
                    CryptoNote05 = table.Column<string>(type: "text", nullable: true),
                    CryptoNote06 = table.Column<string>(type: "text", nullable: true),
                    AuthNote01 = table.Column<string>(type: "text", nullable: true),
                    AuthNote02 = table.Column<string>(type: "text", nullable: true),
                    AuthNote03 = table.Column<string>(type: "text", nullable: true),
                    AuthNote04 = table.Column<string>(type: "text", nullable: true),
                    AuthNote05 = table.Column<string>(type: "text", nullable: true),
                    AuthNote06 = table.Column<string>(type: "text", nullable: true),
                    AuthNote07 = table.Column<string>(type: "text", nullable: true),
                    AuthNote08 = table.Column<string>(type: "text", nullable: true),
                    AuthNote09 = table.Column<string>(type: "text", nullable: true),
                    AuthNote10 = table.Column<string>(type: "text", nullable: true),
                    AuthNote11 = table.Column<string>(type: "text", nullable: true),
                    AuthNote12 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote01 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote02 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote03 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote04 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote05 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote06 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote07 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote08 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote09 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote10 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote11 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote12 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote13 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote14 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote15 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote16 = table.Column<string>(type: "text", nullable: true),
                    NetworkNote17 = table.Column<string>(type: "text", nullable: true),
                    CodeNote01 = table.Column<string>(type: "text", nullable: true),
                    CodeNote02 = table.Column<string>(type: "text", nullable: true),
                    CodeNote03 = table.Column<string>(type: "text", nullable: true),
                    CodeNote04 = table.Column<string>(type: "text", nullable: true),
                    CodeNote05 = table.Column<string>(type: "text", nullable: true),
                    CodeNote06 = table.Column<string>(type: "text", nullable: true),
                    CodeNote07 = table.Column<string>(type: "text", nullable: true),
                    CodeNote08 = table.Column<string>(type: "text", nullable: true),
                    CodeNote09 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote01 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote02 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote03 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote04 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote05 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote06 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote07 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote08 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote09 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote10 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote11 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote12 = table.Column<string>(type: "text", nullable: true),
                    ResilienceNote13 = table.Column<string>(type: "text", nullable: true),
                    ArchStatus01 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus02 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus03 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus04 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus05 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus06 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus07 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus08 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus09 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus10 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus11 = table.Column<int>(type: "integer", nullable: false),
                    ArchStatus12 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus01 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus02 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus03 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus04 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus05 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus06 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus07 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus08 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus09 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus10 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus11 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus12 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus13 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus14 = table.Column<int>(type: "integer", nullable: false),
                    StorageStatus15 = table.Column<int>(type: "integer", nullable: false),
                    CryptoStatus01 = table.Column<int>(type: "integer", nullable: false),
                    CryptoStatus02 = table.Column<int>(type: "integer", nullable: false),
                    CryptoStatus03 = table.Column<int>(type: "integer", nullable: false),
                    CryptoStatus04 = table.Column<int>(type: "integer", nullable: false),
                    CryptoStatus05 = table.Column<int>(type: "integer", nullable: false),
                    CryptoStatus06 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus01 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus02 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus03 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus04 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus05 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus06 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus07 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus08 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus09 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus10 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus11 = table.Column<int>(type: "integer", nullable: false),
                    AuthStatus12 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus01 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus02 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus03 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus04 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus05 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus06 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus07 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus08 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus09 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus10 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus11 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus12 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus13 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus14 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus15 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus16 = table.Column<int>(type: "integer", nullable: false),
                    NetworkStatus17 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus01 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus02 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus03 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus04 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus05 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus06 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus07 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus08 = table.Column<int>(type: "integer", nullable: false),
                    CodeStatus09 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus01 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus02 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus03 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus04 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus05 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus06 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus07 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus08 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus09 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus10 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus11 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus12 = table.Column<int>(type: "integer", nullable: false),
                    ResilienceStatus13 = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MASTG", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MASTG_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_MASTG_Projects_ProjectId",
                        column: x => x.ProjectId,
                        principalTable: "Projects",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_MASTG_Targets_TargetId",
                        column: x => x.TargetId,
                        principalTable: "Targets",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_MASTG_ProjectId",
                table: "MASTG",
                column: "ProjectId");

            migrationBuilder.CreateIndex(
                name: "IX_MASTG_TargetId",
                table: "MASTG",
                column: "TargetId");

            migrationBuilder.CreateIndex(
                name: "IX_MASTG_UserId",
                table: "MASTG",
                column: "UserId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MASTG");
        }
    }
}
