/*using Cervantes.CORE.Entities;

namespace Cervantes.IFR;

public class VulnTemplatesWstgES
{
    public static Vuln InsufficientAuthentication => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Autenticación Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no autentica adecuadamente a los usuarios, permitiendo el acceso no autorizado a funcionalidades o datos sensibles.",
        ProofOfConcept = "Demostrar acceso a áreas o funciones restringidas sin una autenticación adecuada.",
        Impact = "Unauthorized access to sensitive data or functionality, potentially leading to data breaches or system compromise.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar mecanismos de autenticación fuertes, como la autenticación de múltiples factores, para todas las áreas sensibles de la aplicación.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "High",
        OWASPImpact = "Severe",
        OWASPLikehood = "Likely",
        OWASPVector = "2.0",
        MitreValues = "Initial Access, Privilege Escalation",
        MitreTechniques = "T1078",
        VulnCwes = new List<string> { "CWE-287", "CWE-306" },
    };
    
    public static Vuln WeakPasswordRequirements => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Requisitos de Contraseña Débiles",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación permite contraseñas débiles que no cumplen con los requisitos mínimos de complejidad y longitud.",
    ProofOfConcept = "Crear cuentas con contraseñas débiles que no cumplen con los estándares de la industria.",
    Impact = "Increased risk of successful brute-force attacks and unauthorized account access.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    Remediation = "Implementar políticas de contraseñas fuertes que requieran una longitud mínima, complejidad y que eviten contraseñas débiles comunes.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access",
    MitreTechniques = "T1110",
    VulnCwes = new List<string> { "CWE-521" },
};

public static Vuln InsecureSessionManagement => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Gestión Insegura de Sesiones",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no gestiona adecuadamente las sesiones de usuario, lo que lleva a vulnerabilidades como la fijación de sesión o la expiración insuficiente de sesiones.",
    ProofOfConcept = "Demostrar el secuestro de la sesión de un usuario o el uso de un token de sesión antiguo para obtener acceso no autorizado.",
    Impact = "Unauthorized access to user accounts and sensitive data.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar prácticas seguras de gestión de sesiones, incluyendo la creación, expiración e invalidación adecuada de sesiones.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Lateral Movement",
    MitreTechniques = "T1539",
    VulnCwes = new List<string> { "CWE-384", "CWE-613" },
};

public static Vuln Idor => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Referencia Directa Insegura a Objetos (IDOR)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación expone una referencia directa a objetos de implementación interna, como archivos, directorios, registros de base de datos o claves, sin ningún control de acceso o validación.",
    ProofOfConcept = "Demostrar el acceso o modificación de recursos pertenecientes a otros usuarios manipulando referencias a objetos en las solicitudes.",
    Impact = "Unauthorized access to sensitive data, potential data theft, or manipulation of other users' information.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar controles de acceso adecuados y utilizar referencias indirectas a objetos que se mapeen a datos específicos del usuario en el lado del servidor.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Lateral Movement, Collection",
    MitreTechniques = "T1213",
    VulnCwes = new List<string> { "CWE-639" },
};

public static Vuln CrossSiteScripting => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Cross-Site Scripting (XSS)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no valida o codifica adecuadamente la entrada del usuario antes de renderizarla en una página web, permitiendo a los atacantes inyectar y ejecutar scripts maliciosos en el contexto de los navegadores de otros usuarios.",
    ProofOfConcept = "Demostrar la inyección de un script que se ejecuta en el navegador de la víctima, como mostrar una caja de alerta o robar cookies de sesión.",
    Impact = "Potential theft of user sessions, defacement of websites, redirection of users to malicious sites, or execution of arbitrary code in the user's browser.",
    CVSS3 = 6.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    Remediation = "Implementar una validación de entrada adecuada, codificación de salida y usar encabezados de Content Security Policy (CSP) para mitigar los riesgos de XSS.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1189",
    VulnCwes = new List<string> { "CWE-79" },
};

public static Vuln InsecureCryptographicStorage => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Almacenamiento Criptográfico Inseguro",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación almacena datos sensibles utilizando algoritmos criptográficos débiles o desactualizados, o implementa incorrectamente funciones criptográficas.",
    ProofOfConcept = "Demostrar la capacidad de descifrar datos sensibles utilizando debilidades conocidas en la implementación criptográfica.",
    Impact = "Unauthorized access to sensitive data, potentially leading to identity theft, financial fraud, or other malicious activities.",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Utilizar algoritmos criptográficos fuertes y estándares de la industria e implementarlos correctamente. Asegurar prácticas adecuadas de gestión de claves.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Exfiltration",
    MitreTechniques = "T1552",
    VulnCwes = new List<string> { "CWE-327", "CWE-328" },
};

public static Vuln InsecureDeserialization => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Deserialización Insegura",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación deserializa datos no confiables sin verificación suficiente, permitiendo potencialmente a los atacantes ejecutar código arbitrario o manipular la lógica de la aplicación.",
    ProofOfConcept = "Crear un objeto serializado malicioso que, al deserializarse, ejecute comandos no autorizados o altere el comportamiento de la aplicación.",
    Impact = "Remote code execution, data manipulation, or denial of service.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar comprobaciones de tipo estrictas, usar prácticas de deserialización seguras y evitar deserializar datos no confiables cuando sea posible.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Execution, Defense Evasion",
    MitreTechniques = "T1203",
    VulnCwes = new List<string> { "CWE-502" },
};

public static Vuln BrokenAccessControl => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Control de Acceso Defectuoso",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no aplica correctamente los controles de acceso, permitiendo a los usuarios realizar acciones o acceder a recursos para los que no deberían tener permiso.",
    ProofOfConcept = "Demostrar el acceso a funcionalidades o datos no autorizados manipulando parámetros de solicitud o utilizando una cuenta con privilegios inferiores.",
    Impact = "Unauthorized access to sensitive data or functionality, potential data theft, or manipulation of other users' information.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar y aplicar controles de acceso adecuados tanto a nivel de aplicación como de API. Utilizar control de acceso basado en roles (RBAC) y el principio de mínimo privilegio.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Privilege Escalation, Lateral Movement",
    MitreTechniques = "T1548",
    VulnCwes = new List<string> { "CWE-284", "CWE-285", "CWE-639" },
};

public static Vuln SecurityMisconfiguration => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Configuración Incorrecta de Seguridad",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación, el marco de trabajo, el servidor web o la plataforma están configurados de manera insegura, potencialmente exponiendo información sensible o permitiendo acceso no autorizado.",
    ProofOfConcept = "Identificar y explotar configuraciones predeterminadas, servicios abiertos innecesarios o información del sistema expuesta.",
    Impact = "Unauthorized access to application features or data, system compromise, or information disclosure.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
    Remediation = "Implementar prácticas de configuración segura, deshabilitar características innecesarias, usar encabezados de seguridad y actualizar y parchar regularmente todos los componentes.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Discovery",
    MitreTechniques = "T1082",
    VulnCwes = new List<string> { "CWE-16", "CWE-2" },
};

public static Vuln SensitiveDataExposure => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Exposición de Datos Sensibles",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no protege adecuadamente la información sensible, como datos financieros, información de salud o información de identificación personal (PII).",
    ProofOfConcept = "Interceptar transmisiones de datos no cifrados o acceder a almacenamiento de datos sensibles mal asegurados.",
    Impact = "Exposure of sensitive user data, potential for identity theft, financial fraud, or violation of data protection regulations.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "Cifrar datos sensibles en tránsito y en reposo, implementar una gestión adecuada de claves y minimizar la exposición de datos sensibles en registros y mensajes de error.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Collection, Exfiltration",
    MitreTechniques = "T1005",
    VulnCwes = new List<string> { "CWE-311", "CWE-312", "CWE-319" },
};

public static Vuln InsufficientLoggingAndMonitoring => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Registro y Monitoreo Insuficientes",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no genera registros adecuados para eventos de seguridad, o no monitorea ni responde a incidentes de seguridad de manera oportuna.",
    ProofOfConcept = "Realizar actividades sospechosas sin detección, o demostrar la falta de pistas de auditoría adecuadas para operaciones críticas.",
    Impact = "Delayed or missed detection of malicious activities, hindered incident response and forensics capabilities.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar un registro completo para eventos relevantes de seguridad, asegurar un almacenamiento y protección adecuados de los registros, y establecer mecanismos efectivos de monitoreo y alerta.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Defense Evasion, Impact",
    MitreTechniques = "T1562",
    VulnCwes = new List<string> { "CWE-778", "CWE-223" },
};

public static Vuln UsingComponentsWithKnownVulnerabilities => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Uso de Componentes con Vulnerabilidades Conocidas",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación utiliza componentes de terceros, bibliotecas o marcos de trabajo con vulnerabilidades de seguridad conocidas.",
    ProofOfConcept = "Identificar componentes desactualizados y demostrar la explotación de vulnerabilidades conocidas en estos componentes.",
    Impact = "Potential for various types of attacks depending on the vulnerability, including data theft, remote code execution, or application compromise.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Actualizar y parchar regularmente todos los componentes, implementar una herramienta de análisis de composición de software y mantener un inventario de todos los componentes utilizados y sus versiones.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-1035" },
};

public static Vuln SqlInjection => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Inyección SQL",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación construye consultas SQL utilizando entrada proporcionada por el usuario sin una sanitización o parametrización adecuada, permitiendo a los atacantes modificar o ejecutar comandos SQL arbitrarios.",
    ProofOfConcept = "Demostrar la capacidad de recuperar datos no autorizados o ejecutar comandos en la base de datos inyectando SQL malicioso.",
    Impact = "Unauthorized access to sensitive data, data manipulation, and potential complete compromise of the database and connected systems.",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Utilizar consultas parametrizadas o declaraciones preparadas, implementar una validación de entrada adecuada y aplicar el principio de mínimo privilegio para las cuentas de base de datos.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "3.0",
    MitreValues = "Initial Access, Execution, Exfiltration",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-89" },
};

public static Vuln ServerSideRequestForgery => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Falsificación de Solicitudes del Lado del Servidor (SSRF)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación procesa URL o rutas de archivo proporcionadas por el usuario para recuperar recursos, permitiendo a un atacante manipular solicitudes para acceder a recursos internos o realizar acciones no autorizadas.",
    ProofOfConcept = "Demostrar la capacidad de hacer que el servidor solicite recursos internos o sitios externos controlados por el atacante.",
    Impact = "Potential access to internal systems, data exfiltration, or remote code execution in some cases.",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:H",
    Remediation = "Implementar una validación de entrada estricta, usar listas blancas para URLs o dominios permitidos, deshabilitar esquemas de URL innecesarios y usar un servidor separado para realizar solicitudes externas.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Lateral Movement",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-918" },
};

public static Vuln XmlExternalEntityProcessing => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Procesamiento de Entidades Externas XML (XXE)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación procesa entrada XML que incluye referencias a entidades externas sin una validación adecuada, permitiendo a los atacantes revelar archivos internos, realizar falsificación de solicitudes del lado del servidor o ejecutar ataques de denegación de servicio.",
    ProofOfConcept = "Demostrar la capacidad de leer archivos internos o hacer que el servidor se conecte a hosts arbitrarios utilizando entrada XML que contiene entidades externas maliciosas.",
    Impact = "Potential disclosure of sensitive data, server-side request forgery, or denial of service.",
    CVSS3 = 8.2,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:H",
    Remediation = "Deshabilitar el procesamiento de entidades externas XML y DTD en todos los analizadores XML de la aplicación, usar formatos de datos menos complejos como JSON cuando sea posible, y validar y sanear toda la entrada XML.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-611" },
};

public static Vuln LackOfRateLimiting => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Falta de Limitación de Tasa",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no implementa mecanismos adecuados de limitación de tasa, permitiendo a los atacantes realizar un número excesivo de solicitudes u operaciones.",
    ProofOfConcept = "Demostrar la capacidad de realizar un gran número de solicitudes en un corto período de tiempo sin ninguna restricción.",
    Impact = "Potential for denial of service, brute force attacks, or excessive resource consumption.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    Remediation = "Implementar limitación de tasa en todos los puntos finales de la API y funciones críticas. Utilizar técnicas como algoritmos de cubo de tokens o contadores de ventana fija para restringir el número de solicitudes que un usuario puede hacer en un período de tiempo determinado.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Impact",
    MitreTechniques = "T1499",
    VulnCwes = new List<string> { "CWE-770" },
};

public static Vuln InadequateOAuth2Implementation => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Implementación Inadecuada de OAuth 2.0",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La implementación de OAuth 2.0 de la aplicación contiene fallas de seguridad, como validación inadecuada de URIs de redirección, almacenamiento inseguro de tokens o manejo incorrecto de parámetros de estado.",
    ProofOfConcept = "Demostrar la capacidad de realizar robo de tokens, toma de control de cuentas o acceso no autorizado a través de fallas en la implementación de OAuth.",
    Impact = "Potential for unauthorized access to user accounts, data theft, or impersonation of users.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
    Remediation = "Implementar OAuth 2.0 de forma segura siguiendo las mejores prácticas: validar todas las URIs de redirección, usar parámetros de estado para prevenir CSRF, almacenar y transmitir tokens de forma segura, e implementar una validación y expiración adecuada de tokens.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Lateral Movement",
    MitreTechniques = "T1550",
    VulnCwes = new List<string> { "CWE-346", "CWE-601" },
};

public static Vuln InsufficientAntiAutomation => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Protección Insuficiente contra Automatización",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación carece de medidas suficientes para prevenir ataques automatizados, como relleno de credenciales, intentos de fuerza bruta o raspado de contenido.",
    ProofOfConcept = "Demostrar la capacidad de realizar solicitudes automatizadas de alto volumen sin activar ningún mecanismo defensivo.",
    Impact = "Potential for account takeover, data harvesting, or service degradation through automated attacks.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar medidas anti-automatización como CAPTCHA, limitación de tasa, restricciones basadas en IP y análisis de comportamiento para detectar y prevenir ataques automatizados.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Credential Access",
    MitreTechniques = "T1110",
    VulnCwes = new List<string> { "CWE-799", "CWE-837" },
};

public static Vuln WeakCryptographicAlgorithms => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Algoritmos Criptográficos Débiles",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación utiliza algoritmos criptográficos débiles u obsoletos que son susceptibles a ataques.",
    ProofOfConcept = "Identificar el uso de algoritmos débiles (por ejemplo, MD5, SHA1, DES) en las operaciones criptográficas de la aplicación.",
    Impact = "Potential for decryption of sensitive data, compromised integrity of signed data, or breaking of secure communication channels.",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Reemplazar los algoritmos débiles con algoritmos criptográficos fuertes y modernos (por ejemplo, AES, SHA-256, RSA con tamaños de clave apropiados) y seguir las mejores prácticas para su implementación.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Impact",
    MitreTechniques = "T1557",
    VulnCwes = new List<string> { "CWE-327", "CWE-326" },
};

public static Vuln ImproperCertificateValidation => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Validación Incorrecta de Certificados",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no valida correctamente los certificados SSL/TLS, permitiendo potencialmente ataques de intermediario o conexiones a servidores maliciosos.",
    ProofOfConcept = "Demostrar la capacidad de interceptar tráfico SSL/TLS utilizando un certificado autofirmado o inválido sin que la aplicación lo detecte.",
    Impact = "Potential for eavesdropping on sensitive communications, data theft, or injection of malicious content.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar una validación adecuada de certificados, incluyendo la verificación de caducidad, revocación y coincidencia de nombres de host. Utilizar fijación de certificados para aplicaciones de alta seguridad.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Collection, Man-in-the-Middle",
    MitreTechniques = "T1557",
    VulnCwes = new List<string> { "CWE-295" },
};

public static Vuln CrossSiteRequestForgery => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Falsificación de Solicitudes entre Sitios (CSRF)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no implementa protecciones adecuadas contra CSRF, permitiendo a los atacantes engañar a los usuarios para que realicen acciones no intencionadas en la aplicación autenticada.",
    ProofOfConcept = "Crear una página web maliciosa que, cuando es visitada por un usuario autenticado, realiza una acción no autorizada en la aplicación vulnerable.",
    Impact = "Potential for unauthorized actions performed on behalf of authenticated users, such as changes to account settings or unauthorized transfers.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
    Remediation = "Implementar tokens anti-CSRF para todas las operaciones que cambian el estado, usar el atributo SameSite para las cookies y considerar la implementación de defensas adicionales como encabezados de solicitud personalizados.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Privilege Escalation",
    MitreTechniques = "T1204",
    VulnCwes = new List<string> { "CWE-352" },
};

public static Vuln InsufficientPasswordRecoveryMechanism => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Mecanismo de Recuperación de Contraseña Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "El mecanismo de recuperación de contraseña de la aplicación es débil o puede ser fácilmente eludido, permitiendo potencialmente a los atacantes tomar el control de las cuentas de usuario.",
    ProofOfConcept = "Demostrar la capacidad de restablecer la contraseña de un usuario sin la autenticación adecuada o eludiendo las medidas de seguridad.",
    Impact = "Potential for unauthorized access to user accounts, leading to data theft or account abuse.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar un proceso seguro de recuperación de contraseña utilizando tokens de recuperación de un solo uso y tiempo limitado enviados a través de canales fuera de banda. Evitar el uso de preguntas de seguridad como único método de recuperación.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access",
    MitreTechniques = "T1552",
    VulnCwes = new List<string> { "CWE-640" },
};

public static Vuln LackOfInputSanitization => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Falta de Sanitización de Entrada",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no sanitiza o valida adecuadamente la entrada del usuario, permitiendo potencialmente varios ataques de inyección u otras entradas maliciosas.",
    ProofOfConcept = "Demostrar la capacidad de inyectar cargas útiles maliciosas (por ejemplo, inyección SQL, XSS) a través de campos de entrada de usuario.",
    Impact = "Potential for data manipulation, unauthorized data access, or execution of malicious scripts, depending on the context of the unsanitized input.",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
    Remediation = "Implementar una validación y sanitización adecuada de la entrada para todas las entradas de usuario. Usar consultas parametrizadas para operaciones de base de datos, codificar la salida para prevenir XSS y validar las entradas contra una lista blanca de caracteres y formatos permitidos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-20", "CWE-79", "CWE-89" },
};

public static Vuln InsufficientSessionTimeout => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Tiempo de Espera de Sesión Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no implementa mecanismos adecuados de tiempo de espera de sesión, permitiendo que las sesiones permanezcan activas durante períodos prolongados de tiempo.",
    ProofOfConcept = "Demostrar que la sesión de un usuario permanece activa incluso después de largos períodos de inactividad o después de cerrar el navegador.",
    Impact = "Increased risk of session hijacking, especially on shared computers or in case of session token theft.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    Remediation = "Implementar mecanismos adecuados de tiempo de espera de sesión. Establecer tiempos de expiración razonables para las sesiones y asegurar que las sesiones se invaliden después del cierre de sesión del usuario o períodos prolongados de inactividad.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Defense Evasion",
    MitreTechniques = "T1497",
    VulnCwes = new List<string> { "CWE-613" },
};

public static Vuln ImproperErrorHandling => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Manejo Inadecuado de Errores",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación revela información sensible a través de mensajes de error detallados o trazas de pila, potencialmente ayudando a los atacantes a comprender la estructura y vulnerabilidades de la aplicación.",
    ProofOfConcept = "Provocar errores en la aplicación que revelen información sensible como la estructura de la base de datos, rutas de archivos o direcciones IP internas.",
    Impact = "Information disclosure that could aid attackers in further exploiting the application or underlying systems.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
    Remediation = "Implementar un manejo adecuado de errores que muestre mensajes de error genéricos a los usuarios mientras registra información detallada de errores de forma segura para los desarrolladores. Asegurar que los modos de depuración estén deshabilitados en entornos de producción.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Discovery",
    MitreTechniques = "T1082",
    VulnCwes = new List<string> { "CWE-209", "CWE-200" },
};

public static Vuln MissingSecurityHeaders => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Falta de Encabezados de Seguridad",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no implementa encabezados de seguridad importantes que pueden ayudar a proteger contra varios ataques como XSS, clickjacking y ataques de intermediario.",
    ProofOfConcept = "Analizar los encabezados de respuesta HTTP y demostrar la ausencia de encabezados de seguridad importantes como Content-Security-Policy, X-Frame-Options o Strict-Transport-Security.",
    Impact = "Increased vulnerability to various attacks that could have been mitigated by proper security headers.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar encabezados de seguridad apropiados incluyendo Content-Security-Policy, X-Frame-Options, Strict-Transport-Security, X-Content-Type-Options y Referrer-Policy. Configurar estos encabezados correctamente basándose en los requisitos de la aplicación.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Defense Evasion",
    MitreTechniques = "T1556",
    VulnCwes = new List<string> { "CWE-693", "CWE-1021" },
};

public static Vuln InsecureUseOfCryptography => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Uso Inseguro de Criptografía",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación utiliza funciones criptográficas de manera insegura, como usar tamaños de clave débiles, gestión inadecuada de claves o implementación incorrecta de protocolos criptográficos.",
    ProofOfConcept = "Identificar instancias de prácticas criptográficas inseguras, como claves de cifrado codificadas, uso del modo ECB para cifrado simétrico o validación inadecuada de certificados.",
    Impact = "Potential compromise of encrypted data, broken confidentiality or integrity of communications, or bypass of security mechanisms relying on cryptography.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Utilizar bibliotecas criptográficas bien probadas, asegurar una gestión adecuada de claves (generación, almacenamiento y rotación), usar tamaños de clave y modos de operación apropiados, y seguir las mejores prácticas para los protocolos criptográficos elegidos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Impact",
    MitreTechniques = "T1552",
    VulnCwes = new List<string> { "CWE-327", "CWE-320" },
};

public static Vuln BrokenFunctionLevelAuthorization => new Vuln
{
    Template = true,
    Language = Language.Español,
    Name = "Autorización Rota a Nivel de Función",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "La aplicación no restringe adecuadamente el acceso a ciertas funciones basándose en los roles de usuario, permitiendo a los usuarios realizar acciones para las que no deberían estar autorizados.",
    ProofOfConcept = "Demostrar el acceso a funciones administrativas o la realización de acciones privilegiadas utilizando una cuenta de usuario con privilegios bajos.",
    Impact = "Unauthorized access to sensitive functionality, potential for data theft, manipulation, or system compromise.",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar controles de acceso a nivel de función adecuados. Aplicar verificaciones de autorización de manera consistente en todas las funciones de la aplicación. Utilizar control de acceso basado en roles (RBAC) y aplicar el principio de mínimo privilegio.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Privilege Escalation",
    MitreTechniques = "T1548",
    VulnCwes = new List<string> { "CWE-285" },
};

}*/