using Cervantes.CORE.Entities;

namespace Cervantes.IFR.VulnTemplates;

public class VulnTemplatesWstgPT
{
    public static Vuln InsufficientAuthentication => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Autenticação Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não autentica adequadamente os usuários, permitindo acesso não autorizado a funcionalidades ou dados sensíveis.",
        ProofOfConcept = "Demonstrar acesso a áreas ou funções restritas sem a autenticação adequada.",
        Impact = "Acesso não autorizado a dados ou funcionalidades sensíveis, potencialmente levando a violações de dados ou comprometimento do sistema.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar mecanismos de autenticação fortes, como autenticação multifator, para todas as áreas sensíveis da aplicação.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1078",
        MitreTechniques = "T1078 - Valid Accounts",
    };

    public static Vuln WeakPasswordRequirements => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Requisitos de Senha Fracos",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação permite senhas fracas que não atendem aos requisitos mínimos de complexidade e comprimento.",
        ProofOfConcept = "Criar contas com senhas fracas que não cumprem os padrões da indústria.",
        Impact = "Maior risco de ataques de força bruta bem-sucedidos e acesso não autorizado a contas.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
        Remediation = "Implementar políticas de senhas fortes que exijam comprimento mínimo, complexidade e evitem senhas fracas comuns.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1110",
        MitreTechniques = "T1110 - Credential Access",
    };

    public static Vuln InsecureSessionManagement => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Gerenciamento de Sessão Inseguro",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não gerencia adequadamente as sessões de usuário, levando a vulnerabilidades como fixação de sessão ou expiração insuficiente de sessão.",
        ProofOfConcept = "Demonstrar o sequestro da sessão de um usuário ou o uso de um token de sessão antigo para obter acesso não autorizado.",
        Impact = "Acesso não autorizado a contas de usuário e dados sensíveis.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar práticas seguras de gerenciamento de sessões, incluindo a criação, expiração e invalidação adequada de sessões.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1539",
        MitreTechniques = "T1539 - Steal Web Session Cookie",
    };
    
    public static Vuln Idor => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Referência Direta Insegura a Objetos (IDOR)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação expõe uma referência direta a objetos de implementação interna, como arquivos, diretórios, registros de banco de dados ou chaves, sem qualquer controle de acesso ou validação.",
        ProofOfConcept = "Demonstrar o acesso ou modificação de recursos pertencentes a outros usuários manipulando referências a objetos nas solicitações.",
        Impact = "Acesso não autorizado a dados sensíveis, possível roubo de dados ou manipulação de informações de outros usuários.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar controles de acesso adequados e usar referências indiretas a objetos que sejam mapeadas para dados específicos do usuário no lado do servidor.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1213",
        MitreTechniques = "T1213 - Data from Information Repositories",
    };

    public static Vuln CrossSiteScripting => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Cross-Site Scripting (XSS)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não valida ou codifica adequadamente a entrada do usuário antes de renderizá-la em uma página web, permitindo que atacantes injetem e executem scripts maliciosos no contexto dos navegadores de outros usuários.",
        ProofOfConcept = "Demonstrar a injeção de um script que é executado no navegador da vítima, como exibir uma caixa de alerta ou roubar cookies de sessão.",
        Impact = "Possível roubo de sessões de usuário, desfiguração de sites, redirecionamento de usuários para sites maliciosos ou execução de código arbitrário no navegador do usuário.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar validação de entrada adequada, codificação de saída e usar cabeçalhos de Política de Segurança de Conteúdo (CSP) para mitigar os riscos de XSS.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1189",
        MitreTechniques = "T1189 - Drive-by Compromise",
    };

    public static Vuln InsecureCryptographicStorage => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Armazenamento Criptográfico Inseguro",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação armazena dados sensíveis usando algoritmos criptográficos fracos ou desatualizados, ou implementa incorretamente funções criptográficas.",
        ProofOfConcept = "Demonstrar a capacidade de decifrar dados sensíveis utilizando fraquezas conhecidas na implementação criptográfica.",
        Impact = "Acesso não autorizado a dados sensíveis, potencialmente levando a roubo de identidade, fraude financeira ou outras atividades maliciosas.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Utilizar algoritmos criptográficos fortes e padrão da indústria e implementá-los corretamente. Garantir práticas adequadas de gerenciamento de chaves.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1552",
        MitreTechniques = "T1552 - Unsecured Credentials",
    };

    public static Vuln InsecureDeserialization => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Desserialização Insegura",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação desserializa dados não confiáveis sem verificação suficiente, potencialmente permitindo que atacantes executem código arbitrário ou manipulem a lógica da aplicação.",
        ProofOfConcept = "Criar um objeto serializado malicioso que, ao ser desserializado, execute comandos não autorizados ou altere o comportamento da aplicação.",
        Impact = "Execução remota de código, manipulação de dados ou negação de serviço.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar verificações de tipo estritas, usar práticas de desserialização seguras e evitar desserializar dados não confiáveis quando possível.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1203",
        MitreTechniques = "T1203 - Exploitation for Client Execution",
    };

    public static Vuln SqlInjection => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Injeção SQL",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Critical,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação constrói consultas SQL usando entrada fornecida pelo usuário sem a sanitização ou parametrização adequada, permitindo que atacantes modifiquem ou executem comandos SQL arbitrários.",
        ProofOfConcept = "Demonstrar a capacidade de recuperar dados não autorizados ou executar comandos no banco de dados através da injeção de SQL malicioso.",
        Impact = "Acesso não autorizado a dados sensíveis, manipulação de dados e potencial comprometimento completo do banco de dados e sistemas conectados.",
        CVSS3 = 9.8,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Utilizar consultas parametrizadas ou declarações preparadas, implementar uma validação de entrada adequada e aplicar o princípio de menor privilégio para as contas de banco de dados.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
    public static Vuln BrokenAccessControl => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Controle de Acesso Quebrado",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação falha em fazer cumprir adequadamente os controles de acesso, permitindo que os usuários realizem ações ou acessem recursos para os quais não deveriam ter permissões.",
        ProofOfConcept = "Demonstrar o acesso a funcionalidades ou dados não autorizados manipulando parâmetros de solicitação ou utilizando uma conta com privilégios menores.",
        Impact = "Acesso não autorizado a dados ou funcionalidades sensíveis, possível roubo de dados ou manipulação de informações de outros usuários.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar e fazer cumprir controles de acesso adequados tanto a nível de aplicação quanto de API. Utilizar controle de acesso baseado em funções (RBAC) e o princípio de menor privilégio.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1548",
        MitreTechniques = "T1548 - Abuse Elevation Control Mechanism",
    };
    
    public static Vuln SecurityMisconfiguration => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Configuração Incorreta de Segurança",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação, o framework, o servidor web ou a plataforma estão configurados de maneira insegura, potencialmente expondo informações sensíveis ou permitindo acesso não autorizado.",
        ProofOfConcept = "Identificar e explorar configurações padrão, serviços abertos desnecessários ou informações do sistema expostas.",
        Impact = "Acesso não autorizado a funções ou dados da aplicação, comprometimento do sistema ou divulgação de informações.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        Remediation = "Implementar práticas de configuração segura, desabilitar recursos desnecessários, usar cabeçalhos de segurança e atualizar e corrigir regularmente todos os componentes.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1082",
        MitreTechniques = "T1082 - System Information Discovery",
    };

    public static Vuln SensitiveDataExposure => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Exposição de Dados Sensíveis",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não protege adequadamente informações sensíveis, como dados financeiros, informações de saúde ou informações pessoais identificáveis (PII).",
        ProofOfConcept = "Interceptar transmissões de dados não criptografados ou acessar armazenamento de dados sensíveis inadequadamente protegido.",
        Impact = "Exposição de dados sensíveis de usuários, potencial de roubo de identidade, fraude financeira ou violação de regulamentos de proteção de dados.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        Remediation = "Criptografar dados sensíveis em trânsito e em repouso, implementar gerenciamento adequado de chaves e minimizar a exposição de dados sensíveis em logs e mensagens de erro.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1005",
        MitreTechniques = "T1005 - Data from Local System",
    };

    public static Vuln InsufficientLoggingAndMonitoring => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Registro e Monitoramento Insuficientes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não gera registros adequados para eventos de segurança, ou falha em monitorar e responder a incidentes de segurança de maneira oportuna.",
        ProofOfConcept = "Realizar atividades suspeitas sem detecção, ou demonstrar a falta de trilhas de auditoria adequadas para operações críticas.",
        Impact = "Detecção atrasada ou perdida de atividades maliciosas, capacidades de resposta a incidentes e análise forense prejudicadas.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar registro abrangente para eventos relevantes de segurança, garantir o armazenamento e proteção adequados dos logs, e estabelecer mecanismos eficazes de monitoramento e alerta.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1562",
        MitreTechniques = "T1562 - Impair Defenses",
    };

    public static Vuln UsingComponentsWithKnownVulnerabilities => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Uso de Componentes com Vulnerabilidades Conhecidas",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza componentes, bibliotecas ou frameworks de terceiros com vulnerabilidades de segurança conhecidas.",
        ProofOfConcept = "Identificar componentes desatualizados e demonstrar a exploração de vulnerabilidades conhecidas nesses componentes.",
        Impact = "Potencial para vários tipos de ataques dependendo da vulnerabilidade, incluindo roubo de dados, execução remota de código ou comprometimento da aplicação.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Atualizar e corrigir regularmente todos os componentes, implementar uma ferramenta de análise de composição de software e manter um inventário de todos os componentes utilizados e suas versões.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln ServerSideRequestForgery => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falsificação de Solicitação do Lado do Servidor (SSRF)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação processa URLs ou caminhos de arquivo fornecidos pelo usuário para recuperar recursos, permitindo que um atacante manipule solicitações para acessar recursos internos ou realizar ações não autorizadas.",
        ProofOfConcept = "Demonstrar a capacidade de fazer com que o servidor solicite recursos internos ou sites externos controlados pelo atacante.",
        Impact = "Possível acesso a sistemas internos, exfiltração de dados ou execução remota de código em alguns casos.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:H",
        Remediation = "Implementar uma validação de entrada rigorosa, usar listas brancas para URLs ou domínios permitidos, desabilitar esquemas de URL desnecessários e usar um servidor separado para realizar solicitações externas.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

     public static Vuln XmlExternalEntityProcessing => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Processamento de Entidades Externas XML (XXE)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação processa entrada XML que inclui referências a entidades externas sem a validação adequada, permitindo que os atacantes revelem arquivos internos, realizem falsificação de solicitação do lado do servidor ou executem ataques de negação de serviço.",
        ProofOfConcept = "Demonstrar a capacidade de ler arquivos internos ou fazer com que o servidor se conecte a hosts arbitrários usando entrada XML que contém entidades externas maliciosas.",
        Impact = "Possível divulgação de dados sensíveis, falsificação de solicitação do lado do servidor ou negação de serviço.",
        CVSS3 = 8.2,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:H",
        Remediation = "Desabilitar o processamento de entidades externas XML e DTD em todos os analisadores XML da aplicação, usar formatos de dados menos complexos como JSON quando possível, e validar e sanear toda a entrada XML.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln LackOfRateLimiting => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falta de Limitação de Taxa",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não implementa mecanismos adequados de limitação de taxa, permitindo que os atacantes realizem um número excessivo de solicitações ou operações.",
        ProofOfConcept = "Demonstrar a capacidade de realizar um grande número de solicitações em um curto período de tempo sem qualquer restrição.",
        Impact = "Potencial para negação de serviço, ataques de força bruta ou consumo excessivo de recursos.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
        Remediation = "Implementar limitação de taxa em todos os endpoints da API e funções críticas. Utilizar técnicas como algoritmos de balde de tokens ou contadores de janela fixa para restringir o número de solicitações que um usuário pode fazer em um determinado período de tempo.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1499",
        MitreTechniques = "T1499 - Endpoint Denial of Service",
    };
    
    public static Vuln InadequateOAuth2Implementation => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Implementação Inadequada de OAuth 2.0",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A implementação de OAuth 2.0 da aplicação contém falhas de segurança, como validação incorreta de URIs de redirecionamento, armazenamento inseguro de tokens ou manipulação incorreta de parâmetros de estado.",
        ProofOfConcept = "Demonstrar a capacidade de realizar roubo de tokens, tomada de controle de contas ou acesso não autorizado através de falhas na implementação de OAuth.",
        Impact = "Potencial de acesso não autorizado a contas de usuário, roubo de dados ou personificação de usuários.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
        Remediation = "Implementar OAuth 2.0 de forma segura seguindo as melhores práticas: validar todas as URIs de redirecionamento, usar parâmetros de estado para prevenir CSRF, armazenar e transmitir tokens de forma segura, e implementar uma validação e expiração adequada de tokens.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1550",
        MitreTechniques = "T1550 - Use Alternate Authentication Material",
    };
    
    public static Vuln InsufficientAntiAutomation => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Anti-Automação Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação carece de medidas suficientes para prevenir ataques automatizados, como preenchimento de credenciais, tentativas de força bruta ou raspagem de conteúdo.",
        ProofOfConcept = "Demonstrar a capacidade de realizar solicitações automatizadas de alto volume sem acionar nenhum mecanismo defensivo.",
        Impact = "Potencial de tomada de controle de contas, coleta de dados ou degradação do serviço através de ataques automatizados.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar medidas anti-automação como CAPTCHA, limitação de taxa, restrições baseadas em IP e análise de comportamento para detectar e prevenir ataques automatizados.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1110",
        MitreTechniques = "T1110 - Brute Force",
    };
    
    public static Vuln WeakCryptographicAlgorithms => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Algoritmos Criptográficos Fracos",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza algoritmos criptográficos fracos ou desatualizados que são suscetíveis a ataques.",
        ProofOfConcept = "Identificar o uso de algoritmos fracos (por exemplo, MD5, SHA1, DES) nas operações criptográficas da aplicação.",
        Impact = "Potencial de decifração de dados sensíveis, comprometimento da integridade de dados assinados ou quebra de canais de comunicação seguros.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Substituir algoritmos fracos por algoritmos criptográficos fortes e modernos (por exemplo, AES, SHA-256, RSA com tamanhos de chave apropriados) e seguir as melhores práticas para sua implementação.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1557",
        MitreTechniques = "T1557 - Adversary-in-the-Middle",
    };

    public static Vuln ImproperCertificateValidation => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Validação Incorreta de Certificados",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não valida adequadamente os certificados SSL/TLS, potencialmente permitindo ataques de homem no meio ou conexões com servidores maliciosos.",
        ProofOfConcept = "Demonstrar a capacidade de interceptar tráfego SSL/TLS usando um certificado autoassinado ou inválido sem que a aplicação o detecte.",
        Impact = "Potencial de interceptação de comunicações sensíveis, roubo de dados ou injeção de conteúdo malicioso.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar uma validação adequada de certificados, incluindo a verificação de expiração, revogação e correspondência de nomes de host. Usar fixação de certificados para aplicações de alta segurança.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1557",
        MitreTechniques = "T1557 - Adversary-in-the-Middle",
    };

    public static Vuln CrossSiteRequestForgery => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falsificação de Solicitação Entre Sites (CSRF)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não implementa proteções CSRF adequadas, permitindo que os atacantes enganem os usuários para que realizem ações não intencionais na aplicação autenticada.",
        ProofOfConcept = "Criar uma página web maliciosa que, quando visitada por um usuário autenticado, realiza uma ação não autorizada na aplicação vulnerável.",
        Impact = "Potencial de ações não autorizadas realizadas em nome de usuários autenticados, como alterações nas configurações da conta ou transferências não autorizadas.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        Remediation = "Implementar tokens anti-CSRF para todas as operações que alteram o estado, usar o atributo SameSite para os cookies e considerar a implementação de defesas adicionais como cabeçalhos de solicitação personalizados.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1204",
        MitreTechniques = "T1204 - User Execution",
    };

    public static Vuln InsufficientPasswordRecoveryMechanism => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Mecanismo de Recuperação de Senha Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "O mecanismo de recuperação de senha da aplicação é fraco ou pode ser facilmente contornado, potencialmente permitindo que os atacantes assumam o controle das contas dos usuários.",
        ProofOfConcept = "Demonstrar a capacidade de redefinir a senha de um usuário sem a autenticação adequada ou contornando medidas de segurança.",
        Impact = "Potencial de acesso não autorizado a contas de usuários, levando a roubo de dados ou abuso de contas.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar um processo seguro de recuperação de senha utilizando tokens de recuperação de uso único e tempo limitado enviados através de canais fora de banda. Evitar o uso de perguntas de segurança como único método de recuperação.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1552",
        MitreTechniques = "T1552 - Unsecured Credentials",
    };

    public static Vuln LackOfInputSanitization => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falta de Sanitização de Entrada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não sanitiza ou valida adequadamente a entrada do usuário, potencialmente permitindo vários ataques de injeção ou outras entradas maliciosas.",
        ProofOfConcept = "Demonstrar a capacidade de injetar payloads maliciosos (por exemplo, injeção SQL, XSS) através de campos de entrada do usuário.",
        Impact = "Potencial de manipulação de dados, acesso não autorizado a dados ou execução de scripts maliciosos, dependendo do contexto da entrada não sanitizada.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        Remediation = "Implementar uma validação e sanitização de entrada adequadas para todas as entradas do usuário. Usar consultas parametrizadas para operações de banco de dados, codificar a saída para prevenção de XSS e validar as entradas contra uma lista branca de caracteres e formatos permitidos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
    
    public static Vuln InsufficientSessionTimeout => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Tempo Limite de Sessão Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não implementa mecanismos adequados de tempo limite de sessão, permitindo que as sessões permaneçam ativas por períodos prolongados de tempo.",
        ProofOfConcept = "Demonstrar que a sessão de um usuário permanece ativa mesmo após longos períodos de inatividade ou após fechar o navegador.",
        Impact = "Maior risco de sequestro de sessão, especialmente em computadores compartilhados ou em caso de roubo de token de sessão.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
        Remediation = "Implementar mecanismos adequados de tempo limite de sessão. Estabelecer tempos de expiração razoáveis para as sessões e garantir que as sessões sejam invalidadas após o logout do usuário ou períodos prolongados de inatividade.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln ImproperErrorHandling => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Tratamento Inadequado de Erros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação revela informações sensíveis através de mensagens de erro detalhadas ou traces de pilha, potencialmente auxiliando os atacantes a entender a estrutura e vulnerabilidades da aplicação.",
        ProofOfConcept = "Provocar erros na aplicação que revelem informações sensíveis como estrutura do banco de dados, caminhos de arquivos ou endereços IP internos.",
        Impact = "Divulgação de informações que poderiam ajudar os atacantes a explorar ainda mais a aplicação ou os sistemas subjacentes.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        Remediation = "Implementar um tratamento de erros adequado que mostre mensagens de erro genéricas aos usuários enquanto registra informações detalhadas de erros de forma segura para os desenvolvedores. Garantir que os modos de depuração estejam desativados em ambientes de produção.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1082",
        MitreTechniques = "T1082 - System Information Discovery",
    };

    public static Vuln MissingSecurityHeaders => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Cabeçalhos de Segurança Ausentes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não implementa cabeçalhos de segurança importantes que podem ajudar a proteger contra vários ataques como XSS, clickjacking e ataques de homem no meio.",
        ProofOfConcept = "Analisar os cabeçalhos de resposta HTTP e demonstrar a ausência de cabeçalhos de segurança importantes como Content-Security-Policy, X-Frame-Options ou Strict-Transport-Security.",
        Impact = "Maior vulnerabilidade a vários ataques que poderiam ter sido mitigados com cabeçalhos de segurança adequados.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar cabeçalhos de segurança apropriados incluindo Content-Security-Policy, X-Frame-Options, Strict-Transport-Security, X-Content-Type-Options e Referrer-Policy. Configurar esses cabeçalhos corretamente com base nos requisitos da aplicação.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln InsecureUseOfCryptography => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Uso Inseguro de Criptografia",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza funções criptográficas de maneira insegura, como usar tamanhos de chave fracos, gerenciamento inadequado de chaves ou implementação incorreta de protocolos criptográficos.",
        ProofOfConcept = "Identificar instâncias de práticas criptográficas inseguras, como chaves de criptografia codificadas, uso do modo ECB para criptografia simétrica ou validação inadequada de certificados.",
        Impact = "Possível comprometimento de dados criptografados, quebra da confidencialidade ou integridade das comunicações, ou contorno de mecanismos de segurança que dependem da criptografia.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Usar bibliotecas criptográficas bem testadas, garantir um gerenciamento adequado de chaves (geração, armazenamento e rotação), usar tamanhos de chave e modos de operação apropriados, e seguir as melhores práticas para os protocolos criptográficos escolhidos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1552",
        MitreTechniques = "T1552 - Unsecured Credentials",
    };

    public static Vuln BrokenFunctionLevelAuthorization => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Autorização em Nível de Função Quebrada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não restringe adequadamente o acesso a certas funções com base nos papéis do usuário, permitindo que os usuários realizem ações para as quais não deveriam estar autorizados.",
        ProofOfConcept = "Demonstrar o acesso a funções administrativas ou a realização de ações privilegiadas utilizando uma conta de usuário com privilégios baixos.",
        Impact = "Acesso não autorizado a funcionalidades sensíveis, potencial de roubo de dados, manipulação ou comprometimento do sistema.",
        CVSS3 = 8.8,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar controles de acesso adequados em nível de função. Fazer cumprir as verificações de autorização de maneira consistente em todas as funções da aplicação. Usar controle de acesso baseado em papéis (RBAC) e aplicar o princípio do menor privilégio.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1548",
        MitreTechniques = "T1548 - Abuse Elevation Control Mechanism",
    };
    
    public static Vuln InsecureCommunicationChannels => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Canais de Comunicação Inseguros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza protocolos inseguros ou criptografia fraca para a transmissão de dados, potencialmente expondo informações sensíveis a interceptação ou manipulação.",
        ProofOfConcept = "Demonstrar a capacidade de interceptar e ler dados sensíveis em trânsito, ou mostrar o uso de protocolos obsoletos como SSLv3 ou TLS 1.0.",
        Impact = "Possível exposição de dados sensíveis, incluindo credenciais, informações pessoais ou dados críticos do negócio a partes não autorizadas.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar protocolos de comunicação seguros (TLS 1.2 ou superior) para todas as transmissões de dados. Garantir a configuração adequada de algoritmos de criptografia e tamanhos de chave. Usar fixação de certificados para aplicações móveis.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1040",
        MitreTechniques = "T1040 - Network Sniffing",
    };

    public static Vuln LackOfSecureDefaults => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falta de Configurações Seguras por Padrão",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação ou seus componentes são implantados com configurações padrão inseguras, potencialmente expondo o sistema a riscos desnecessários.",
        ProofOfConcept = "Identificar contas padrão com senhas fracas, serviços desnecessários habilitados por padrão ou permissões padrão excessivamente permissivas.",
        Impact = "Maior superfície de ataque e potencial de exploração de recursos ou serviços desnecessários.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar uma abordagem de 'seguro por padrão'. Desabilitar recursos e serviços desnecessários, remover contas padrão ou alterar suas credenciais, e aplicar princípios de menor privilégio às configurações padrão.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };
    
    public static Vuln InsufficientProtectionFromAutomatedThreats => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Proteção Insuficiente contra Ameaças Automatizadas",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação carece de defesas adequadas contra ataques automatizados como preenchimento de credenciais, tentativas de força bruta ou raspagem de conteúdo.",
        ProofOfConcept = "Demonstrar a capacidade de realizar um alto volume de solicitações (por exemplo, tentativas de login ou recuperação de dados) sem acionar nenhum mecanismo defensivo.",
        Impact = "Maior risco de tomada de controle de contas, coleta de dados ou degradação do serviço devido a ataques automatizados.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar limitação de taxa, desafios CAPTCHA, bloqueios de contas e restrições baseadas em IP. Utilizar análise de comportamento para detectar e prevenir ataques automatizados. Considerar o uso de firewalls de aplicações web (WAF) para proteção adicional.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1110",
        MitreTechniques = "T1110 - Brute Force",
    };
    
    public static Vuln UnvalidatedRedirectsAndForwards => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Redirecionamentos e Encaminhamentos não Validados",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação redireciona ou encaminha usuários para sites potencialmente maliciosos sem uma validação adequada da URL de destino.",
        ProofOfConcept = "Demonstrar a capacidade de manipular parâmetros de redirecionamento para enviar usuários a sites externos arbitrários.",
        Impact = "Potencial para ataques de phishing, distribuição de malware ou engenharia social ao redirecionar usuários para sites maliciosos.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar uma validação rigorosa de todos os destinos de redirecionamento. Utilizar uma lista branca de destinos permitidos ou validar contra um padrão de URLs conhecidas como seguras. Evitar o uso de entrada fornecida pelo usuário diretamente em funções de redirecionamento.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1566",
        MitreTechniques = "T1566 - Phishing",
    };

    public static Vuln InsecureAuthenticationMechanism => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Mecanismo de Autenticação Inseguro",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza mecanismos de autenticação fracos ou facilmente contornáveis, permitindo potencialmente o acesso não autorizado a contas de usuário.",
        ProofOfConcept = "Demonstrar a evasão de controles de autenticação ou a exploração de fraquezas no processo de autenticação.",
        Impact = "Acesso não autorizado a contas de usuário, potencial de roubo de identidade, vazamento de dados ou comprometimento do sistema.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar mecanismos de autenticação fortes e multifator. Utilizar gerenciamento seguro de sessões, aplicar políticas de senhas e considerar o uso de provedores de identidade federados para uma segurança aprimorada.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1078",
        MitreTechniques = "T1078 - Valid Accounts",
    };

    public static Vuln InsufficientAntiCachingHeaders => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Cabeçalhos Anti-Cache Insuficientes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não define cabeçalhos de controle de cache adequados, potencialmente permitindo que informações sensíveis sejam armazenadas em caches de navegadores ou proxies intermediários.",
        ProofOfConcept = "Demonstrar a capacidade de recuperar informações sensíveis do cache do navegador ou mostrar que páginas sensíveis são armazenadas em cache por proxies.",
        Impact = "Potencial exposição de dados sensíveis a partes não autorizadas, especialmente em computadores compartilhados ou através de ataques de homem no meio.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        Remediation = "Implementar cabeçalhos de controle de cache adequados (por exemplo, Cache-Control: no-store, no-cache, must-revalidate) para páginas que contêm informações sensíveis. Utilizar HTTPS para prevenir o armazenamento em cache por proxies intermediários.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1557",
        MitreTechniques = "T1557 - Adversary-in-the-Middle",
    };
    
    public static Vuln LackOfProperTLSConfiguration => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falta de Configuração Adequada de TLS",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza configurações TLS fracas ou obsoletas, expondo potencialmente as comunicações a interceptação ou manipulação.",
        ProofOfConcept = "Demonstrar o uso de suites de cifra fracas, versões TLS obsoletas ou validação de certificados mal configurada.",
        Impact = "Potencial para ataques de homem no meio, interceptação de dados ou degradação das comunicações criptografadas.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Configurar TLS para usar apenas suites de cifra fortes, desabilitar versões TLS antigas (1.0, 1.1), garantir a validação adequada de certificados e implementar HSTS. Revisar e atualizar regularmente as configurações TLS.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1573",
        MitreTechniques = "T1573 - Encrypted Channel",
    };

    public static Vuln InsufficientDataProtection => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Proteção Insuficiente de Dados em Trânsito e em Repouso",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não protege adequadamente os dados sensíveis durante a transmissão ou o armazenamento, expondo-os potencialmente a acesso ou manipulação não autorizados.",
        ProofOfConcept = "Demonstrar a capacidade de interceptar dados não criptografados em trânsito ou acessar dados sensíveis armazenados de maneira insegura.",
        Impact = "Possível exposição de dados sensíveis de usuários, violações de conformidade e maior risco de vazamento de dados.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar criptografia forte para dados em trânsito (por exemplo, TLS) e em repouso (por exemplo, criptografia a nível de arquivo ou banco de dados). Utilizar práticas seguras de gerenciamento de chaves e garantir que todos os dados sensíveis estejam identificados e protegidos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1040,T1029",
        MitreTechniques = "T1040 - Network Sniffing, T1029 - Scheduled Transfer",
    };
    
    public static Vuln ImproperAssetManagement => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Gerenciamento Inadequado de Ativos",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A organização carece de um inventário e gerenciamento adequados de seus ativos de TI, o que potencialmente leva a sistemas sem patches, servidores esquecidos ou dispositivos não autorizados na rede.",
        ProofOfConcept = "Identificar sistemas não gerenciados ou esquecidos, versões de software obsoletas ou dispositivos não autorizados conectados à rede.",
        Impact = "Maior superfície de ataque, potencial de comprometimentos não detectados e dificuldade para manter uma postura de segurança geral.",
        CVSS3 = 5.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar um sistema abrangente de gerenciamento de ativos. Inventariar e atualizar regularmente todos os ativos de TI, incluindo hardware, software e recursos na nuvem. Estabelecer processos para o gerenciamento do ciclo de vida dos ativos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1046",
        MitreTechniques = "T1046 - Network Service Discovery",
    };
    
    public static Vuln LackOfSoftwareUpdates => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falta de Atualizações de Software/Gerenciamento de Patches",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação ou seus sistemas subjacentes não são atualizados regularmente, deixando potencialmente vulnerabilidades conhecidas sem correção.",
        ProofOfConcept = "Identificar versões de software desatualizadas com vulnerabilidades conhecidas que poderiam ser exploradas.",
        Impact = "Maior risco de exploração de vulnerabilidades conhecidas, potencialmente levando a comprometimento do sistema, vazamentos de dados ou interrupções do serviço.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar um processo robusto de gerenciamento de patches. Atualizar regularmente todos os componentes de software, incluindo a aplicação, bibliotecas, frameworks e sistemas operacionais. Automatizar o processo de aplicação de patches quando possível.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln InsufficientPrivacyControls => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Controles de Privacidade Insuficientes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação carece de controles adequados para proteger a privacidade do usuário, potencialmente violando as regulamentações de proteção de dados ou as expectativas do usuário.",
        ProofOfConcept = "Demonstrar a coleta, processamento ou compartilhamento de dados pessoais sem o consentimento adequado ou além dos propósitos declarados.",
        Impact = "Possíveis violações legais e regulatórias, perda de confiança do usuário e potenciais sanções financeiras.",
        CVSS3 = 5.9,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
        Remediation = "Implementar princípios de privacidade por design. Realizar avaliações de impacto na privacidade, obter o consentimento adequado do usuário para a coleta e processamento de dados, e fornecer políticas de privacidade claras. Implementar princípios de minimização de dados e limitação de propósito.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1005",
        MitreTechniques = "T1005 - Data from Local System",
    };

    public static Vuln InsecureAPIEndpoints => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Endpoints de API Inseguros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "Os endpoints da API da aplicação carecem de controles de segurança adequados, permitindo potencialmente acesso não autorizado, manipulação de dados ou divulgação de informações.",
        ProofOfConcept = "Demonstrar acesso não autorizado a endpoints da API, manipulação de dados ou extração de informações sensíveis através de chamadas à API.",
        Impact = "Potencial de vazamentos de dados, ações não autorizadas ou comprometimento do sistema através da exploração da API.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar autenticação e autorização fortes para todos os endpoints da API. Utilizar chaves de API, tokens OAuth ou outros métodos seguros. Validar e sanitizar todas as entradas da API, implementar limitação de taxa e usar HTTPS para todas as comunicações da API.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
    
    public static Vuln InsufficientInputValidation => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Validação de Entrada Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não valida adequadamente a entrada do usuário, permitindo potencialmente ataques de injeção, estouro de buffer ou outras entradas maliciosas.",
        ProofOfConcept = "Demonstrar a capacidade de inserir dados maliciosos que são processados pela aplicação sem uma validação ou sanitização adequada.",
        Impact = "Potencial para vários ataques incluindo injeção SQL, XSS, injeção de comandos ou travamentos da aplicação.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar uma validação rigorosa de entrada para todos os dados fornecidos pelo usuário. Usar listas brancas, sanitização de entrada e consultas parametrizadas. Validar a entrada por tipo, comprimento, formato e intervalo conforme apropriado.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln ImproperOutputEncoding => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Codificação de Saída Inadequada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não codifica adequadamente a saída antes de renderizá-la aos usuários, permitindo potencialmente ataques de injeção como Cross-Site Scripting (XSS).",
        ProofOfConcept = "Demonstrar a capacidade de injetar e executar scripts ou HTML maliciosos na saída da aplicação.",
        Impact = "Potencial para ataques do lado do cliente, roubo de dados, sequestro de sessões ou desfiguração da aplicação.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar codificação de saída contextual para todo o conteúdo dinâmico. Usar funções de codificação apropriadas para contextos HTML, JavaScript, CSS e URL. Considerar o uso de motores de template com escape automático.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1189",
        MitreTechniques = "T1189 - Drive-by Compromise",
    };

    public static Vuln InsecureFileHandling => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Manipulação Insegura de Arquivos",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não valida ou manipula adequadamente as operações de arquivo, permitindo potencialmente acesso não autorizado, inclusão de arquivos ou execução de arquivos maliciosos.",
        ProofOfConcept = "Demonstrar a capacidade de acessar arquivos fora dos diretórios pretendidos, fazer upload de arquivos maliciosos ou executar arquivos arbitrários no servidor.",
        Impact = "Potencial de acesso não autorizado a arquivos sensíveis, execução remota de código ou comprometimento do servidor.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar uma validação rigorosa de entrada para nomes e caminhos de arquivo. Usar listas brancas para tipos e extensões de arquivo permitidos. Armazenar os arquivos enviados pelo usuário fora da raiz web e utilizar bibliotecas seguras de manipulação de arquivos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln LackOfSecurePasswordStorage => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Falta de Armazenamento Seguro de Senhas",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Critical,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação não armazena de forma segura as senhas dos usuários, expondo-as potencialmente a acesso não autorizado ou tornando-as vulneráveis a tentativas de descriptografia.",
        ProofOfConcept = "Demonstrar que as senhas são armazenadas em texto claro, usando algoritmos de hash fracos ou sem um salting adequado.",
        Impact = "Potencial de acesso não autorizado a contas de usuário, comprometimento massivo de contas em caso de vazamento de dados.",
        CVSS3 = 9.8,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Utilizar algoritmos de hash adaptativos fortes (por exemplo, bcrypt, Argon2) para o armazenamento de senhas. Implementar salting adequado e garantir fatores de trabalho suficientes. Nunca armazenar senhas em texto claro ou usando criptografia reversível.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };
    
    public static Vuln InsufficientProtectionAgainstDoS => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Proteção Insuficiente Contra Negação de Serviço",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação carece de medidas adequadas para se proteger contra ataques de Negação de Serviço (DoS), permitindo potencialmente que os atacantes sobrecarreguem os recursos do sistema e interrompam a disponibilidade do serviço.",
        ProofOfConcept = "Demonstrar a capacidade de consumir recursos excessivos ou acionar operações intensivas em recursos sem limitações adequadas.",
        Impact = "Potencial de interrupção do serviço, degradação do desempenho ou indisponibilidade completa do sistema.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        Remediation = "Implementar limitação de taxa, regulação de requisições e cotas de recursos. Usar algoritmos eficientes e cache onde apropriado. Considerar a implementação de CAPTCHAs para operações sensíveis e implantar soluções de mitigação de DoS em nível de rede.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1498",
        MitreTechniques = "T1498 - Network Denial of Service",
    };
    
    public static Vuln InsufficientSubresourceIntegrity => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Integridade de Sub-recursos Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação carrega recursos externos (como scripts ou folhas de estilo) sem verificações de integridade adequadas, permitindo potencialmente que atacantes injetem conteúdo malicioso através de recursos de terceiros comprometidos.",
        ProofOfConcept = "Demonstrar que a aplicação carrega recursos externos sem verificações de Integridade de Sub-recursos (SRI), tornando-a vulnerável a ataques de cadeia de suprimentos.",
        Impact = "Potencial de execução de scripts não autorizados, levando a roubo de dados, desfiguração ou outros ataques do lado do cliente.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar Integridade de Sub-recursos (SRI) para todos os recursos carregados externamente. Usar atributos de integridade com hashes criptográficos para garantir a integridade dos recursos carregados.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1195",
        MitreTechniques = "T1195 - Supply Chain Compromise",
    };
    
    public static Vuln InadequateSecurityArchitecture => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Arquitetura de Segurança Inadequada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A arquitetura de segurança da aplicação é insuficiente, carecendo de controles de segurança adequados, padrões de design seguro ou uma abordagem de defesa em profundidade.",
        ProofOfConcept = "Demonstrar falhas arquitetônicas que permitem contornar múltiplas camadas de segurança ou explorar fraquezas sistêmicas no design da aplicação.",
        Impact = "Maior vulnerabilidade a vários ataques devido a fraquezas sistêmicas, potencialmente levando a comprometimentos ou vazamentos de dados em larga escala.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar uma arquitetura de segurança robusta seguindo princípios como defesa em profundidade, privilégio mínimo e segurança por design. Realizar revisões regulares da arquitetura e garantir o alinhamento com as melhores práticas de segurança.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln FlawedBusinessLogic => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Lógica de Negócio Falha",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação contém falhas na implementação de sua lógica de negócio, permitindo que os usuários realizem ações que violam o processo de negócio pretendido ou as suposições de segurança.",
        ProofOfConcept = "Demonstrar a capacidade de manipular os processos de negócio da aplicação, como contornar pagamentos, alterar quantidades de pedidos ou acessar descontos não autorizados.",
        Impact = "Potencial de perdas financeiras, acesso não autorizado a serviços ou manipulação de processos de negócio críticos.",
        CVSS3 = 7.7,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N",
        Remediation = "Implementar uma validação abrangente da lógica de negócio. Garantir que todos os processos de negócio estejam corretamente modelados e aplicados na aplicação. Realizar revisões por pares da implementação da lógica de negócio e conduzir testes exaustivos de cenários de negócio.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };
    
    public static Vuln InsecureThirdPartyComponents => new Vuln
    {
        Template = true,
        Language = Language.Português,
        Name = "Componentes de Terceiros Inseguros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "A aplicação utiliza componentes, bibliotecas ou frameworks de terceiros que estão desatualizados, contêm vulnerabilidades conhecidas ou são obtidos de fontes não confiáveis.",
        ProofOfConcept = "Identificar e demonstrar a exploração de vulnerabilidades conhecidas em componentes de terceiros utilizados pela aplicação.",
        Impact = "Potencial para vários tipos de ataques dependendo das vulnerabilidades nos componentes, incluindo roubo de dados, execução remota de código ou comprometimento da aplicação.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar uma ferramenta de análise de composição de software (SCA) para rastrear e gerenciar componentes de terceiros. Atualizar regularmente os componentes para suas versões seguras mais recentes. Estabelecer um processo para avaliar e aprovar código de terceiros. Usar fontes confiáveis para obter componentes.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
}