using Cervantes.CORE.Entities;

namespace Cervantes.IFR;

public class VulnTemplatesWstgES
{
   public static Vuln InsufficientAuthentication => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Autenticación Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no autentica adecuadamente a los usuarios, permitiendo el acceso no autorizado a funcionalidades o datos sensibles.",
        ProofOfConcept = "Demostrar acceso a áreas o funciones restringidas sin la autenticación adecuada.",
        Impact = "Acceso no autorizado a datos o funcionalidades sensibles, potencialmente llevando a brechas de datos o compromiso del sistema.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar mecanismos de autenticación fuertes, como autenticación multifactor, para todas las áreas sensibles de la aplicación.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1078",
        MitreTechniques = "T1078 - Valid Accounts",
    };

    public static Vuln WeakPasswordRequirements => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Requisitos de Contraseña Débiles",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación permite contraseñas débiles que no cumplen con los requisitos mínimos de complejidad y longitud.",
        ProofOfConcept = "Crear cuentas con contraseñas débiles que no cumplen con los estándares de la industria.",
        Impact = "Mayor riesgo de ataques de fuerza bruta exitosos y acceso no autorizado a cuentas.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
        Remediation = "Implementar políticas de contraseñas fuertes que requieran longitud mínima, complejidad y eviten contraseñas débiles comunes.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1110",
        MitreTechniques = "T1110 - Credential Access",
    };

    public static Vuln InsecureSessionManagement => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Gestión Insegura de Sesiones",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no gestiona adecuadamente las sesiones de usuario, lo que lleva a vulnerabilidades como fijación de sesión o expiración insuficiente de sesión.",
        ProofOfConcept = "Demostrar el secuestro de la sesión de un usuario o el uso de un token de sesión antiguo para obtener acceso no autorizado.",
        Impact = "Acceso no autorizado a cuentas de usuario y datos sensibles.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar prácticas seguras de gestión de sesiones, incluyendo la creación, expiración e invalidación adecuada de sesiones.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1539",
        MitreTechniques = "T1539 - Steal Web Session Cookie",
    };
    
    public static Vuln Idor => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Referencia Directa Insegura a Objetos (IDOR)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación expone una referencia directa a objetos de implementación interna, como archivos, directorios, registros de base de datos o claves, sin ningún control de acceso o validación.",
        ProofOfConcept = "Demostrar el acceso o modificación de recursos pertenecientes a otros usuarios manipulando referencias a objetos en las solicitudes.",
        Impact = "Acceso no autorizado a datos sensibles, posible robo de datos o manipulación de información de otros usuarios.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar controles de acceso adecuados y usar referencias indirectas a objetos que se mapeen a datos específicos del usuario en el lado del servidor.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1213",
        MitreTechniques = "T1213 - Data from Information Repositories",
    };

    public static Vuln CrossSiteScripting => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Secuencias de Comandos en Sitios Cruzados (XSS)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no valida o codifica adecuadamente la entrada del usuario antes de renderizarla en una página web, permitiendo a los atacantes inyectar y ejecutar scripts maliciosos en el contexto de los navegadores de otros usuarios.",
        ProofOfConcept = "Demostrar la inyección de un script que se ejecuta en el navegador de la víctima, como mostrar un cuadro de alerta o robar cookies de sesión.",
        Impact = "Posible robo de sesiones de usuario, desfiguración de sitios web, redirección de usuarios a sitios maliciosos o ejecución de código arbitrario en el navegador del usuario.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar una validación de entrada adecuada, codificación de salida y usar encabezados de Política de Seguridad de Contenido (CSP) para mitigar los riesgos de XSS.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1189",
        MitreTechniques = "T1189 - Drive-by Compromise",
    };

    public static Vuln InsecureCryptographicStorage => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Almacenamiento Criptográfico Inseguro",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación almacena datos sensibles utilizando algoritmos criptográficos débiles o desactualizados, o implementa incorrectamente funciones criptográficas.",
        ProofOfConcept = "Demostrar la capacidad de descifrar datos sensibles utilizando debilidades conocidas en la implementación criptográfica.",
        Impact = "Acceso no autorizado a datos sensibles, potencialmente llevando a robo de identidad, fraude financiero u otras actividades maliciosas.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Utilizar algoritmos criptográficos fuertes y estándar de la industria e implementarlos correctamente. Asegurar prácticas adecuadas de gestión de claves.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1552",
        MitreTechniques = "T1552 - Unsecured Credentials",
    };

    public static Vuln InsecureDeserialization => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Deserialización Insegura",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación deserializa datos no confiables sin suficiente verificación, potencialmente permitiendo a los atacantes ejecutar código arbitrario o manipular la lógica de la aplicación.",
        ProofOfConcept = "Crear un objeto serializado malicioso que, al ser deserializado, ejecute comandos no autorizados o altere el comportamiento de la aplicación.",
        Impact = "Ejecución remota de código, manipulación de datos o denegación de servicio.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar verificaciones de tipo estrictas, usar prácticas de deserialización seguras y evitar deserializar datos no confiables cuando sea posible.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1203",
        MitreTechniques = "T1203 - Exploitation for Client Execution",
    };

    public static Vuln SqlInjection => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Inyección SQL",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Critical,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación construye consultas SQL utilizando entrada proporcionada por el usuario sin la sanitización o parametrización adecuada, permitiendo a los atacantes modificar o ejecutar comandos SQL arbitrarios.",
        ProofOfConcept = "Demostrar la capacidad de recuperar datos no autorizados o ejecutar comandos en la base de datos mediante la inyección de SQL malicioso.",
        Impact = "Acceso no autorizado a datos sensibles, manipulación de datos y potencial compromiso completo de la base de datos y sistemas conectados.",
        CVSS3 = 9.8,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Utilizar consultas parametrizadas o declaraciones preparadas, implementar una validación de entrada adecuada y aplicar el principio de menor privilegio para las cuentas de base de datos.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
    
    public static Vuln BrokenAccessControl => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Control de Acceso Roto",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación falla en hacer cumplir adecuadamente los controles de acceso, permitiendo a los usuarios realizar acciones o acceder a recursos para los que no deberían tener permisos.",
        ProofOfConcept = "Demostrar el acceso a funcionalidades o datos no autorizados manipulando parámetros de solicitud o utilizando una cuenta con privilegios menores.",
        Impact = "Acceso no autorizado a datos o funcionalidades sensibles, posible robo de datos o manipulación de información de otros usuarios.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar y hacer cumplir controles de acceso adecuados tanto a nivel de aplicación como de API. Utilizar control de acceso basado en roles (RBAC) y el principio de menor privilegio.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1548",
        MitreTechniques = "T1548 - Abuse Elevation Control Mechanism",
    };
    
    public static Vuln SecurityMisconfiguration => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Configuración Incorrecta de Seguridad",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación, el marco de trabajo, el servidor web o la plataforma están configurados de manera insegura, potencialmente exponiendo información sensible o permitiendo acceso no autorizado.",
        ProofOfConcept = "Identificar y explotar configuraciones predeterminadas, servicios abiertos innecesarios o información del sistema expuesta.",
        Impact = "Acceso no autorizado a funciones o datos de la aplicación, compromiso del sistema o divulgación de información.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        Remediation = "Implementar prácticas de configuración segura, deshabilitar características innecesarias, usar encabezados de seguridad y actualizar y parchear regularmente todos los componentes.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1082",
        MitreTechniques = "T1082 - System Information Discovery",
    };

    public static Vuln SensitiveDataExposure => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Exposición de Datos Sensibles",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no protege adecuadamente la información sensible, como datos financieros, información de salud o información personal identificable (PII).",
        ProofOfConcept = "Interceptar transmisiones de datos no cifrados o acceder a almacenamiento de datos sensibles inadecuadamente asegurado.",
        Impact = "Exposición de datos sensibles de usuarios, potencial de robo de identidad, fraude financiero o violación de regulaciones de protección de datos.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        Remediation = "Cifrar datos sensibles en tránsito y en reposo, implementar una gestión adecuada de claves y minimizar la exposición de datos sensibles en registros y mensajes de error.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1005",
        MitreTechniques = "T1005 - Data from Local System",
    };

    public static Vuln InsufficientLoggingAndMonitoring => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Registro y Monitoreo Insuficientes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no genera registros adecuados para eventos de seguridad, o falla en monitorear y responder a incidentes de seguridad de manera oportuna.",
        ProofOfConcept = "Realizar actividades sospechosas sin detección, o demostrar la falta de pistas de auditoría adecuadas para operaciones críticas.",
        Impact = "Detección retrasada o perdida de actividades maliciosas, capacidades de respuesta a incidentes y forenses obstaculizadas.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar registro completo para eventos relevantes de seguridad, asegurar el almacenamiento y protección adecuados de los registros, y establecer mecanismos efectivos de monitoreo y alerta.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1562",
        MitreTechniques = "T1562 - Impair Defenses",
    };

    public static Vuln UsingComponentsWithKnownVulnerabilities => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Uso de Componentes con Vulnerabilidades Conocidas",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza componentes, bibliotecas o marcos de trabajo de terceros con vulnerabilidades de seguridad conocidas.",
        ProofOfConcept = "Identificar componentes desactualizados y demostrar la explotación de vulnerabilidades conocidas en estos componentes.",
        Impact = "Potencial para varios tipos de ataques dependiendo de la vulnerabilidad, incluyendo robo de datos, ejecución remota de código o compromiso de la aplicación.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Actualizar y parchar regularmente todos los componentes, implementar una herramienta de análisis de composición de software y mantener un inventario de todos los componentes utilizados y sus versiones.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln ServerSideRequestForgery => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falsificación de Solicitudes del Lado del Servidor (SSRF)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación procesa URLs o rutas de archivo proporcionadas por el usuario para recuperar recursos, permitiendo a un atacante manipular solicitudes para acceder a recursos internos o realizar acciones no autorizadas.",
        ProofOfConcept = "Demostrar la capacidad de hacer que el servidor solicite recursos internos o sitios externos controlados por el atacante.",
        Impact = "Posible acceso a sistemas internos, exfiltración de datos o ejecución remota de código en algunos casos.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:H",
        Remediation = "Implementar una validación de entrada estricta, usar listas blancas para URLs o dominios permitidos, deshabilitar esquemas de URL innecesarios y usar un servidor separado para realizar solicitudes externas.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

     public static Vuln XmlExternalEntityProcessing => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Procesamiento de Entidades Externas XML (XXE)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación procesa entrada XML que incluye referencias a entidades externas sin la validación adecuada, permitiendo a los atacantes revelar archivos internos, realizar falsificación de solicitudes del lado del servidor o ejecutar ataques de denegación de servicio.",
        ProofOfConcept = "Demostrar la capacidad de leer archivos internos o hacer que el servidor se conecte a hosts arbitrarios usando entrada XML que contiene entidades externas maliciosas.",
        Impact = "Posible divulgación de datos sensibles, falsificación de solicitudes del lado del servidor o denegación de servicio.",
        CVSS3 = 8.2,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:H",
        Remediation = "Deshabilitar el procesamiento de entidades externas XML y DTD en todos los analizadores XML de la aplicación, usar formatos de datos menos complejos como JSON cuando sea posible, y validar y sanear toda la entrada XML.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln LackOfRateLimiting => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falta de Limitación de Tasa",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no implementa mecanismos adecuados de limitación de tasa, permitiendo a los atacantes realizar un número excesivo de solicitudes u operaciones.",
        ProofOfConcept = "Demostrar la capacidad de realizar un gran número de solicitudes en un corto período de tiempo sin ninguna restricción.",
        Impact = "Potencial para denegación de servicio, ataques de fuerza bruta o consumo excesivo de recursos.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
        Remediation = "Implementar limitación de tasa en todos los puntos finales de la API y funciones críticas. Utilizar técnicas como algoritmos de cubo de tokens o contadores de ventana fija para restringir el número de solicitudes que un usuario puede hacer en un período de tiempo determinado.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1499",
        MitreTechniques = "T1499 - Endpoint Denial of Service\n",
    };
    
    public static Vuln InadequateOAuth2Implementation => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Implementación Inadecuada de OAuth 2.0",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La implementación de OAuth 2.0 de la aplicación contiene fallas de seguridad, como validación incorrecta de URIs de redirección, almacenamiento inseguro de tokens o manejo incorrecto de parámetros de estado.",
        ProofOfConcept = "Demostrar la capacidad de realizar robo de tokens, toma de control de cuentas o acceso no autorizado a través de fallas en la implementación de OAuth.",
        Impact = "Potencial de acceso no autorizado a cuentas de usuario, robo de datos o suplantación de usuarios.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
        Remediation = "Implementar OAuth 2.0 de forma segura siguiendo las mejores prácticas: validar todas las URIs de redirección, usar parámetros de estado para prevenir CSRF, almacenar y transmitir tokens de forma segura, e implementar una validación y expiración adecuada de tokens.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1550",
        MitreTechniques = "T1550 - Use Alternate Authentication Material",
    };
    
    public static Vuln InsufficientAntiAutomation => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Anti-Automatización Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación carece de medidas suficientes para prevenir ataques automatizados, como relleno de credenciales, intentos de fuerza bruta o raspado de contenido.",
        ProofOfConcept = "Demostrar la capacidad de realizar solicitudes automatizadas de alto volumen sin activar ningún mecanismo defensivo.",
        Impact = "Potencial de toma de control de cuentas, recolección de datos o degradación del servicio a través de ataques automatizados.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar medidas anti-automatización como CAPTCHA, limitación de tasa, restricciones basadas en IP y análisis de comportamiento para detectar y prevenir ataques automatizados.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1110",
        MitreTechniques = "T1110 - Brute Force",
    };
    
    public static Vuln WeakCryptographicAlgorithms => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Algoritmos Criptográficos Débiles",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza algoritmos criptográficos débiles o desactualizados que son susceptibles a ataques.",
        ProofOfConcept = "Identificar el uso de algoritmos débiles (por ejemplo, MD5, SHA1, DES) en las operaciones criptográficas de la aplicación.",
        Impact = "Potencial de descifrado de datos sensibles, compromiso de la integridad de datos firmados o ruptura de canales de comunicación seguros.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Reemplazar algoritmos débiles con algoritmos criptográficos fuertes y modernos (por ejemplo, AES, SHA-256, RSA con tamaños de clave apropiados) y seguir las mejores prácticas para su implementación.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1557",
        MitreTechniques = "T1557 - Adversary-in-the-Middle",
    };

    public static Vuln ImproperCertificateValidation => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Validación Incorrecta de Certificados",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no valida adecuadamente los certificados SSL/TLS, potencialmente permitiendo ataques de hombre en el medio o conexiones a servidores maliciosos.",
        ProofOfConcept = "Demostrar la capacidad de interceptar tráfico SSL/TLS usando un certificado autofirmado o inválido sin que la aplicación lo detecte.",
        Impact = "Potencial de escucha de comunicaciones sensibles, robo de datos o inyección de contenido malicioso.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar una validación adecuada de certificados, incluyendo la verificación de caducidad, revocación y coincidencia de nombres de host. Usar fijación de certificados para aplicaciones de alta seguridad.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1557",
        MitreTechniques = "T1557 - Adversary-in-the-Middle",
    };

    public static Vuln CrossSiteRequestForgery => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falsificación de Petición en Sitios Cruzados (CSRF)",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no implementa protecciones CSRF adecuadas, permitiendo a los atacantes engañar a los usuarios para que realicen acciones no intencionadas en la aplicación autenticada.",
        ProofOfConcept = "Crear una página web maliciosa que, cuando es visitada por un usuario autenticado, realiza una acción no autorizada en la aplicación vulnerable.",
        Impact = "Potencial de acciones no autorizadas realizadas en nombre de usuarios autenticados, como cambios en la configuración de la cuenta o transferencias no autorizadas.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        Remediation = "Implementar tokens anti-CSRF para todas las operaciones que cambian el estado, usar el atributo SameSite para las cookies y considerar la implementación de defensas adicionales como encabezados de solicitud personalizados.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1204",
        MitreTechniques = "T1204 - User Execution",
    };

    public static Vuln InsufficientPasswordRecoveryMechanism => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Mecanismo de Recuperación de Contraseña Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "El mecanismo de recuperación de contraseña de la aplicación es débil o puede ser fácilmente eludido, potencialmente permitiendo a los atacantes tomar el control de las cuentas de usuario.",
        ProofOfConcept = "Demostrar la capacidad de restablecer la contraseña de un usuario sin la autenticación adecuada o eludiendo medidas de seguridad.",
        Impact = "Potencial de acceso no autorizado a cuentas de usuario, conduciendo a robo de datos o abuso de cuentas.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar un proceso seguro de recuperación de contraseña utilizando tokens de recuperación de uso único y tiempo limitado enviados a través de canales fuera de banda. Evitar el uso de preguntas de seguridad como único método de recuperación.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1552",
        MitreTechniques = "T1552 - Unsecured Credentials",
    };

    public static Vuln LackOfInputSanitization => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falta de Saneamiento de Entrada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no sanea o valida adecuadamente la entrada del usuario, potencialmente permitiendo varios ataques de inyección u otras entradas maliciosas.",
        ProofOfConcept = "Demostrar la capacidad de inyectar cargas útiles maliciosas (por ejemplo, inyección SQL, XSS) a través de campos de entrada de usuario.",
        Impact = "Potencial de manipulación de datos, acceso no autorizado a datos o ejecución de scripts maliciosos, dependiendo del contexto de la entrada no saneada.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        Remediation = "Implementar una validación y saneamiento de entrada adecuados para todas las entradas de usuario. Usar consultas parametrizadas para operaciones de base de datos, codificar la salida para prevención de XSS y validar las entradas contra una lista blanca de caracteres y formatos permitidos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
    
    public static Vuln InsufficientSessionTimeout => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Tiempo de Espera de Sesión Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no implementa mecanismos adecuados de tiempo de espera de sesión, permitiendo que las sesiones permanezcan activas durante períodos prolongados de tiempo.",
        ProofOfConcept = "Demostrar que la sesión de un usuario permanece activa incluso después de largos períodos de inactividad o después de cerrar el navegador.",
        Impact = "Mayor riesgo de secuestro de sesión, especialmente en computadoras compartidas o en caso de robo de token de sesión.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
        Remediation = "Implementar mecanismos adecuados de tiempo de espera de sesión. Establecer tiempos de expiración razonables para las sesiones y asegurar que las sesiones se invaliden después del cierre de sesión del usuario o períodos prolongados de inactividad.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln ImproperErrorHandling => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Manejo Inadecuado de Errores",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación revela información sensible a través de mensajes de error detallados o trazas de pila, potencialmente ayudando a los atacantes a entender la estructura y vulnerabilidades de la aplicación.",
        ProofOfConcept = "Provocar errores en la aplicación que revelen información sensible como estructura de la base de datos, rutas de archivos o direcciones IP internas.",
        Impact = "Divulgación de información que podría ayudar a los atacantes a explotar aún más la aplicación o los sistemas subyacentes.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        Remediation = "Implementar un manejo de errores adecuado que muestre mensajes de error genéricos a los usuarios mientras se registra información detallada de errores de forma segura para los desarrolladores. Asegurar que los modos de depuración estén desactivados en entornos de producción.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1082",
        MitreTechniques = "T1082 - System Information Discovery",
    };

    public static Vuln MissingSecurityHeaders => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Encabezados de Seguridad Faltantes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no implementa encabezados de seguridad importantes que pueden ayudar a proteger contra varios ataques como XSS, clickjacking y ataques de hombre en el medio.",
        ProofOfConcept = "Analizar los encabezados de respuesta HTTP y demostrar la ausencia de encabezados de seguridad importantes como Content-Security-Policy, X-Frame-Options o Strict-Transport-Security.",
        Impact = "Mayor vulnerabilidad a varios ataques que podrían haberse mitigado con encabezados de seguridad adecuados.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar encabezados de seguridad apropiados incluyendo Content-Security-Policy, X-Frame-Options, Strict-Transport-Security, X-Content-Type-Options y Referrer-Policy. Configurar estos encabezados correctamente basándose en los requisitos de la aplicación.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln InsecureUseOfCryptography => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Uso Inseguro de Criptografía",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza funciones criptográficas de manera insegura, como usar tamaños de clave débiles, gestión inadecuada de claves o implementación incorrecta de protocolos criptográficos.",
        ProofOfConcept = "Identificar instancias de prácticas criptográficas inseguras, como claves de cifrado codificadas, uso del modo ECB para cifrado simétrico o validación inadecuada de certificados.",
        Impact = "Posible compromiso de datos cifrados, ruptura de la confidencialidad o integridad de las comunicaciones, o elusión de mecanismos de seguridad que dependen de la criptografía.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Usar bibliotecas criptográficas bien probadas, asegurar una gestión adecuada de claves (generación, almacenamiento y rotación), usar tamaños de clave y modos de operación apropiados, y seguir las mejores prácticas para los protocolos criptográficos elegidos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1552",
        MitreTechniques = "T1552 - Unsecured Credentials",
    };

    public static Vuln BrokenFunctionLevelAuthorization => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Autorización a Nivel de Función Rota",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no restringe adecuadamente el acceso a ciertas funciones basándose en los roles de usuario, permitiendo a los usuarios realizar acciones para las que no deberían estar autorizados.",
        ProofOfConcept = "Demostrar el acceso a funciones administrativas o la realización de acciones privilegiadas utilizando una cuenta de usuario con privilegios bajos.",
        Impact = "Acceso no autorizado a funcionalidad sensible, potencial de robo de datos, manipulación o compromiso del sistema.",
        CVSS3 = 8.8,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar controles de acceso adecuados a nivel de función. Hacer cumplir las verificaciones de autorización de manera consistente en todas las funciones de la aplicación. Usar control de acceso basado en roles (RBAC) y aplicar el principio de mínimo privilegio.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1548",
        MitreTechniques = "T1548 - Abuse Elevation Control Mechanism",
    };
    
    public static Vuln InsecureCommunicationChannels => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Canales de Comunicación Inseguros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza protocolos inseguros o cifrado débil para la transmisión de datos, potencialmente exponiendo información sensible a intercepción o manipulación.",
        ProofOfConcept = "Demostrar la capacidad de interceptar y leer datos sensibles en tránsito, o mostrar el uso de protocolos obsoletos como SSLv3 o TLS 1.0.",
        Impact = "Posible exposición de datos sensibles, incluyendo credenciales, información personal o datos críticos del negocio a partes no autorizadas.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar protocolos de comunicación seguros (TLS 1.2 o superior) para todas las transmisiones de datos. Asegurar la configuración adecuada de algoritmos de cifrado y tamaños de clave. Usar fijación de certificados para aplicaciones móviles.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1040",
        MitreTechniques = "T1040 - Network Sniffing",
    };

    public static Vuln LackOfSecureDefaults => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falta de Configuraciones Seguras por Defecto",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación o sus componentes se despliegan con configuraciones predeterminadas inseguras, exponiendo potencialmente el sistema a riesgos innecesarios.",
        ProofOfConcept = "Identificar cuentas predeterminadas con contraseñas débiles, servicios innecesarios habilitados por defecto o permisos predeterminados excesivamente permisivos.",
        Impact = "Mayor superficie de ataque y potencial de explotación de características o servicios innecesarios.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar un enfoque de 'seguro por defecto'. Deshabilitar características y servicios innecesarios, eliminar cuentas predeterminadas o cambiar sus credenciales, y aplicar principios de mínimo privilegio a las configuraciones predeterminadas.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln InsufficientProtectionFromAutomatedThreats => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Protección Insuficiente contra Amenazas Automatizadas",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación carece de defensas adecuadas contra ataques automatizados como relleno de credenciales, intentos de fuerza bruta o raspado de contenido.",
        ProofOfConcept = "Demostrar la capacidad de realizar un alto volumen de solicitudes (por ejemplo, intentos de inicio de sesión o recuperación de datos) sin activar ningún mecanismo defensivo.",
        Impact = "Mayor riesgo de toma de control de cuentas, recolección de datos o degradación del servicio debido a ataques automatizados.",
        CVSS3 = 6.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar limitación de tasa, desafíos CAPTCHA, bloqueos de cuentas y restricciones basadas en IP. Utilizar análisis de comportamiento para detectar y prevenir ataques automatizados. Considerar el uso de firewalls de aplicaciones web (WAF) para protección adicional.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1110",
        MitreTechniques = "T1110 - Brute Force",
    };
    
    public static Vuln UnvalidatedRedirectsAndForwards => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Redirecciones y Reenvíos no Validados",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación redirige o reenvía a los usuarios a sitios web potencialmente maliciosos sin una validación adecuada de la URL de destino.",
        ProofOfConcept = "Demostrar la capacidad de manipular parámetros de redirección para enviar usuarios a sitios web externos arbitrarios.",
        Impact = "Potencial para ataques de phishing, distribución de malware o ingeniería social al redirigir usuarios a sitios maliciosos.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar una validación estricta de todos los destinos de redirección. Utilizar una lista blanca de destinos permitidos o validar contra un patrón de URLs conocidas como seguras. Evitar el uso de entrada proporcionada por el usuario directamente en funciones de redirección.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1566",
        MitreTechniques = "T1566 - Phishing",
    };

    public static Vuln InsecureAuthenticationMechanism => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Mecanismo de Autenticación Inseguro",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza mecanismos de autenticación débiles o fácilmente eludibles, permitiendo potencialmente el acceso no autorizado a cuentas de usuario.",
        ProofOfConcept = "Demostrar la elusión de controles de autenticación o la explotación de debilidades en el proceso de autenticación.",
        Impact = "Acceso no autorizado a cuentas de usuario, potencial de robo de identidad, filtración de datos o compromiso del sistema.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar mecanismos de autenticación fuertes y multifactor. Utilizar gestión segura de sesiones, hacer cumplir políticas de contraseñas y considerar el uso de proveedores de identidad federados para una seguridad mejorada.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1078",
        MitreTechniques = "T1078 - Valid Accounts",
    };

    public static Vuln InsufficientAntiCachingHeaders => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Encabezados Anti-Caché Insuficientes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no establece encabezados de control de caché adecuados, permitiendo potencialmente que información sensible se almacene en cachés de navegadores o proxies intermedios.",
        ProofOfConcept = "Demostrar la capacidad de recuperar información sensible de la caché del navegador o mostrar que las páginas sensibles son almacenadas en caché por proxies.",
        Impact = "Potencial exposición de datos sensibles a partes no autorizadas, especialmente en computadoras compartidas o a través de ataques de hombre en el medio.",
        CVSS3 = 5.3,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        Remediation = "Implementar encabezados de control de caché adecuados (por ejemplo, Cache-Control: no-store, no-cache, must-revalidate) para páginas que contienen información sensible. Utilizar HTTPS para prevenir el almacenamiento en caché por proxies intermedios.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1557",
        MitreTechniques = "T1557 - Adversary-in-the-Middle",
    };
    
    public static Vuln LackOfProperTLSConfiguration => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falta de Configuración Adecuada de TLS",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza configuraciones TLS débiles u obsoletas, exponiendo potencialmente las comunicaciones a intercepción o manipulación.",
        ProofOfConcept = "Demostrar el uso de suites de cifrado débiles, versiones TLS obsoletas o validación de certificados mal configurada.",
        Impact = "Potencial para ataques de hombre en el medio, intercepción de datos o degradación de las comunicaciones cifradas.",
        CVSS3 = 7.4,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Configurar TLS para usar solo suites de cifrado fuertes, deshabilitar versiones TLS antiguas (1.0, 1.1), asegurar la validación adecuada de certificados e implementar HSTS. Revisar y actualizar regularmente las configuraciones TLS.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1573",
        MitreTechniques = "T1573 - Encrypted Channel",
    };

    public static Vuln InsufficientDataProtection => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Protección Insuficiente de Datos en Tránsito y en Reposo",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no protege adecuadamente los datos sensibles durante la transmisión o el almacenamiento, exponiéndolos potencialmente a acceso o manipulación no autorizados.",
        ProofOfConcept = "Demostrar la capacidad de interceptar datos no cifrados en tránsito o acceder a datos sensibles almacenados de manera insegura.",
        Impact = "Posible exposición de datos sensibles de usuarios, violaciones de cumplimiento y mayor riesgo de filtración de datos.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        Remediation = "Implementar cifrado fuerte para datos en tránsito (por ejemplo, TLS) y en reposo (por ejemplo, cifrado a nivel de archivo o base de datos). Utilizar prácticas seguras de gestión de claves y asegurar que todos los datos sensibles estén identificados y protegidos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1040,T1029",
        MitreTechniques = "T1040 - Network Sniffing, T1029 - Scheduled Transfer",
    };
    
    public static Vuln ImproperAssetManagement => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Gestión Inadecuada de Activos",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La organización carece de un inventario y gestión adecuados de sus activos de TI, lo que potencialmente conduce a sistemas sin parches, servidores olvidados o dispositivos no autorizados en la red.",
        ProofOfConcept = "Identificar sistemas no gestionados u olvidados, versiones de software obsoletas o dispositivos no autorizados conectados a la red.",
        Impact = "Mayor superficie de ataque, potencial de compromisos no detectados y dificultad para mantener una postura de seguridad general.",
        CVSS3 = 5.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        Remediation = "Implementar un sistema integral de gestión de activos. Inventariar y actualizar regularmente todos los activos de TI, incluyendo hardware, software y recursos en la nube. Establecer procesos para la gestión del ciclo de vida de los activos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1046",
        MitreTechniques = "T1046 - Network Service Discovery",
    };

    public static Vuln LackOfSoftwareUpdates => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falta de Actualizaciones de Software/Gestión de Parches",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación o sus sistemas subyacentes no se actualizan regularmente, dejando potencialmente vulnerabilidades conocidas sin parchear.",
        ProofOfConcept = "Identificar versiones de software obsoletas con vulnerabilidades conocidas que podrían ser explotadas.",
        Impact = "Mayor riesgo de explotación de vulnerabilidades conocidas, potencialmente llevando a compromiso del sistema, filtraciones de datos o interrupciones del servicio.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar un proceso robusto de gestión de parches. Actualizar regularmente todos los componentes de software, incluyendo la aplicación, bibliotecas, marcos de trabajo y sistemas operativos. Automatizar el proceso de parcheo cuando sea posible.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln InsufficientPrivacyControls => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Controles de Privacidad Insuficientes",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación carece de controles adecuados para proteger la privacidad del usuario, potencialmente violando las regulaciones de protección de datos o las expectativas del usuario.",
        ProofOfConcept = "Demostrar la recopilación, procesamiento o compartición de datos personales sin el consentimiento adecuado o más allá de los propósitos declarados.",
        Impact = "Posibles violaciones legales y regulatorias, pérdida de confianza del usuario y posibles sanciones financieras.",
        CVSS3 = 5.9,
        CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
        Remediation = "Implementar principios de privacidad por diseño. Realizar evaluaciones de impacto en la privacidad, obtener el consentimiento adecuado del usuario para la recopilación y procesamiento de datos, y proporcionar políticas de privacidad claras. Implementar principios de minimización de datos y limitación de propósito.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1005",
        MitreTechniques = "T1005 - Data from Local System",
    };

    public static Vuln InsecureAPIEndpoints => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Puntos Finales de API Inseguros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "Los puntos finales de la API de la aplicación carecen de controles de seguridad adecuados, permitiendo potencialmente el acceso no autorizado, la manipulación de datos o la divulgación de información.",
        ProofOfConcept = "Demostrar acceso no autorizado a puntos finales de la API, manipulación de datos o extracción de información sensible a través de llamadas a la API.",
        Impact = "Potencial de filtraciones de datos, acciones no autorizadas o compromiso del sistema a través de la explotación de la API.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar autenticación y autorización fuertes para todos los puntos finales de la API. Utilizar claves de API, tokens OAuth u otros métodos seguros. Validar y sanear todas las entradas de la API, implementar limitación de tasa y usar HTTPS para todas las comunicaciones de la API.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
    
    public static Vuln InsufficientInputValidation => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Validación de Entrada Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no valida adecuadamente la entrada del usuario, permitiendo potencialmente ataques de inyección, desbordamientos de buffer u otras entradas maliciosas.",
        ProofOfConcept = "Demostrar la capacidad de ingresar datos maliciosos que son procesados por la aplicación sin una validación o sanitización adecuada.",
        Impact = "Potencial para varios ataques incluyendo inyección SQL, XSS, inyección de comandos o bloqueos de la aplicación.",
        CVSS3 = 8.6,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar una validación estricta de entrada para todos los datos proporcionados por el usuario. Usar listas blancas, sanitización de entrada y consultas parametrizadas. Validar la entrada por tipo, longitud, formato y rango según corresponda.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln ImproperOutputEncoding => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Codificación de Salida Inadecuada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no codifica adecuadamente la salida antes de renderizarla a los usuarios, permitiendo potencialmente ataques de inyección como Cross-Site Scripting (XSS).",
        ProofOfConcept = "Demostrar la capacidad de inyectar y ejecutar scripts o HTML maliciosos en la salida de la aplicación.",
        Impact = "Potencial para ataques del lado del cliente, robo de datos, secuestro de sesiones o desfiguración de la aplicación.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar codificación de salida contextual para todo el contenido dinámico. Usar funciones de codificación apropiadas para contextos HTML, JavaScript, CSS y URL. Considerar el uso de motores de plantillas con escape automático.",
        RemediationComplexity = RemediationComplexity.Medium,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1189",
        MitreTechniques = "T1189 - Drive-by Compromise",
    };

    public static Vuln InsecureFileHandling => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Manejo Inseguro de Archivos",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no valida o maneja adecuadamente las operaciones de archivo, permitiendo potencialmente acceso no autorizado, inclusión de archivos o ejecución de archivos maliciosos.",
        ProofOfConcept = "Demostrar la capacidad de acceder a archivos fuera de los directorios previstos, subir archivos maliciosos o ejecutar archivos arbitrarios en el servidor.",
        Impact = "Potencial de acceso no autorizado a archivos sensibles, ejecución remota de código o compromiso del servidor.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar una validación estricta de entrada para nombres y rutas de archivo. Usar listas blancas para tipos y extensiones de archivo permitidos. Almacenar los archivos subidos por el usuario fuera de la raíz web y utilizar bibliotecas seguras de manejo de archivos.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln LackOfSecurePasswordStorage => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Falta de Almacenamiento Seguro de Contraseñas",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Critical,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación no almacena de forma segura las contraseñas de los usuarios, exponiéndolas potencialmente a acceso no autorizado o haciéndolas vulnerables a intentos de descifrado.",
        ProofOfConcept = "Demostrar que las contraseñas se almacenan en texto plano, usando algoritmos de hash débiles o sin un salado adecuado.",
        Impact = "Potencial de acceso no autorizado a cuentas de usuario, compromiso masivo de cuentas en caso de filtración de datos.",
        CVSS3 = 9.8,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Utilizar algoritmos de hash adaptativos fuertes (por ejemplo, bcrypt, Argon2) para el almacenamiento de contraseñas. Implementar salado adecuado y asegurar factores de trabajo suficientes. Nunca almacenar contraseñas en texto plano o usando cifrado reversible.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };

    public static Vuln InsufficientProtectionAgainstDoS => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Protección Insuficiente Contra Denegación de Servicio",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación carece de medidas adecuadas para protegerse contra ataques de Denegación de Servicio (DoS), permitiendo potencialmente a los atacantes saturar los recursos del sistema y interrumpir la disponibilidad del servicio.",
        ProofOfConcept = "Demostrar la capacidad de consumir recursos excesivos o desencadenar operaciones intensivas en recursos sin limitaciones adecuadas.",
        Impact = "Potencial de interrupción del servicio, degradación del rendimiento o indisponibilidad completa del sistema.",
        CVSS3 = 7.5,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        Remediation = "Implementar limitación de tasa, regulación de solicitudes y cuotas de recursos. Usar algoritmos eficientes y caché donde sea apropiado. Considerar la implementación de CAPTCHAs para operaciones sensibles y desplegar soluciones de mitigación de DoS a nivel de red.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1498",
        MitreTechniques = "T1498 - Network Denial of Service",
    };
    
    public static Vuln InsufficientSubresourceIntegrity => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Integridad de Subrecursos Insuficiente",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.Medium,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación carga recursos externos (como scripts o hojas de estilo) sin comprobaciones de integridad adecuadas, permitiendo potencialmente a los atacantes inyectar contenido malicioso a través de recursos de terceros comprometidos.",
        ProofOfConcept = "Demostrar que la aplicación carga recursos externos sin comprobaciones de Integridad de Subrecursos (SRI), haciéndola vulnerable a ataques de cadena de suministro.",
        Impact = "Potencial de ejecución de scripts no autorizados, llevando a robo de datos, desfiguración u otros ataques del lado del cliente.",
        CVSS3 = 6.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        Remediation = "Implementar Integridad de Subrecursos (SRI) para todos los recursos cargados externamente. Usar atributos de integridad con hashes criptográficos para garantizar la integridad de los recursos cargados.",
        RemediationComplexity = RemediationComplexity.Low,
        RemediationPriority = RemediationPriority.Medium,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1195",
        MitreTechniques = "T1195 - Supply Chain Compromise",
    };
    
    public static Vuln InadequateSecurityArchitecture => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Arquitectura de Seguridad Inadecuada",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La arquitectura de seguridad de la aplicación es insuficiente, careciendo de controles de seguridad adecuados, patrones de diseño seguro o un enfoque de defensa en profundidad.",
        ProofOfConcept = "Demostrar fallos arquitectónicos que permiten eludir múltiples capas de seguridad o explotar debilidades sistémicas en el diseño de la aplicación.",
        Impact = "Mayor vulnerabilidad a varios ataques debido a debilidades sistémicas, potencialmente llevando a compromisos o filtraciones de datos a gran escala.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar una arquitectura de seguridad robusta siguiendo principios como defensa en profundidad, mínimo privilegio y seguridad por diseño. Realizar revisiones regulares de la arquitectura y asegurar la alineación con las mejores prácticas de seguridad.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };

    public static Vuln FlawedBusinessLogic => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Lógica de Negocio Defectuosa",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación contiene fallas en la implementación de su lógica de negocio, permitiendo a los usuarios realizar acciones que violan el proceso de negocio previsto o las suposiciones de seguridad.",
        ProofOfConcept = "Demostrar la capacidad de manipular los procesos de negocio de la aplicación, como eludir pagos, alterar cantidades de pedidos o acceder a descuentos no autorizados.",
        Impact = "Potencial de pérdidas financieras, acceso no autorizado a servicios o manipulación de procesos de negocio críticos.",
        CVSS3 = 7.7,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N",
        Remediation = "Implementar una validación exhaustiva de la lógica de negocio. Asegurar que todos los procesos de negocio estén correctamente modelados y aplicados en la aplicación. Realizar revisiones por pares de la implementación de la lógica de negocio y realizar pruebas exhaustivas de escenarios de negocio.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "",
        MitreTechniques = "",
    };
    
    public static Vuln InsecureThirdPartyComponents => new Vuln
    {
        Template = true,
        Language = Language.Español,
        Name = "Componentes de Terceros Inseguros",
        CreatedDate = DateTime.UtcNow,
        ModifiedDate = DateTime.UtcNow,
        Risk = VulnRisk.High,
        Status = VulnStatus.Open,
        cve = "N/A",
        Description = "La aplicación utiliza componentes, bibliotecas o marcos de trabajo de terceros que están desactualizados, contienen vulnerabilidades conocidas o se obtienen de fuentes no confiables.",
        ProofOfConcept = "Identificar y demostrar la explotación de vulnerabilidades conocidas en componentes de terceros utilizados por la aplicación.",
        Impact = "Potencial para varios tipos de ataques dependiendo de las vulnerabilidades en los componentes, incluyendo robo de datos, ejecución remota de código o compromiso de la aplicación.",
        CVSS3 = 8.1,
        CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        Remediation = "Implementar una herramienta de análisis de composición de software (SCA) para rastrear y gestionar componentes de terceros. Actualizar regularmente los componentes a sus versiones seguras más recientes. Establecer un proceso para evaluar y aprobar código de terceros. Usar fuentes confiables para obtener componentes.",
        RemediationComplexity = RemediationComplexity.High,
        RemediationPriority = RemediationPriority.High,
        JiraCreated = false,
        OWASPRisk = "",
        OWASPImpact = "",
        OWASPLikehood = "",
        OWASPVector = "",
        MitreValues = "T1190",
        MitreTechniques = "T1190 - Exploit Public-Facing Application",
    };
}