/*using Cervantes.CORE.Entities;

namespace Cervantes.IFR.VulnTemplates;

public class VulnTemplatesWstgPT
{
    public static Vuln InsufficientAuthentication => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Autenticação Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não autentica adequadamente os usuários, permitindo acesso não autorizado a funcionalidades ou dados sensíveis.",
    ProofOfConcept = "Demonstrar acesso a áreas ou funções restritas sem autenticação adequada.",
    Impact = "Unauthorized access to sensitive data or functionality, potentially leading to data breaches or system compromise.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar mecanismos de autenticação forte, como autenticação de múltiplos fatores, para todas as áreas sensíveis da aplicação.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Privilege Escalation",
    MitreTechniques = "T1078",
    VulnCwes = new List<string> { "CWE-287", "CWE-306" },
};

public static Vuln WeakPasswordRequirements => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Requisitos de Senha Fracos",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação permite senhas fracas que não atendem aos requisitos mínimos de complexidade e comprimento.",
    ProofOfConcept = "Criar contas com senhas fracas que não atendem aos padrões da indústria.",
    Impact = "Increased risk of successful brute-force attacks and unauthorized account access.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    Remediation = "Implementar políticas de senha fortes, exigindo comprimento mínimo, complexidade e prevenindo senhas fracas comuns.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access",
    MitreTechniques = "T1110",
    VulnCwes = new List<string> { "CWE-521" },
};

public static Vuln InsecureSessionManagement => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Gerenciamento de Sessão Inseguro",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não gerencia adequadamente as sessões dos usuários, levando a vulnerabilidades como fixação de sessão ou expiração insuficiente de sessão.",
    ProofOfConcept = "Demonstrar o sequestro da sessão de um usuário ou usar um token de sessão antigo para obter acesso não autorizado.",
    Impact = "Unauthorized access to user accounts and sensitive data.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar práticas seguras de gerenciamento de sessão, incluindo criação, expiração e invalidação adequadas de sessões.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Lateral Movement",
    MitreTechniques = "T1539",
    VulnCwes = new List<string> { "CWE-384", "CWE-613" },
};

public static Vuln Idor => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Referência Direta Insegura a Objeto (IDOR)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação expõe uma referência direta a objetos de implementação interna, como arquivos, diretórios, registros de banco de dados ou chaves, sem qualquer controle de acesso ou validação.",
    ProofOfConcept = "Demonstrar o acesso ou modificação de recursos pertencentes a outros usuários manipulando referências de objetos em requisições.",
    Impact = "Unauthorized access to sensitive data, potential data theft, or manipulation of other users' information.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar controles de acesso adequados e usar referências indiretas a objetos que são mapeadas para dados específicos do usuário no lado do servidor.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Lateral Movement, Collection",
    MitreTechniques = "T1213",
    VulnCwes = new List<string> { "CWE-639" },
};

public static Vuln CrossSiteScripting => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Cross-Site Scripting (XSS)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não valida ou codifica adequadamente a entrada do usuário antes de renderizá-la em uma página web, permitindo que atacantes injetem e executem scripts maliciosos no contexto dos navegadores de outros usuários.",
    ProofOfConcept = "Demonstrar a injeção de um script que é executado no navegador da vítima, como exibir uma caixa de alerta ou roubar cookies de sessão.",
    Impact = "Potential theft of user sessions, defacement of websites, redirection of users to malicious sites, or execution of arbitrary code in the user's browser.",
    CVSS3 = 6.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    Remediation = "Implementar validação adequada de entrada, codificação de saída e usar cabeçalhos de Política de Segurança de Conteúdo (CSP) para mitigar riscos de XSS.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1189",
    VulnCwes = new List<string> { "CWE-79" },
};

public static Vuln InsecureCryptographicStorage => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Armazenamento Criptográfico Inseguro",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação armazena dados sensíveis usando algoritmos criptográficos fracos ou desatualizados, ou implementa funções criptográficas de maneira inadequada.",
    ProofOfConcept = "Demonstrar a capacidade de descriptografar dados sensíveis usando fraquezas conhecidas na implementação criptográfica.",
    Impact = "Unauthorized access to sensitive data, potentially leading to identity theft, financial fraud, or other malicious activities.",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Usar algoritmos criptográficos fortes e padrão da indústria e implementá-los corretamente. Garantir práticas adequadas de gerenciamento de chaves.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Exfiltration",
    MitreTechniques = "T1552",
    VulnCwes = new List<string> { "CWE-327", "CWE-328" },
};

public static Vuln InsecureDeserialization => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Desserialização Insegura",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação desserializa dados não confiáveis sem verificação suficiente, potencialmente permitindo que atacantes executem código arbitrário ou manipulem a lógica da aplicação.",
    ProofOfConcept = "Criar um objeto serializado malicioso que, quando desserializado, execute comandos não autorizados ou altere o comportamento da aplicação.",
    Impact = "Remote code execution, data manipulation, or denial of service.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar verificações estritas de tipo, usar práticas seguras de desserialização e evitar desserializar dados não confiáveis quando possível.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Execution, Defense Evasion",
    MitreTechniques = "T1203",
    VulnCwes = new List<string> { "CWE-502" },
};

public static Vuln SqlInjection => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Injeção SQL",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação constrói consultas SQL usando entrada fornecida pelo usuário sem sanitização ou parametrização adequada, permitindo que atacantes modifiquem ou executem comandos SQL arbitrários.",
    ProofOfConcept = "Demonstrar a capacidade de recuperar dados não autorizados ou executar comandos no banco de dados injetando SQL malicioso.",
    Impact = "Unauthorized access to sensitive data, data manipulation, and potential complete compromise of the database and connected systems.",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Usar consultas parametrizadas ou declarações preparadas, implementar validação adequada de entrada e aplicar o princípio do menor privilégio para contas de banco de dados.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Critical,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "3.0",
    MitreValues = "Initial Access, Execution, Exfiltration",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-89" },
};
public static Vuln BrokenAccessControl => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Controle de Acesso Quebrado",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação falha em impor adequadamente os controles de acesso, permitindo que os usuários realizem ações ou acessem recursos para os quais não deveriam ter permissão.",
    ProofOfConcept = "Demonstrar o acesso a funcionalidades ou dados não autorizados manipulando parâmetros de solicitação ou usando uma conta com privilégios inferiores.",
    Impact = "Unauthorized access to sensitive data or functionality, potential data theft, or manipulation of other users' information.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar e fazer cumprir controles de acesso adequados tanto no nível da aplicação quanto da API. Usar controle de acesso baseado em função (RBAC) e o princípio do menor privilégio.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Privilege Escalation, Lateral Movement",
    MitreTechniques = "T1548",
    VulnCwes = new List<string> { "CWE-284", "CWE-285", "CWE-639" },
};

public static Vuln SecurityMisconfiguration => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Configuração Incorreta de Segurança",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação, framework, servidor web ou plataforma está configurada de forma insegura, potencialmente expondo informações sensíveis ou permitindo acesso não autorizado.",
    ProofOfConcept = "Identificar e explorar configurações padrão, serviços abertos desnecessários ou informações do sistema expostas.",
    Impact = "Unauthorized access to application features or data, system compromise, or information disclosure.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
    Remediation = "Implementar práticas de configuração segura, desativar recursos desnecessários, usar cabeçalhos de segurança e atualizar e corrigir regularmente todos os componentes.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Discovery",
    MitreTechniques = "T1082",
    VulnCwes = new List<string> { "CWE-16", "CWE-2" },
};

public static Vuln SensitiveDataExposure => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Exposição de Dados Sensíveis",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não protege adequadamente informações sensíveis, como dados financeiros, informações de saúde ou informações pessoalmente identificáveis (PII).",
    ProofOfConcept = "Interceptar transmissões de dados não criptografados ou acessar armazenamento de dados sensíveis inadequadamente protegidos.",
    Impact = "Exposure of sensitive user data, potential for identity theft, financial fraud, or violation of data protection regulations.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "Criptografar dados sensíveis em trânsito e em repouso, implementar gerenciamento adequado de chaves e minimizar a exposição de dados sensíveis em logs e mensagens de erro.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Collection, Exfiltration",
    MitreTechniques = "T1005",
    VulnCwes = new List<string> { "CWE-311", "CWE-312", "CWE-319" },
};

public static Vuln InsufficientLoggingAndMonitoring => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Registro e Monitoramento Insuficientes",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não gera logs adequados para eventos de segurança, ou falha em monitorar e responder a incidentes de segurança em tempo hábil.",
    ProofOfConcept = "Realizar atividades suspeitas sem detecção, ou demonstrar a falta de trilhas de auditoria adequadas para operações críticas.",
    Impact = "Delayed or missed detection of malicious activities, hindered incident response and forensics capabilities.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar registro abrangente para eventos relevantes de segurança, garantir armazenamento e proteção adequados de logs e estabelecer mecanismos eficazes de monitoramento e alerta.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Defense Evasion, Impact",
    MitreTechniques = "T1562",
    VulnCwes = new List<string> { "CWE-778", "CWE-223" },
};

public static Vuln UsingComponentsWithKnownVulnerabilities => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Uso de Componentes com Vulnerabilidades Conhecidas",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação usa componentes, bibliotecas ou frameworks de terceiros com vulnerabilidades de segurança conhecidas.",
    ProofOfConcept = "Identificar componentes desatualizados e demonstrar a exploração de vulnerabilidades conhecidas nesses componentes.",
    Impact = "Potential for various types of attacks depending on the vulnerability, including data theft, remote code execution, or application compromise.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Atualizar e corrigir regularmente todos os componentes, implementar uma ferramenta de análise de composição de software e manter um inventário de todos os componentes usados e suas versões.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-1035" },
};

public static Vuln ServerSideRequestForgery => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falsificação de Solicitação do Lado do Servidor (SSRF)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação processa URLs ou caminhos de arquivo fornecidos pelo usuário para recuperar recursos, permitindo que um atacante manipule solicitações para acessar recursos internos ou realizar ações não autorizadas.",
    ProofOfConcept = "Demonstrar a capacidade de fazer o servidor solicitar recursos internos ou sites externos controlados pelo atacante.",
    Impact = "Potential access to internal systems, data exfiltration, or remote code execution in some cases.",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:H",
    Remediation = "Implementar validação rigorosa de entrada, usar listas de permissão para URLs ou domínios permitidos, desativar esquemas de URL desnecessários e usar um servidor separado para fazer solicitações externas.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Lateral Movement",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-918" },
};

public static Vuln XmlExternalEntityProcessing => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Processamento de Entidade Externa XML (XXE)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação processa entrada XML que inclui referências a entidades externas sem validação adequada, permitindo que atacantes revelem arquivos internos, realizem falsificação de solicitação do lado do servidor ou executem ataques de negação de serviço.",
    ProofOfConcept = "Demonstrar a capacidade de ler arquivos internos ou fazer o servidor se conectar a hosts arbitrários usando entrada XML contendo entidades externas maliciosas.",
    Impact = "Potential disclosure of sensitive data, server-side request forgery, or denial of service.",
    CVSS3 = 8.2,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:H",
    Remediation = "Desativar o processamento de entidades externas XML e DTD em todos os analisadores XML na aplicação, usar formatos de dados menos complexos como JSON quando possível, e validar e sanitizar todas as entradas XML.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-611" },
};

public static Vuln LackOfRateLimiting => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falta de Limitação de Taxa",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não implementa mecanismos adequados de limitação de taxa, permitindo que atacantes realizem um número excessivo de solicitações ou operações.",
    ProofOfConcept = "Demonstrar a capacidade de fazer um grande número de solicitações em um curto período de tempo sem quaisquer restrições.",
    Impact = "Potential for denial of service, brute force attacks, or excessive resource consumption.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    Remediation = "Implementar limitação de taxa em todos os endpoints da API e funções críticas. Usar técnicas como algoritmos de balde de tokens ou contadores de janela fixa para restringir o número de solicitações que um usuário pode fazer em um determinado período de tempo.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Impact",
    MitreTechniques = "T1499",
    VulnCwes = new List<string> { "CWE-770" },
};

public static Vuln InadequateOAuth2Implementation => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Implementação Inadequada de OAuth 2.0",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A implementação OAuth 2.0 da aplicação contém falhas de segurança, como validação inadequada de URIs de redirecionamento, armazenamento inseguro de tokens ou manuseio incorreto de parâmetros de estado.",
    ProofOfConcept = "Demonstrar a capacidade de realizar roubo de tokens, tomada de conta ou acesso não autorizado através de falhas na implementação do OAuth.",
    Impact = "Potential for unauthorized access to user accounts, data theft, or impersonation of users.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
    Remediation = "Implementar OAuth 2.0 de forma segura seguindo as melhores práticas: validar todos os URIs de redirecionamento, usar parâmetros de estado para prevenir CSRF, armazenar e transmitir tokens de forma segura e implementar validação e expiração adequadas de tokens.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Lateral Movement",
    MitreTechniques = "T1550",
    VulnCwes = new List<string> { "CWE-346", "CWE-601" },
};

public static Vuln InsufficientAntiAutomation => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Anti-Automação Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação carece de medidas suficientes para prevenir ataques automatizados, como preenchimento de credenciais, tentativas de força bruta ou raspagem de conteúdo.",
    ProofOfConcept = "Demonstrar a capacidade de realizar solicitações automatizadas de alto volume sem acionar nenhum mecanismo defensivo.",
    Impact = "Potential for account takeover, data harvesting, or service degradation through automated attacks.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar medidas anti-automação como CAPTCHA, limitação de taxa, restrições baseadas em IP e análise comportamental para detectar e prevenir ataques automatizados.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Credential Access",
    MitreTechniques = "T1110",
    VulnCwes = new List<string> { "CWE-799", "CWE-837" },
};

public static Vuln WeakCryptographicAlgorithms => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Algoritmos Criptográficos Fracos",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação usa algoritmos criptográficos fracos ou desatualizados que são suscetíveis a ataques.",
    ProofOfConcept = "Identificar o uso de algoritmos fracos (por exemplo, MD5, SHA1, DES) nas operações criptográficas da aplicação.",
    Impact = "Potential for decryption of sensitive data, compromised integrity of signed data, or breaking of secure communication channels.",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Substituir algoritmos fracos por algoritmos criptográficos fortes e modernos (por exemplo, AES, SHA-256, RSA com tamanhos de chave apropriados) e seguir as melhores práticas para sua implementação.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Impact",
    MitreTechniques = "T1557",
    VulnCwes = new List<string> { "CWE-327", "CWE-326" },
};

public static Vuln ImproperCertificateValidation => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Validação Inadequada de Certificados",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não valida adequadamente os certificados SSL/TLS, potencialmente permitindo ataques de homem-no-meio ou conexões com servidores maliciosos.",
    ProofOfConcept = "Demonstrar a capacidade de interceptar tráfego SSL/TLS usando um certificado autoassinado ou inválido sem que a aplicação o detecte.",
    Impact = "Potential for eavesdropping on sensitive communications, data theft, or injection of malicious content.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar validação adequada de certificados, incluindo verificação de expiração, revogação e correspondência de nomes de host. Usar fixação de certificados para aplicações de alta segurança.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Collection, Man-in-the-Middle",
    MitreTechniques = "T1557",
    VulnCwes = new List<string> { "CWE-295" },
};

public static Vuln CrossSiteRequestForgery => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falsificação de Solicitação Entre Sites (CSRF)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não implementa proteções CSRF adequadas, permitindo que atacantes enganem os usuários para realizar ações não intencionadas na aplicação autenticada.",
    ProofOfConcept = "Criar uma página web maliciosa que, quando visitada por um usuário autenticado, realiza uma ação não autorizada na aplicação vulnerável.",
    Impact = "Potential for unauthorized actions performed on behalf of authenticated users, such as changes to account settings or unauthorized transfers.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
    Remediation = "Implementar tokens anti-CSRF para todas as operações que alteram o estado, usar o atributo de cookie SameSite e considerar implementar defesas adicionais como cabeçalhos de solicitação personalizados.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Privilege Escalation",
    MitreTechniques = "T1204",
    VulnCwes = new List<string> { "CWE-352" },
};

public static Vuln InsufficientPasswordRecoveryMechanism => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Mecanismo Insuficiente de Recuperação de Senha",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O mecanismo de recuperação de senha da aplicação é fraco ou pode ser facilmente contornado, potencialmente permitindo que atacantes assumam o controle das contas dos usuários.",
    ProofOfConcept = "Demonstrar a capacidade de redefinir a senha de um usuário sem autenticação adequada ou contornando medidas de segurança.",
    Impact = "Potential for unauthorized access to user accounts, leading to data theft or account abuse.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar um processo seguro de recuperação de senha usando tokens de recuperação de uso único e com tempo limitado, enviados por canais fora de banda. Evitar usar perguntas de segurança como único método de recuperação.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access",
    MitreTechniques = "T1552",
    VulnCwes = new List<string> { "CWE-640" },
};
public static Vuln LackOfInputSanitization => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falta de Sanitização de Entrada",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não sanitiza ou valida adequadamente a entrada do usuário, potencialmente permitindo vários ataques de injeção ou outras entradas maliciosas.",
    ProofOfConcept = "Demonstrar a capacidade de injetar payloads maliciosos (por exemplo, injeção SQL, XSS) através de campos de entrada do usuário.",
    Impact = "Potential for data manipulation, unauthorized data access, or execution of malicious scripts, depending on the context of the unsanitized input.",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
    Remediation = "Implementar validação e sanitização adequadas de entrada para todas as entradas do usuário. Usar consultas parametrizadas para operações de banco de dados, codificar a saída para prevenção de XSS e validar entradas contra uma lista branca de caracteres e formatos permitidos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-20", "CWE-79", "CWE-89" },
};

public static Vuln InsufficientSessionTimeout => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Tempo Limite de Sessão Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não implementa mecanismos adequados de tempo limite de sessão, permitindo que as sessões permaneçam ativas por períodos prolongados.",
    ProofOfConcept = "Demonstrar que a sessão de um usuário permanece ativa mesmo após longos períodos de inatividade ou fechamento do navegador.",
    Impact = "Increased risk of session hijacking, especially on shared computers or in case of session token theft.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    Remediation = "Implementar mecanismos adequados de tempo limite de sessão. Definir tempos de expiração razoáveis para sessões e garantir que as sessões sejam invalidadas após o logout do usuário ou períodos prolongados de inatividade.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Defense Evasion",
    MitreTechniques = "T1497",
    VulnCwes = new List<string> { "CWE-613" },
};

public static Vuln ImproperErrorHandling => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Tratamento Inadequado de Erros",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação revela informações sensíveis através de mensagens de erro detalhadas ou rastreamentos de pilha, potencialmente auxiliando atacantes a entender a estrutura e vulnerabilidades da aplicação.",
    ProofOfConcept = "Provocar erros na aplicação que revelem informações sensíveis, como estrutura do banco de dados, caminhos de arquivos ou endereços IP internos.",
    Impact = "Information disclosure that could aid attackers in further exploiting the application or underlying systems.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
    Remediation = "Implementar tratamento adequado de erros que exiba mensagens de erro genéricas para os usuários, enquanto registra informações detalhadas de erro de forma segura para os desenvolvedores. Garantir que os modos de depuração estejam desativados em ambientes de produção.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Discovery",
    MitreTechniques = "T1082",
    VulnCwes = new List<string> { "CWE-209", "CWE-200" },
};

public static Vuln MissingSecurityHeaders => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Cabeçalhos de Segurança Ausentes",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não implementa cabeçalhos de segurança importantes que podem ajudar a proteger contra vários ataques, como XSS, clickjacking e ataques de homem-no-meio.",
    ProofOfConcept = "Analisar os cabeçalhos de resposta HTTP e demonstrar a ausência de cabeçalhos de segurança importantes, como Content-Security-Policy, X-Frame-Options ou Strict-Transport-Security.",
    Impact = "Increased vulnerability to various attacks that could have been mitigated by proper security headers.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar cabeçalhos de segurança apropriados, incluindo Content-Security-Policy, X-Frame-Options, Strict-Transport-Security, X-Content-Type-Options e Referrer-Policy. Configurar esses cabeçalhos corretamente com base nos requisitos da aplicação.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Defense Evasion",
    MitreTechniques = "T1556",
    VulnCwes = new List<string> { "CWE-693", "CWE-1021" },
};

public static Vuln InsecureUseOfCryptography => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Uso Inseguro de Criptografia",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação usa funções criptográficas de forma insegura, como usar tamanhos de chave fracos, gerenciamento inadequado de chaves ou implementação incorreta de protocolos criptográficos.",
    ProofOfConcept = "Identificar instâncias de práticas criptográficas inseguras, como chaves de criptografia codificadas, uso do modo ECB para criptografia simétrica ou validação inadequada de certificados.",
    Impact = "Potential compromise of encrypted data, broken confidentiality or integrity of communications, or bypass of security mechanisms relying on cryptography.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Usar bibliotecas criptográficas bem testadas, garantir o gerenciamento adequado de chaves (geração, armazenamento e rotação), usar tamanhos de chave e modos de operação apropriados e seguir as melhores práticas para os protocolos criptográficos escolhidos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access, Impact",
    MitreTechniques = "T1552",
    VulnCwes = new List<string> { "CWE-327", "CWE-320" },
};

public static Vuln BrokenFunctionLevelAuthorization => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Autorização Quebrada em Nível de Função",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação falha em restringir adequadamente o acesso a certas funções com base nos papéis do usuário, permitindo que usuários realizem ações para as quais não deveriam estar autorizados.",
    ProofOfConcept = "Demonstrar o acesso a funções administrativas ou a realização de ações privilegiadas usando uma conta de usuário com baixos privilégios.",
    Impact = "Unauthorized access to sensitive functionality, potential for data theft, manipulation, or system compromise.",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar controles adequados de acesso em nível de função. Aplicar verificações de autorização consistentemente em todas as funções da aplicação. Usar controle de acesso baseado em funções (RBAC) e aplicar o princípio do menor privilégio.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Privilege Escalation",
    MitreTechniques = "T1548",
    VulnCwes = new List<string> { "CWE-285" },
};

public static Vuln InsecureCommunicationChannels => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Canais de Comunicação Inseguros",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação usa protocolos inseguros ou criptografia fraca para transmissão de dados, potencialmente expondo informações sensíveis a interceptação ou manipulação.",
    ProofOfConcept = "Demonstrar a capacidade de interceptar e ler dados sensíveis em trânsito, ou mostrar o uso de protocolos desatualizados como SSLv3 ou TLS 1.0.",
    Impact = "Potential exposure of sensitive data, including credentials, personal information, or business-critical data to unauthorized parties.",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar protocolos de comunicação seguros (TLS 1.2 ou superior) para todas as transmissões de dados. Garantir a configuração adequada de algoritmos de criptografia e tamanhos de chave. Usar fixação de certificado para aplicações móveis.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Collection, Exfiltration",
    MitreTechniques = "T1040",
    VulnCwes = new List<string> { "CWE-319", "CWE-326" },
};

public static Vuln LackOfSecureDefaults => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falta de Padrões Seguros",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação ou seus componentes são implantados com configurações padrão inseguras, potencialmente expondo o sistema a riscos desnecessários.",
    ProofOfConcept = "Identificar contas padrão com senhas fracas, serviços desnecessários habilitados por padrão ou permissões padrão excessivamente permissivas.",
    Impact = "Increased attack surface and potential for exploitation of unnecessary features or services.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar uma abordagem 'segura por padrão'. Desativar recursos e serviços desnecessários, remover contas padrão ou alterar suas credenciais e aplicar princípios de menor privilégio às configurações padrão.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access",
    MitreTechniques = "T1133",
    VulnCwes = new List<string> { "CWE-276", "CWE-1188" },
};

public static Vuln InsufficientProtectionFromAutomatedThreats => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Proteção Insuficiente contra Ameaças Automatizadas",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação carece de defesas adequadas contra ataques automatizados, como preenchimento de credenciais, tentativas de força bruta ou raspagem de conteúdo.",
    ProofOfConcept = "Demonstrar a capacidade de realizar um alto volume de solicitações (por exemplo, tentativas de login ou recuperação de dados) sem acionar nenhum mecanismo defensivo.",
    Impact = "Increased risk of account takeover, data harvesting, or service degradation due to automated attacks.",
    CVSS3 = 6.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar limitação de taxa, desafios CAPTCHA, bloqueios de conta e restrições baseadas em IP. Usar análise comportamental para detectar e prevenir ataques automatizados. Considerar o uso de firewalls de aplicação web (WAF) para proteção adicional.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Credential Access",
    MitreTechniques = "T1110",
    VulnCwes = new List<string> { "CWE-799", "CWE-307" },
};

public static Vuln UnvalidatedRedirectsAndForwards => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Redirecionamentos e Encaminhamentos não Validados",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação redireciona ou encaminha usuários para sites potencialmente maliciosos sem a devida validação da URL de destino.",
    ProofOfConcept = "Demonstrar a capacidade de manipular parâmetros de redirecionamento para enviar usuários para sites externos arbitrários.",
    Impact = "Potential for phishing attacks, malware distribution, or social engineering by redirecting users to malicious sites.",
    CVSS3 = 6.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    Remediation = "Implementar validação rigorosa de todos os destinos de redirecionamento. Usar uma lista branca de destinos permitidos ou validar contra um padrão de URLs conhecidas e seguras. Evitar usar entrada fornecida pelo usuário diretamente em funções de redirecionamento.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access",
    MitreTechniques = "T1566",
    VulnCwes = new List<string> { "CWE-601" },
};

public static Vuln InsecureAuthenticationMechanism => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Mecanismo de Autenticação Inseguro",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação usa mecanismos de autenticação fracos ou facilmente contornáveis, potencialmente permitindo acesso não autorizado a contas de usuários.",
    ProofOfConcept = "Demonstrar a capacidade de contornar controles de autenticação ou explorar fraquezas no processo de autenticação.",
    Impact = "Unauthorized access to user accounts, potential for identity theft, data breach, or system compromise.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar mecanismos de autenticação fortes e multifatoriais. Usar gerenciamento seguro de sessões, impor políticas de senha e considerar o uso de provedores de identidade federada para segurança aprimorada.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Credential Access",
    MitreTechniques = "T1078",
    VulnCwes = new List<string> { "CWE-287", "CWE-384" },
};

public static Vuln InsufficientAntiCachingHeaders => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Cabeçalhos Anti-Cache Insuficientes",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não define cabeçalhos de controle de cache adequados, potencialmente permitindo que informações sensíveis sejam armazenadas em caches de navegadores ou proxies intermediários.",
    ProofOfConcept = "Demonstrar a capacidade de recuperar informações sensíveis do cache do navegador ou mostrar que páginas sensíveis são armazenadas em cache por proxies.",
    Impact = "Potential exposure of sensitive data to unauthorized parties, especially on shared computers or through man-in-the-middle attacks.",
    CVSS3 = 5.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
    Remediation = "Implementar cabeçalhos de controle de cache adequados (por exemplo, Cache-Control: no-store, no-cache, must-revalidate) para páginas contendo informações sensíveis. Usar HTTPS para evitar o armazenamento em cache por proxies intermediários.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Collection",
    MitreTechniques = "T1557",
    VulnCwes = new List<string> { "CWE-525" },
};

public static Vuln LackOfProperTLSConfiguration => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falta de Configuração Adequada de TLS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação usa configurações TLS fracas ou desatualizadas, potencialmente expondo as comunicações a interceptação ou manipulação.",
    ProofOfConcept = "Demonstrar o uso de conjuntos de cifras fracos, versões TLS desatualizadas ou validação de certificado mal configurada.",
    Impact = "Potential for man-in-the-middle attacks, data interception, or degradation of encrypted communications.",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Configurar o TLS para usar apenas conjuntos de cifras fortes, desativar versões TLS mais antigas (1.0, 1.1), garantir a validação adequada de certificados e implementar HSTS. Revisar e atualizar regularmente as configurações TLS.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Command and Control",
    MitreTechniques = "T1573",
    VulnCwes = new List<string> { "CWE-326", "CWE-327" },
};

public static Vuln InsufficientDataProtection => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Proteção Insuficiente de Dados em Trânsito e em Repouso",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não protege adequadamente dados sensíveis durante a transmissão ou armazenamento, potencialmente expondo-os a acesso não autorizado ou adulteração.",
    ProofOfConcept = "Demonstrar a capacidade de interceptar dados não criptografados em trânsito ou acessar dados sensíveis armazenados de maneira insegura.",
    Impact = "Potential exposure of sensitive user data, compliance violations, and increased risk of data breaches.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar criptografia forte para dados em trânsito (por exemplo, TLS) e em repouso (por exemplo, criptografia em nível de arquivo ou banco de dados). Usar práticas seguras de gerenciamento de chaves e garantir que todos os dados sensíveis sejam identificados e protegidos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Collection, Exfiltration",
    MitreTechniques = "T1040, T1029",
    VulnCwes = new List<string> { "CWE-311", "CWE-312" },
};

public static Vuln ImproperAssetManagement => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Gerenciamento Inadequado de Ativos",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A organização carece de inventário e gerenciamento adequados de seus ativos de TI, potencialmente levando a sistemas não corrigidos, servidores esquecidos ou dispositivos não autorizados na rede.",
    ProofOfConcept = "Identificar sistemas não gerenciados ou esquecidos, versões de software desatualizadas ou dispositivos não autorizados conectados à rede.",
    Impact = "Increased attack surface, potential for undetected compromises, and difficulty in maintaining overall security posture.",
    CVSS3 = 5.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
    Remediation = "Implementar um sistema abrangente de gerenciamento de ativos. Fazer inventário e atualizar regularmente todos os ativos de TI, incluindo hardware, software e recursos em nuvem. Estabelecer processos para gerenciamento do ciclo de vida dos ativos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Discovery",
    MitreTechniques = "T1046",
    VulnCwes = new List<string> { "CWE-1059" },
};

public static Vuln LackOfSoftwareUpdates => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falta de Atualizações de Software/Gerenciamento de Patches",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação ou seus sistemas subjacentes não são atualizados regularmente, potencialmente deixando vulnerabilidades conhecidas sem correção.",
    ProofOfConcept = "Identificar versões de software desatualizadas com vulnerabilidades conhecidas que poderiam ser exploradas.",
    Impact = "Increased risk of exploitation of known vulnerabilities, potentially leading to system compromise, data breaches, or service disruptions.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar um processo robusto de gerenciamento de patches. Atualizar regularmente todos os componentes de software, incluindo a aplicação, bibliotecas, frameworks e sistemas operacionais. Automatizar o processo de aplicação de patches quando possível.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-1104" },
};

public static Vuln InsufficientPrivacyControls => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Controles de Privacidade Insuficientes",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação carece de controles adequados para proteger a privacidade do usuário, potencialmente violando regulamentos de proteção de dados ou expectativas dos usuários.",
    ProofOfConcept = "Demonstrar coleta, processamento ou compartilhamento de dados pessoais sem o consentimento adequado ou além dos propósitos declarados.",
    Impact = "Potential legal and regulatory violations, loss of user trust, and possible financial penalties.",
    CVSS3 = 5.9,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "Implementar princípios de privacidade desde a concepção. Realizar avaliações de impacto na privacidade, obter o consentimento adequado do usuário para coleta e processamento de dados, e fornecer políticas de privacidade claras. Implementar princípios de minimização de dados e limitação de finalidade.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Collection",
    MitreTechniques = "T1005",
    VulnCwes = new List<string> { "CWE-359" },
};

public static Vuln InsecureAPIEndpoints => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Endpoints de API Inseguros",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os endpoints da API da aplicação carecem de controles de segurança adequados, potencialmente permitindo acesso não autorizado, manipulação de dados ou divulgação de informações.",
    ProofOfConcept = "Demonstrar acesso não autorizado a endpoints da API, manipulação de dados ou extração de informações sensíveis através de chamadas de API.",
    Impact = "Potential for data breaches, unauthorized actions, or system compromise through API exploitation.",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar autenticação e autorização fortes para todos os endpoints da API. Usar chaves de API, tokens OAuth ou outros métodos seguros. Validar e sanitizar todas as entradas da API, implementar limitação de taxa e usar HTTPS para todas as comunicações da API.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-284", "CWE-285" },
};

public static Vuln InsufficientInputValidation => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Validação de Entrada Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não valida adequadamente a entrada do usuário, potencialmente permitindo ataques de injeção, estouro de buffer ou outras entradas maliciosas.",
    ProofOfConcept = "Demonstrar a capacidade de inserir dados maliciosos que são processados pela aplicação sem validação ou sanitização adequada.",
    Impact = "Potential for various attacks including SQL injection, XSS, command injection, or application crashes.",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar validação rigorosa de entrada para todos os dados fornecidos pelo usuário. Usar listas brancas, sanitização de entrada e consultas parametrizadas. Validar a entrada quanto ao tipo, comprimento, formato e intervalo conforme apropriado.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-20" },
};

public static Vuln ImproperOutputEncoding => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Codificação de Saída Inadequada",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não codifica adequadamente a saída antes de renderizá-la para os usuários, potencialmente permitindo ataques de injeção como Cross-Site Scripting (XSS).",
    ProofOfConcept = "Demonstrar a capacidade de injetar e executar scripts ou HTML maliciosos na saída da aplicação.",
    Impact = "Potential for client-side attacks, data theft, session hijacking, or defacement of the application.",
    CVSS3 = 6.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    Remediation = "Implementar codificação de saída consciente do contexto para todo o conteúdo dinâmico. Usar funções de codificação apropriadas para contextos HTML, JavaScript, CSS e URL. Considerar o uso de mecanismos de template com escape automático.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1189",
    VulnCwes = new List<string> { "CWE-79", "CWE-116" },
};

public static Vuln InsecureFileHandling => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Manipulação Insegura de Arquivos",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não valida ou manipula adequadamente as operações de arquivo, potencialmente permitindo acesso não autorizado, inclusão de arquivos ou execução de arquivos maliciosos.",
    ProofOfConcept = "Demonstrar a capacidade de acessar arquivos fora dos diretórios pretendidos, fazer upload de arquivos maliciosos ou executar arquivos arbitrários no servidor.",
    Impact = "Potential for unauthorized access to sensitive files, remote code execution, or compromise of the server.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar validação rigorosa de entrada para nomes e caminhos de arquivos. Usar listas brancas para tipos e extensões de arquivos permitidos. Armazenar arquivos carregados pelo usuário fora da raiz da web e usar bibliotecas seguras de manipulação de arquivos.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1505",
    VulnCwes = new List<string> { "CWE-73", "CWE-434" },
};

public static Vuln LackOfSecurePasswordStorage => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Falta de Armazenamento Seguro de Senhas",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação não armazena senhas de usuários de forma segura, potencialmente expondo-as a acesso não autorizado ou tornando-as vulneráveis a tentativas de quebra.",
    ProofOfConcept = "Demonstrar que as senhas são armazenadas em texto simples, usando algoritmos de hash fracos, ou sem o uso adequado de salt.",
    Impact = "Potential for unauthorized access to user accounts, mass account compromise in case of data breach.",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Usar algoritmos de hash adaptativos e fortes (por exemplo, bcrypt, Argon2) para o armazenamento de senhas. Implementar salt adequado e garantir fatores de trabalho suficientes. Nunca armazenar senhas em texto simples ou usando criptografia reversível.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "3.0",
    MitreValues = "Credential Access",
    MitreTechniques = "T1003",
    VulnCwes = new List<string> { "CWE-256", "CWE-916" },
};

public static Vuln InsufficientProtectionAgainstDoS => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Proteção Insuficiente Contra Negação de Serviço",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação carece de medidas adequadas para se proteger contra ataques de Negação de Serviço (DoS), potencialmente permitindo que atacantes sobrecarreguem os recursos do sistema e interrompam a disponibilidade do serviço.",
    ProofOfConcept = "Demonstrar a capacidade de consumir recursos excessivos ou acionar operações intensivas em recursos sem limitações adequadas.",
    Impact = "Potential for service disruption, degraded performance, or complete system unavailability.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    Remediation = "Implementar limitação de taxa, throttling de requisições e cotas de recursos. Usar algoritmos eficientes e caching quando apropriado. Considerar a implementação de CAPTCHAs para operações sensíveis e implantar soluções de mitigação de DoS no nível de rede.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Impact",
    MitreTechniques = "T1498",
    VulnCwes = new List<string> { "CWE-400" },
};

public static Vuln InadequateSessionManagement => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Gerenciamento Inadequado de Sessão",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação implementa práticas fracas de gerenciamento de sessão, potencialmente permitindo que atacantes sequestrem ou prevejam sessões de usuários.",
    ProofOfConcept = "Demonstrar a capacidade de sequestrar sessões de usuários, prever tokens de sessão ou manter sessões autenticadas além da duração pretendida.",
    Impact = "Potential for unauthorized access to user accounts, session hijacking, or bypass of authentication mechanisms.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar práticas seguras de gerenciamento de sessão: usar tokens de sessão criptograficamente fortes, impor transmissão segura de tokens (HTTPS), implementar expiração e rotação adequadas de sessão e invalidar sessões no logout.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Credential Access",
    MitreTechniques = "T1539",
    VulnCwes = new List<string> { "CWE-384", "CWE-613" },
};

public static Vuln InsecureDirectObjectReferences => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Referências Diretas Inseguras a Objetos",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação expõe referências a objetos de implementação interna, como arquivos, diretórios, registros de banco de dados ou chaves, sem verificações adequadas de controle de acesso.",
    ProofOfConcept = "Demonstrar a capacidade de acessar ou modificar recursos pertencentes a outros usuários manipulando referências a objetos em requisições.",
    Impact = "Unauthorized access to sensitive data, potential data theft, or manipulation of other users' information.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar controles de acesso adequados para todas as referências a objetos. Usar referências indiretas mapeadas para recursos reais no lado do servidor. Validar a autorização do usuário para cada acesso a uma referência direta a objeto.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Lateral Movement, Collection",
    MitreTechniques = "T1213",
    VulnCwes = new List<string> { "CWE-639" },
};

public static Vuln InsufficientSubresourceIntegrity => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Integridade Insuficiente de Sub-recursos",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação carrega recursos externos (como scripts ou folhas de estilo) sem verificações adequadas de integridade, potencialmente permitindo que atacantes injetem conteúdo malicioso através de recursos de terceiros comprometidos.",
    ProofOfConcept = "Demonstrar que a aplicação carrega recursos externos sem verificações de Integridade de Sub-recursos (SRI), tornando-a vulnerável a ataques de cadeia de suprimentos.",
    Impact = "Potential for execution of unauthorized scripts, leading to data theft, defacement, or other client-side attacks.",
    CVSS3 = 6.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    Remediation = "Implementar Integridade de Sub-recursos (SRI) para todos os recursos carregados externamente. Usar atributos de integridade com hashes criptográficos para garantir a integridade dos recursos carregados.",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "Possible",
    OWASPVector = "2.0",
    MitreValues = "Initial Access",
    MitreTechniques = "T1195",
    VulnCwes = new List<string> { "CWE-353" },
};

public static Vuln ImproperAccessControl => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Controle de Acesso Inadequado",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação falha em restringir adequadamente o acesso a recursos ou funcionalidades com base nos privilégios do usuário, potencialmente permitindo que usuários não autorizados realizem ações ou acessem dados que não deveriam.",
    ProofOfConcept = "Demonstrar a capacidade de acessar funcionalidades ou dados restritos manipulando parâmetros de requisição ou usando uma conta com privilégios inferiores.",
    Impact = "Unauthorized access to sensitive data or functionality, potential for privilege escalation or data manipulation.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar controles de acesso adequados tanto no nível da aplicação quanto da API. Usar controle de acesso baseado em funções (RBAC) e aplicar o princípio do menor privilégio. Validar as permissões do usuário para cada ação sensível ou acesso a dados.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Privilege Escalation, Lateral Movement",
    MitreTechniques = "T1548",
    VulnCwes = new List<string> { "CWE-284", "CWE-285" },
};
public static Vuln XmlExternalEntityInjection => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Injeção de Entidade Externa XML (XXE)",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação processa entradas XML que incluem referências a entidades externas sem validação adequada, permitindo que atacantes divulguem arquivos internos, realizem falsificação de solicitação do lado do servidor ou executem ataques de negação de serviço.",
    ProofOfConcept = "Demonstrar a capacidade de ler arquivos internos ou fazer o servidor se conectar a hosts arbitrários usando entradas XML contendo entidades externas maliciosas.",
    Impact = "Potential disclosure of sensitive data, server-side request forgery, or denial of service.",
    CVSS3 = 8.2,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:H",
    Remediation = "Desabilitar o processamento de entidades externas XML e DTD em todos os analisadores XML na aplicação, usar formatos de dados menos complexos como JSON quando possível, e validar e sanitizar todas as entradas XML.",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-611" },
};

public static Vuln InsufficientThreatModeling => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Modelagem de Ameaças Insuficiente",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação carece de modelagem de ameaças abrangente, potencialmente perdendo riscos críticos de segurança e falhando em implementar contramedidas apropriadas.",
    ProofOfConcept = "Identificar vulnerabilidades de segurança ou vetores de ataque que não foram considerados durante a fase de design e não são adequadamente abordados na aplicação.",
    Impact = "Increased overall risk of security breaches due to unidentified threats, potentially leading to various types of attacks and compromises.",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "Implementar um processo abrangente de modelagem de ameaças durante a fase de design. Usar metodologias como STRIDE ou PASTA. Atualizar regularmente os modelos de ameaças e garantir que os controles de segurança abordem as ameaças identificadas.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Defense Evasion",
    MitreTechniques = "T1195",
    VulnCwes = new List<string> { "CWE-1053" },
};

public static Vuln InadequateSecurityArchitecture => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Arquitetura de Segurança Inadequada",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A arquitetura de segurança da aplicação é insuficiente, carecendo de controles de segurança adequados, padrões de design seguros ou uma abordagem de defesa em profundidade.",
    ProofOfConcept = "Demonstrar falhas arquitetônicas que permitem contornar múltiplas camadas de segurança ou explorar fraquezas sistêmicas no design da aplicação.",
    Impact = "Increased vulnerability to various attacks due to systemic weaknesses, potentially leading to large-scale compromises or data breaches.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar uma arquitetura de segurança robusta seguindo princípios como defesa em profundidade, menor privilégio e segurança por design. Realizar revisões regulares da arquitetura e garantir alinhamento com as melhores práticas de segurança.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Defense Evasion, Lateral Movement",
    MitreTechniques = "T1190",
    VulnCwes = new List<string> { "CWE-1008" },
};

public static Vuln FlawedBusinessLogic => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Lógica de Negócios Falha",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação contém falhas na implementação de sua lógica de negócios, permitindo que os usuários realizem ações que violam o processo de negócios pretendido ou as suposições de segurança.",
    ProofOfConcept = "Demonstrar a capacidade de manipular os processos de negócios da aplicação, como contornar pagamentos, alterar quantidades de pedidos ou acessar descontos não autorizados.",
    Impact = "Potential for financial losses, unauthorized access to services, or manipulation of critical business processes.",
    CVSS3 = 7.7,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N",
    Remediation = "Implementar validação minuciosa da lógica de negócios. Garantir que todos os processos de negócios sejam adequadamente modelados e aplicados na aplicação. Realizar revisões por pares da implementação da lógica de negócios e realizar testes abrangentes de cenários de negócios.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Privilege Escalation",
    MitreTechniques = "T1195",
    VulnCwes = new List<string> { "CWE-840" },
};

public static Vuln MaliciousCodeInjection => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Injeção de Código Malicioso",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação é vulnerável à injeção de código malicioso, permitindo que atacantes executem comandos ou scripts não autorizados dentro do contexto da aplicação.",
    ProofOfConcept = "Demonstrar a capacidade de injetar e executar código malicioso, como comandos do sistema operacional, consultas SQL ou scripts do lado do cliente, através de vários vetores de entrada.",
    Impact = "Potential for complete system compromise, data theft, or unauthorized actions performed with the application's privileges.",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar validação estrita de entrada e codificação de saída. Usar consultas parametrizadas para operações de banco de dados. Evitar o uso de eval() ou outras funções perigosas que executem código dinâmico. Implementar cabeçalhos de Política de Segurança de Conteúdo (CSP).",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "3.0",
    MitreValues = "Execution, Privilege Escalation",
    MitreTechniques = "T1059",
    VulnCwes = new List<string> { "CWE-94", "CWE-79", "CWE-89" },
};

public static Vuln InsecureThirdPartyComponents => new Vuln
{
    Template = true,
    Language = Language.Portuguese,
    Name = "Componentes de Terceiros Inseguros",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A aplicação utiliza componentes, bibliotecas ou frameworks de terceiros que estão desatualizados, contêm vulnerabilidades conhecidas ou são obtidos de fontes não confiáveis.",
    ProofOfConcept = "Identificar e demonstrar a exploração de vulnerabilidades conhecidas em componentes de terceiros utilizados pela aplicação.",
    Impact = "Potential for various types of attacks depending on the vulnerabilities in the components, including data theft, remote code execution, or application compromise.",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "Implementar uma ferramenta de análise de composição de software (SCA) para rastrear e gerenciar componentes de terceiros. Atualizar regularmente os componentes para suas versões seguras mais recentes. Estabelecer um processo para verificar e aprovar código de terceiros. Usar fontes confiáveis para obter componentes.",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "Likely",
    OWASPVector = "2.0",
    MitreValues = "Initial Access, Execution",
    MitreTechniques = "T1195",
    VulnCwes = new List<string> { "CWE-1104" },
};
}*/