using Cervantes.CORE.Entities;

namespace Cervantes.IFR.VulnTemplates;

public class VulnTemplatesGeneralPT
{
    public static Vuln KerberoastingVulnerability => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Contas de Serviço Vulneráveis ao Kerberoasting",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As contas de serviço no domínio estão configuradas com Nomes Principais de Serviço (SPN) e senhas fracas, tornando-as vulneráveis a ataques Kerberoasting. Essas contas permitem que seus tickets Kerberos TGS sejam solicitados e descriptografados sem detecção.",
    ProofOfConcept = "1. Enumerados os Nomes Principais de Serviço usando SetSPN.exe -Q */*\n2. Usado Rubeus para extrair tickets Kerberos TGS\n3. Descriptografia bem-sucedida de tickets extraídos offline usando hashcat",
    Impact = "A exploração bem-sucedida permite aos atacantes:\n- Obter credenciais de contas de serviço\n- Acessar serviços e sistemas críticos\n- Potencialmente escalar privilégios se as contas de serviço tiverem direitos administrativos\n- Mover-se lateralmente pela rede",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Redefinir senhas de contas de serviço usando senhas complexas (>25 caracteres)\n2. Implementar rotação regular de senhas\n3. Revisar e limitar privilégios de contas de serviço\n4. Monitorar solicitações suspeitas de tickets TGS\n5. Considerar implementar Contas de Serviço Gerenciadas por Grupo (gMSA)",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1558",
    MitreTechniques = "T1558 - Steal or Forge Kerberos Tickets",
};

public static Vuln LLMNRPoisoning => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Envenenamento LLMNR/NBT-NS Habilitado",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os protocolos de Resolução de Nomes Multicast de Link-Local (LLMNR) e Serviço de Nomes NetBIOS (NBT-NS) estão habilitados na rede. Esses protocolos podem ser explorados através de ataques de envenenamento para capturar credenciais de autenticação.",
    ProofOfConcept = "1. Usado a ferramenta Responder para ouvir transmissões LLMNR/NBT-NS\n2. Capturados múltiplos hashes de resposta NTLMv2\n3. Demonstrada capacidade de descriptografia offline de hashes capturados",
    Impact = "Esta vulnerabilidade permite aos atacantes:\n- Interceptar tentativas de autenticação\n- Capturar hashes de senhas NTLM\n- Realizar descriptografia offline de senhas\n- Obter acesso não autorizado ao sistema\n- Permitir movimento lateral",
    CVSS3 = 8.0,
    CVSSVector = "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Desabilitar LLMNR via Política de Grupo\n2. Desabilitar NBT-NS em todos os adaptadores de rede\n3. Configurar sufixos DNS para domínios internos\n4. Implementar entradas WPAD apropriadas no DNS\n5. Implementar segmentação de rede\n6. Monitorar tentativas de envenenamento",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1557",
    MitreTechniques = "T1557 - Man-in-the-Middle",
};

public static Vuln LocalAdminPasswordReuse => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Reutilização de Senha de Administrador Local",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As contas de administrador local em múltiplos sistemas compartilham a mesma senha. Esta prática aumenta significativamente o risco de movimento lateral se um sistema for comprometido.",
    ProofOfConcept = "1. Extraído hash de senha de administrador local do sistema comprometido\n2. Autenticação bem-sucedida em múltiplos sistemas usando as mesmas credenciais\n3. Confirmada a reutilização de senha através da comparação de hashes",
    Impact = "A reutilização de senhas permite aos atacantes:\n- Mover-se lateralmente entre sistemas\n- Manter persistência\n- Escalar privilégios em toda a rede\n- Potencialmente comprometer domínios completos",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:H",
    Remediation = "1. Implementar LAPS (Solução de Senha de Administrador Local)\n2. Garantir senhas únicas para cada conta de administrador local\n3. Rotacionar regularmente as senhas de administrador local\n4. Monitorar tentativas de acesso não autorizadas\n5. Limitar o uso de contas de administrador local",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1003",
    MitreTechniques = "T1003 - OS Credential Dumping",
};

public static Vuln UnquotedServicePath => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidade de Caminho de Serviço Sem Aspas",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Medium,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os serviços do Windows estão configurados com caminhos de serviço sem aspas que contêm espaços. Esta configuração pode ser explorada para escalação de privilégios através da colocação de executáveis maliciosos no caminho.",
    ProofOfConcept = "1. Identificados serviços com caminhos sem aspas usando PowerShell\n2. Demonstrado acesso de escrita a diretórios de caminho de serviço\n3. Criado executável de prova de conceito para validar vulnerabilidade",
    Impact = "Esta vulnerabilidade permite aos atacantes:\n- Escalar privilégios para SYSTEM\n- Executar código arbitrário\n- Manter persistência\n- Comprometer sistemas afetados",
    CVSS3 = 7.8,
    CVSSVector = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Adicionar aspas a todos os caminhos de serviço que contenham espaços\n2. Revisar e restringir permissões de escrita em diretórios de serviço\n3. Auditar todas as configurações de serviço\n4. Implementar lista branca de aplicações\n5. Monitorar modificações suspeitas de serviços",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.Medium,
    JiraCreated = false,
    OWASPRisk = "Medium",
    OWASPImpact = "Moderate",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1574",
    MitreTechniques = "T1574 - Hijack Execution Flow",
};
public static Vuln SMBSigningDisabled => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Assinatura SMB Não Requerida",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A assinatura SMB não está forçada em múltiplos sistemas da rede. Esta configuração permite que os atacantes realizem ataques man-in-the-middle contra conexões SMB.",
    ProofOfConcept = "1. Enumerada configuração de assinatura SMB usando scripts de Nmap\n2. Confirmada falta de requisito de assinatura SMB usando CrackMapExec\n3. Realizado com sucesso ataque de retransmissão SMB entre sistemas afetados",
    Impact = "A falta de assinatura SMB permite aos atacantes:\n- Interceptar e retransmitir autenticação SMB\n- Capturar credenciais de autenticação\n- Executar comandos em sistemas alvo\n- Mover-se lateralmente pela rede\n- Escalar privilégios usando credenciais capturadas",
    CVSS3 = 8.3,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H",
    Remediation = "1. Habilitar assinatura SMB via Política de Grupo\n2. Configurar 'Servidor de rede Microsoft: Assinar digitalmente as comunicações (sempre)'\n3. Configurar 'Cliente de rede Microsoft: Assinar digitalmente as comunicações (sempre)'\n4. Monitorar tentativas de retransmissão SMB\n5. Implementar segmentação de rede",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1557",
    MitreTechniques = "T1557 - Man-in-the-Middle",
};

public static Vuln ExcessiveDomainAdminRights => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Privilégios Excessivos de Administrador de Domínio",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Um número excessivo de contas possui privilégios de Administrador de Domínio. Muitas dessas contas são utilizadas para atividades diárias e administração rotineira, aumentando a superfície de ataque do domínio.",
    ProofOfConcept = "1. Enumerada associação do grupo de Administradores de Domínio usando PowerView\n2. Identificadas múltiplas contas de usuário com privilégios desnecessários\n3. Documentados padrões de uso regular de contas privilegiadas para tarefas rotineiras",
    Impact = "Os privilégios excessivos criam riscos que incluem:\n- Maior superfície de ataque para escalação de privilégios\n- Maior impacto de comprometimento de credenciais\n- Maior potencial de movimento lateral\n- Maior dificuldade em rastrear acessos não autorizados\n- Maior risco de alterações acidentais no sistema",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar todas as contas de Administrador de Domínio\n2. Remover acessos privilegiados desnecessários\n3. Implementar acesso baseado em tempo para tarefas administrativas\n4. Criar contas separadas para atividades rotineiras\n5. Implementar o princípio do privilégio mínimo\n6. Monitorar alterações em grupos privilegiados",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};

public static Vuln GPPPasswordExposure => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Exposição de Senhas em Preferências de Política de Grupo",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "CVE-2014-1812",
    Description = "Foram identificadas credenciais armazenadas em Preferências de Política de Grupo (GPP) no SYSVOL. Embora estejam criptografadas, a chave de descriptografia é conhecida publicamente, permitindo que qualquer usuário do domínio recupere essas credenciais.",
    ProofOfConcept = "1. Localizados arquivos XML no SYSVOL contendo credenciais criptografadas\n2. Descriptografadas com sucesso credenciais usando chave AES conhecida\n3. Validado acesso usando credenciais recuperadas",
    Impact = "As credenciais expostas permitem aos atacantes:\n- Acessar sistemas e serviços sensíveis\n- Escalar privilégios\n- Mover-se lateralmente pela rede\n- Manter acesso persistente\n- Potencialmente acessar contas de administrador de domínio",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Remover todos os arquivos XML de GPP que contenham senhas\n2. Alterar todas as senhas expostas\n3. Usar métodos alternativos para implantação de credenciais\n4. Implementar gerenciamento apropriado de acesso privilegiado\n5. Monitorar SYSVOL para arquivos sensíveis\n6. Usar Contas de Serviço Gerenciadas por Grupo quando possível",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1552",
    MitreTechniques = "T1552 - Unsecured Credentials",
};

public static Vuln WeakServiceAccountPermissions => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Permissões Fracas em Contas de Serviço",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As contas de serviço foram configuradas com permissões excessivas além de seus requisitos operacionais. Essas contas têm permissões como direitos de replicação de domínio, privilégios de backup, ou acesso administrativo local em múltiplos sistemas.",
    ProofOfConcept = "1. Enumeradas permissões de contas de serviço usando BloodHound\n2. Identificados direitos e privilégios excessivos\n3. Documentadas rotas potenciais de ataque usando contas super-privilegiadas",
    Impact = "As contas de serviço super-privilegiadas permitem:\n- Rotas de escalação de privilégios\n- Acesso não autorizado a sistemas críticos\n- Comprometimento potencial do domínio\n- Maior superfície de ataque\n- Maior impacto de roubo de credenciais",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar permissões de contas de serviço\n2. Remover direitos desnecessários\n3. Implementar princípio do privilégio mínimo\n4. Usar contas de serviço gerenciadas\n5. Revisões regulares de permissões\n6. Monitorar alterações não autorizadas de permissões",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};
public static Vuln ClearTextProtocols => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Uso de Protocolos em Texto Claro",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Múltiplos sistemas estão usando protocolos de texto claro (por exemplo, FTP, Telnet, SMTP, HTTP, LDAP) para operações sensíveis. Estes protocolos transmitem dados, incluindo credenciais, sem criptografia.",
    ProofOfConcept = "1. Identificados protocolos de texto claro usando varredura de rede\n2. Capturados dados sensíveis usando captura de pacotes\n3. Demonstrada interceptação de credenciais em protocolos afetados",
    Impact = "Os protocolos de texto claro expõem:\n- Credenciais de usuário\n- Dados sensíveis em trânsito\n- Informações de configuração\n- Permitem ataques man-in-the-middle\n- Permitem sequestro de sessão",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "1. Substituir protocolos de texto claro por alternativas criptografadas\n2. Habilitar LDAPS para serviços de diretório\n3. Implementar TLS para serviços de e-mail\n4. Substituir FTP por SFTP/FTPS\n5. Usar HTTPS para serviços web\n6. Monitorar uso de protocolos não autorizados",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1040",
    MitreTechniques = "T1040 - Network Sniffing",
};

public static Vuln InsecureLDAPBinding => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vinculação LDAP Insegura Habilitada",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os Controladores de Domínio estão configurados para aceitar vinculações LDAP simples sobre conexões não criptografadas. Isto permite que credenciais e tráfego LDAP sensível sejam transmitidos em texto claro.",
    ProofOfConcept = "1. Verificados requisitos de assinatura LDAP usando ldapsearch\n2. Capturado tráfego de autenticação LDAP usando Wireshark\n3. Realizada vinculação LDAP com sucesso usando credenciais capturadas\n4. Confirmada falta de requisito SSL/TLS para conexões LDAP",
    Impact = "A vinculação LDAP insegura permite:\n- Interceptação de credenciais\n- Acesso não autorizado ao diretório\n- Divulgação de informações\n- Ataques man-in-the-middle\n- Escalação de privilégios no domínio",
    CVSS3 = 8.0,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Habilitar requisitos de assinatura LDAP\n2. Forçar LDAPS (LDAP sobre SSL/TLS)\n3. Configurar requisitos mínimos de segurança LDAP\n4. Atualizar aplicações para usar LDAP seguro\n5. Monitorar tráfego LDAP em texto claro",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1040",
    MitreTechniques = "T1040 - Network Sniffing",
};

public static Vuln WeakTLSConfiguration => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configuração Fraca de SSL/TLS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Múltiplos sistemas estão configurados para suportar versões obsoletas de SSL/TLS e conjuntos de cifra fracos. Isso inclui suporte para SSL 3.0, TLS 1.0, e cifras vulneráveis conhecidas.",
    ProofOfConcept = "1. Realizada varredura SSL/TLS usando sslyze\n2. Identificado suporte para protocolos obsoletos\n3. Documentado suporte de conjuntos de cifra fracos\n4. Demonstrados potenciais ataques de downgrade",
    Impact = "As configurações TLS fracas permitem:\n- Ataques man-in-the-middle\n- Ataques de downgrade de protocolo\n- Evasão de criptografia\n- Exposição de dados\n- Sequestro de sessão",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Desabilitar SSL 2.0/3.0 e TLS 1.0/1.1\n2. Habilitar apenas conjuntos de cifra fortes\n3. Configurar ordem apropriada de cifras\n4. Implementar configuração segura de TLS\n5. Testes regulares de segurança\n6. Monitorar downgrades de protocolo",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1557",
    MitreTechniques = "T1557 - Man-in-the-Middle",
};

public static Vuln DefaultCredentials => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Uso de Credenciais Padrão",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Foram encontrados múltiplos sistemas e aplicações usando credenciais padrão do fabricante. Isso inclui interfaces administrativas, dispositivos de rede e aplicações internas.",
    ProofOfConcept = "1. Identificados sistemas usando credenciais padrão\n2. Autenticação bem-sucedida usando senhas padrão conhecidas\n3. Documentados sistemas e interfaces afetados\n4. Demonstrado acesso privilegiado usando credenciais padrão",
    Impact = "As credenciais padrão permitem:\n- Acesso administrativo não autorizado\n- Comprometimento do sistema\n- Acesso à infraestrutura de rede\n- Movimento lateral\n- Riscos de vazamento de dados",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Alterar todas as senhas padrão\n2. Implementar política de senhas\n3. Auditorias regulares de credenciais\n4. Documentar alterações de senhas\n5. Implementar autenticação forte\n6. Monitorar uso de credenciais padrão",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};
public static Vuln MissingSecurityUpdates => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Atualizações Críticas de Segurança Ausentes",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Múltiplos sistemas carecem de atualizações e patches críticos de segurança. Estes sistemas são vulneráveis a exploits conhecidos que poderiam permitir a execução remota de código e escalação de privilégios.",
    ProofOfConcept = "1. Realizada varredura de vulnerabilidades\n2. Identificados patches de segurança ausentes\n3. Validada ausência de atualizações usando consultas do sistema\n4. Documentado potencial de exploração de patches ausentes",
    Impact = "Os patches ausentes expõem os sistemas a:\n- Execução remota de código\n- Escalação de privilégios\n- Ataques de ransomware\n- Roubo de dados\n- Comprometimento do sistema",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Implementar atualizações de segurança ausentes\n2. Implementar gerenciamento de patches\n3. Varredura regular de vulnerabilidades\n4. Documentar exceções\n5. Implementar controles compensatórios\n6. Monitorar conformidade de patches",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1068",
    MitreTechniques = "T1068 - Exploitation for Privilege Escalation",
};

public static Vuln UnsecuredShares => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Compartilhamentos de Rede Não Seguros",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Foram descobertos múltiplos compartilhamentos de rede com permissões fracas ou mal configuradas, permitindo acesso não autorizado a dados sensíveis. Isso inclui compartilhamentos administrativos e recursos criados por usuários com permissões excessivas.",
    ProofOfConcept = "1. Enumerados compartilhamentos de rede usando PowerView\n2. Identificados compartilhamentos com permissões fracas\n3. Acessado dados sensíveis sem autenticação\n4. Documentadas permissões excessivas em compartilhamentos",
    Impact = "Os compartilhamentos não seguros permitem:\n- Acesso não autorizado a dados\n- Divulgação de informações\n- Roubo de dados\n- Propagação de malware\n- Coleta de credenciais de arquivos",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Auditar permissões de compartilhamentos\n2. Remover compartilhamentos desnecessários\n3. Implementar privilégio mínimo\n4. Revisões regulares de permissões\n5. Monitorar acesso a compartilhamentos\n6. Documentar compartilhamentos necessários",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1039",
    MitreTechniques = "T1039 - Data from Network Shared Drive",
};

public static Vuln WinRMMisconfiguration => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configuração Incorreta do Windows Remote Management",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O Windows Remote Management (WinRM) está mal configurado em múltiplos sistemas, permitindo conexões não criptografadas e usando métodos de autenticação fracos. O serviço também é acessível a partir de segmentos de rede não autorizados.",
    ProofOfConcept = "1. Descoberto WinRM habilitado usando varredura de portas\n2. Identificada configuração de autenticação fraca\n3. Conexão bem-sucedida usando autenticação básica\n4. Demonstrada execução de comandos sobre canal não criptografado",
    Impact = "A configuração incorreta do WinRM permite:\n- Execução remota de comandos\n- Roubo de credenciais\n- Movimento lateral\n- Comprometimento do sistema\n- Administração não autorizada do sistema",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Habilitar HTTPS para WinRM\n2. Configurar autenticação Kerberos\n3. Implementar segmentação de rede\n4. Restringir acesso WinRM\n5. Habilitar criptografia de mensagens\n6. Monitorar conexões WinRM",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1021",
    MitreTechniques = "T1021 - Remote Services",
};

public static Vuln PrintSpoolerVulnerable => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades do Serviço de Spooler de Impressão",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "Multiple",
    Description = "O serviço de Spooler de Impressão está executando em sistemas que não requerem capacidades de impressão. O serviço contém múltiplas vulnerabilidades que poderiam permitir escalação de privilégios e execução remota de código.",
    ProofOfConcept = "1. Enumerados sistemas executando Spooler de Impressão\n2. Verificado serviço executando em controladores de domínio\n3. Testadas vulnerabilidades conhecidas\n4. Demonstrado potencial de escalação de privilégios",
    Impact = "O Spooler de Impressão vulnerável permite:\n- Escalação de privilégios local\n- Execução remota de código\n- Comprometimento do controlador de domínio\n- Escalação de acesso ao sistema\n- Ataques a toda a rede",
    CVSS3 = 9.0,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H",
    Remediation = "1. Desabilitar Spooler de Impressão onde não necessário\n2. Aplicar atualizações de segurança\n3. Restringir instalações de impressoras\n4. Monitorar atividade do Spooler de Impressão\n5. Implementar isolamento de impressoras\n6. Auditorias regulares do serviço",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1068",
    MitreTechniques = "T1068 - Exploitation for Privilege Escalation",
};
public static Vuln CachedDomainCredentials => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Credenciais de Domínio Armazenadas em Cache Excessivas",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os sistemas estão configurados para armazenar em cache um número excessivo de credenciais de login de domínio. Esta configuração retém hashes de credenciais localmente, aumentando o risco de roubo de credenciais e ataques offline.",
    ProofOfConcept = "1. Verificada configuração de credenciais em cache\n2. Verificado número de logins em cache\n3. Extraídos dados de credenciais em cache\n4. Demonstrado potencial de descriptografia de hash offline",
    Impact = "O armazenamento excessivo de credenciais permite:\n- Ataques offline a credenciais\n- Extração de hashes de senhas\n- Persistência de acesso não autorizado\n- Roubo de credenciais após mudanças no domínio\n- Oportunidades de movimento lateral",
    CVSS3 = 7.4,
    CVSSVector = "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Reduzir limite de credenciais em cache\n2. Implementar política segura de credenciais\n3. Monitoramento regular do sistema\n4. Limpar credenciais em cache existentes\n5. Habilitar credential guard onde possível",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1003",
    MitreTechniques = "T1003 - OS Credential Dumping",
};

public static Vuln BitLockerMisconfiguration => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Problemas de Configuração do BitLocker",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O BitLocker está mal configurado em múltiplos sistemas. Os problemas incluem validação TPM desabilitada, requisitos fracos de PIN e chaves de recuperação armazenadas no Active Directory sem controles de acesso adequados.",
    ProofOfConcept = "1. Revisadas configurações do BitLocker\n2. Identificados sistemas sem validação TPM\n3. Encontradas chaves de recuperação acessíveis no AD\n4. Demonstrado potencial de bypass de PIN fraco",
    Impact = "As configurações incorretas do BitLocker permitem:\n- Acesso não autorizado a dados\n- Bypass de criptografia de unidade\n- Comprometimento de chave de recuperação\n- Roubo de dados de dispositivos perdidos/roubados\n- Evasão de controles de segurança",
    CVSS3 = 7.7,
    CVSSVector = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:C/C:H/I:N/A:N",
    Remediation = "1. Habilitar validação TPM\n2. Fortalecer requisitos de PIN\n3. Proteger armazenamento de chaves de recuperação\n4. Auditorias regulares de configuração\n5. Monitorar estado do BitLocker\n6. Implementar procedimentos de recuperação",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1552",
    MitreTechniques = "T1552 - Unsecured Credentials",
};

public static Vuln WSUSMisconfiguration => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configuração Incorreta de Fonte WSUS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O Windows Server Update Services (WSUS) está mal configurado, usando conexões HTTP não criptografadas para entrega de atualizações e carece de validação apropriada de assinatura. Esta configuração permite potenciais ataques man-in-the-middle e injeção de atualizações maliciosas.",
    ProofOfConcept = "1. Identificado WSUS usando HTTP\n2. Verificada falta de validação de atualizações\n3. Demonstrado potencial de interceptação de atualizações\n4. Documentada entrega vulnerável de atualizações",
    Impact = "A configuração incorreta do WSUS permite:\n- Injeção de atualizações maliciosas\n- Execução de código via atualizações falsas\n- Comprometimento de toda a rede\n- Manipulação do sistema\n- Alteração de atualizações de segurança",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Habilitar HTTPS para WSUS\n2. Implementar validação de atualizações\n3. Proteger fonte de atualizações\n4. Manutenção regular do WSUS\n5. Monitorar implantação de atualizações\n6. Implementar assinatura de atualizações",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1072",
    MitreTechniques = "T1072 - Software Deployment Tools",
};

public static Vuln IPv6SecurityIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Bypass de Controles de Segurança IPv6",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O IPv6 está habilitado mas não está adequadamente protegido na rede. Os controles de segurança focados em IPv4 podem ser evadidos usando IPv6, permitindo acesso não autorizado e ataques potenciais através de túneis IPv6.",
    ProofOfConcept = "1. Confirmado IPv6 habilitado na rede\n2. Demonstrado bypass de túnel IPv6\n3. Realizado spoofing DHCPv6\n4. Alcançado acesso à rede através de IPv6 quando IPv4 estava bloqueado",
    Impact = "O IPv6 não protegido permite:\n- Bypass de controles de segurança\n- Acesso não autorizado à rede\n- Canais encobertos de comunicação\n- Evasão de descoberta de rede\n- Sequestro de DNS via IPv6",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Desabilitar IPv6 se não necessário\n2. Implementar controles de segurança IPv6\n3. Configurar firewalls IPv6\n4. Monitorar tráfego IPv6\n5. Bloquear túneis IPv6\n6. Auditorias regulares de rede",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1046",
    MitreTechniques = "T1046 - Network Service Discovery",
};
public static Vuln PowerShellLoggingGaps => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Registro Insuficiente de PowerShell",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O registro de PowerShell não está configurado corretamente nos sistemas do domínio. O registro de blocos de script, registro de módulos e transcrição estão desabilitados, permitindo que os atacantes executem comandos PowerShell maliciosos sem detecção.",
    ProofOfConcept = "1. Verificada configuração de registro do PowerShell\n2. Executados comandos de teste sem registro\n3. Demonstradas técnicas de bypass de registro\n4. Confirmada ausência de registro de blocos de script",
    Impact = "O registro insuficiente permite:\n- Execução maliciosa sem detecção\n- Roubo de credenciais\n- Atividades pós-exploração\n- Evasão de defesas\n- Resposta limitada a incidentes",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "1. Habilitar registro de blocos de script\n2. Configurar registro de módulos\n3. Habilitar transcrição do PowerShell\n4. Implementar centralização de registros\n5. Revisão regular de registros\n6. Implementar modo de linguagem restrita do PowerShell",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1562",
    MitreTechniques = "T1562 - Impair Defenses",
};

public static Vuln DnsAdminsAbuse => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Abuso de Privilégios do Grupo DnsAdmins",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O grupo DnsAdmins é vulnerável à escalação de privilégios através do carregamento de arquivos DLL arbitrários. Os membros deste grupo podem aproveitar a configuração do servidor DNS para obter privilégios de administrador de domínio.",
    ProofOfConcept = "1. Identificados membros do grupo DnsAdmins\n2. Confirmada capacidade de carregamento de DLL\n3. Criada DLL de prova de conceito\n4. Demonstrada rota potencial de escalação de privilégios",
    Impact = "O abuso de DnsAdmins permite:\n- Escalação de privilégios para DA\n- Comprometimento do domínio\n- Acesso persistente\n- Controle de infraestrutura DNS\n- Execução de código em servidores DNS",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar membros do DnsAdmins\n2. Remover membros desnecessários\n3. Monitorar alterações de configuração DNS\n4. Implementar privilégio mínimo\n5. Revisões regulares de permissões\n6. Habilitar auditoria aprimorada",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};

public static Vuln ExchangeMisconfiguration => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configurações Incorretas de Segurança no Exchange Server",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os servidores Exchange têm múltiplas configurações incorretas de segurança incluindo permissões excessivas, configurações obsoletas de SSL/TLS e configurações vulneráveis de autenticação. Estes problemas poderiam permitir acesso não autorizado e escalação de privilégios.",
    ProofOfConcept = "1. Revisada configuração do Exchange\n2. Identificadas configurações vulneráveis\n3. Testadas rotas de escalação de privilégios\n4. Documentados direitos de acesso excessivos",
    Impact = "As configurações incorretas do Exchange permitem:\n- Escalação de privilégios\n- Acesso a e-mail\n- Comprometimento de administrador de domínio\n- Roubo de dados\n- Acesso persistente",
    CVSS3 = 9.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Revisar permissões do Exchange\n2. Atualizar configuração SSL/TLS\n3. Implementar endurecimento de segurança\n4. Atualizações regulares de segurança\n5. Habilitar registro e monitoramento\n6. Configurar segurança de autenticação",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1505",
    MitreTechniques = "T1505 - Server Software Component",
};

public static Vuln BackupSystemAccess => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Acesso Não Seguro ao Sistema de Backup",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os sistemas de backup e suas contas de serviço associadas têm privilégios excessivos e controles de acesso inadequados. Isso inclui privilégios de backup de domínio e acesso a backups de sistemas críticos sem autenticação adequada.",
    ProofOfConcept = "1. Identificadas contas de serviço de backup\n2. Mapeado acesso ao sistema de backup\n3. Recuperados dados sensíveis de backup\n4. Demonstrado potencial de abuso de privilégios",
    Impact = "O acesso ao sistema de backup permite:\n- Exposição de dados sensíveis\n- Acesso a credenciais de domínio\n- Extração de estado do sistema\n- Escalação de privilégios\n- Comprometimento completo do domínio",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar acesso ao sistema de backup\n2. Implementar privilégio mínimo\n3. Proteger armazenamento de backups\n4. Habilitar criptografia\n5. Revisões regulares de acesso\n6. Monitorar operações de backup",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1003",
    MitreTechniques = "T1003 - OS Credential Dumping",
};
public static Vuln CertificateTemplateVulns => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Modelos de Certificados Vulneráveis",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os Serviços de Certificados do Active Directory (AD CS) contêm modelos de certificados mal configurados que permitem a escalação de privilégios. Os modelos têm requisitos fracos de inscrição e permitem que os solicitantes especifiquem Nomes Alternativos do Sujeito.",
    ProofOfConcept = "1. Analisados modelos de certificados\n2. Identificadas configurações vulneráveis\n3. Demonstrado abuso de modelos\n4. Criados certificados maliciosos",
    Impact = "As vulnerabilidades de modelos permitem:\n- Escalação de privilégios do domínio\n- Bypass de autenticação\n- Mecanismos de persistência\n- Falsificação de certificados\n- Comprometimento de domínio",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Revisar permissões de modelos\n2. Eliminar modelos vulneráveis\n3. Configurar restrições de inscrição\n4. Habilitar auditoria apropriada\n5. Monitorar solicitações de certificados\n6. Documentar linhas base seguras",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1649",
    MitreTechniques = "T1649 - Steal or Forge Authentication Certificates",
};

public static Vuln SQLServerMisconfigurations => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configurações Incorretas do SQL Server",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As instâncias do SQL Server têm múltiplas configurações incorretas de segurança incluindo autenticação fraca, privilégios excessivos e recursos potencialmente perigosos habilitados. XP_CMDSHELL e outros procedimentos arriscados estão habilitados.",
    ProofOfConcept = "1. Mapeadas instâncias do SQL Server\n2. Identificadas configurações fracas\n3. Demonstrada execução de comandos\n4. Acessado bases de dados sensíveis com credenciais padrão",
    Impact = "As configurações incorretas do SQL permitem:\n- Execução de comandos\n- Vazamento de dados\n- Escalação de privilégios\n- Movimento lateral\n- Bypass de autenticação",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Desabilitar recursos desnecessários\n2. Revisar configurações de autenticação\n3. Implementar privilégio mínimo\n4. Habilitar registro de auditoria\n5. Revisões regulares de segurança\n6. Atualizar configurações do SQL Server",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1505",
    MitreTechniques = "T1505 - Server Software Component",
};

public static Vuln RDPSecurityIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Problemas de Segurança do Protocolo de Área de Trabalho Remota",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O Protocolo de Área de Trabalho Remota (RDP) está configurado com ajustes de segurança fracos incluindo NLA desabilitado, criptografia fraca e acesso sem restrições de segmentos de rede não autorizados. Múltiplos sistemas aceitam conexões usando versões obsoletas do protocolo.",
    ProofOfConcept = "1. Escaneados serviços RDP\n2. Identificadas configurações fracas\n3. Testados downgrades de protocolo\n4. Demonstrados bypasses de autenticação",
    Impact = "As vulnerabilidades do RDP permitem:\n- Acesso não autorizado\n- Coleta de credenciais\n- Sequestro de sessão\n- Comprometimento do sistema\n- Reconhecimento de rede",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
    Remediation = "1. Habilitar Autenticação de Nível de Rede\n2. Restringir acesso RDP\n3. Implementar criptografia forte\n4. Configurar segurança de sessão\n5. Monitorar conexões RDP\n6. Revisões regulares de configuração",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1021",
    MitreTechniques = "T1021 - Remote Services",
};

public static Vuln ExcessiveUserRights => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Atribuição Excessiva de Direitos de Usuário",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Múltiplos usuários e grupos receberam direitos excessivos através de políticas de Atribuição de Direitos de Usuário. Privilégios críticos como 'Depurar programas', 'Carregar drivers' e 'Tomar posse' estão atribuídos a usuários não administrativos.",
    ProofOfConcept = "1. Enumeradas atribuições de direitos de usuário\n2. Identificados privilégios excessivos\n3. Demonstrado abuso de privilégios\n4. Mapeadas rotas de escalação de privilégios",
    Impact = "Os direitos excessivos permitem:\n- Escalação de privilégios\n- Manipulação do sistema\n- Bypass de segurança\n- Acesso persistente\n- Movimento lateral",
    CVSS3 = 8.4,
    CVSSVector = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar atribuições de direitos de usuário\n2. Remover privilégios desnecessários\n3. Implementar privilégio mínimo\n4. Revisões regulares de permissões\n5. Monitorar uso de privilégios\n6. Documentar direitos necessários",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};
public static Vuln ShadowCopyAbuse => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Abuso do Serviço de Cópia de Volume",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O Serviço de Cópia de Volume (VSS) está configurado com permissões fracas permitindo que usuários não privilegiados criem e acessem cópias de volume. Isso pode ser abusado para acessar arquivos restritos e extrair dados sensíveis.",
    ProofOfConcept = "1. Verificadas permissões do VSS\n2. Criadas cópias de volume não autorizadas\n3. Acessado arquivos restritos\n4. Extraídos dados sensíveis de cópias",
    Impact = "O abuso do VSS permite:\n- Acesso a dados sensíveis\n- Extração de credenciais\n- Bypass de segurança\n- Acesso ao estado do sistema\n- Roubo persistente de dados",
    CVSS3 = 7.8,
    CVSSVector = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Revisar permissões do VSS\n2. Restringir criação de cópias de volume\n3. Monitorar atividades VSS\n4. Implementar controles de acesso\n5. Revisões regulares de segurança\n6. Documentar uso legítimo",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1003",
    MitreTechniques = "T1003 - OS Credential Dumping",
};

public static Vuln ServicePrincipalMisconfig => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades de Configuração de Entidades de Serviço",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As Entidades de Serviço no Azure AD/Aplicações Empresariais têm permissões excessivas e configurações incorretas de autenticação. Algumas Entidades de Serviço têm credenciais que nunca expiram e permissões delegadas que poderiam permitir escalação de privilégios.",
    ProofOfConcept = "1. Enumeradas Entidades de Serviço\n2. Identificadas contas super-privilegiadas\n3. Encontradas políticas de credenciais expiradas\n4. Mapeadas rotas potenciais de escalação de privilégios",
    Impact = "As Entidades de Serviço mal configuradas permitem:\n- Escalação de privilégios\n- Acesso não autorizado a recursos\n- Acesso persistente de backdoor\n- Ataques entre inquilinos\n- Personificação de aplicações",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar permissões de Entidades de Serviço\n2. Implementar rotação de credenciais\n3. Remover permissões desnecessárias\n4. Habilitar monitoramento\n5. Revisões regulares de acesso\n6. Documentar permissões necessárias",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};

public static Vuln NTPServerIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Problemas de Segurança do Servidor NTP",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os servidores de Protocolo de Tempo de Rede (NTP) estão mal configurados, permitindo ataques de manipulação de tempo. Os servidores aceitam solicitações de qualquer fonte e carecem de autenticação adequada, permitindo potenciais ataques Kerberos através da manipulação do tempo.",
    ProofOfConcept = "1. Escaneados serviços NTP\n2. Testadas configurações NTP\n3. Demonstrada manipulação de tempo\n4. Mostrado potencial para ataques de golden ticket",
    Impact = "As vulnerabilidades NTP permitem:\n- Ataques de sincronização de tempo\n- Bypass de autenticação Kerberos\n- Extensão de vida útil de golden ticket\n- Inconsistências em logs\n- Bypass de controles de segurança",
    CVSS3 = 8.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Restringir fontes NTP\n2. Habilitar autenticação NTP\n3. Configurar fontes de tempo apropriadas\n4. Monitorar sincronização de tempo\n5. Revisões regulares de configuração\n6. Documentar infraestrutura NTP",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1557",
    MitreTechniques = "T1557 - Man-in-the-Middle",
};

public static Vuln LinkedServerVulns => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades de Servidores Vinculados MSSQL",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As configurações de servidores vinculados do SQL Server permitem acesso não autorizado e escalação de privilégios entre servidores de banco de dados. As credenciais são armazenadas de forma insegura e são concedidas permissões excessivas através dos vínculos.",
    ProofOfConcept = "1. Enumerados servidores vinculados\n2. Identificadas configurações fracas\n3. Demonstrada escalação de privilégios\n4. Mapeadas rotas de ataque entre servidores",
    Impact = "As vulnerabilidades de servidores vinculados permitem:\n- Movimento lateral\n- Escalação de privilégios\n- Exfiltração de dados\n- Execução de comandos\n- Ataques entre bancos de dados",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar configurações de servidores vinculados\n2. Remover vínculos desnecessários\n3. Implementar privilégio mínimo\n4. Proteger armazenamento de credenciais\n5. Monitorar uso de vínculos\n6. Revisões regulares de segurança",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1505",
    MitreTechniques = "T1505 - Server Software Component",
};
public static Vuln DefenderExclusions => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Exclusões Excessivas do Windows Defender",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O Windows Defender foi configurado com exclusões excessivas em múltiplos sistemas. Caminhos e processos críticos estão excluídos da varredura, criando potenciais pontos cegos para a execução de malware.",
    ProofOfConcept = "1. Enumeradas exclusões do Defender\n2. Mapeados caminhos excluídos\n3. Demonstrada execução de malware\n4. Validado bypass de varredura",
    Impact = "As exclusões do Defender permitem:\n- Execução de malware\n- Evasão de defesas\n- Acesso persistente\n- Implantação de ferramentas de ataque\n- Bypass de controles de segurança",
    CVSS3 = 7.8,
    CVSSVector = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar exclusões do Defender\n2. Remover exclusões desnecessárias\n3. Documentar exceções necessárias\n4. Implementar controles compensatórios\n5. Monitorar caminhos excluídos\n6. Revisões regulares de configuração",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1562",
    MitreTechniques = "T1562 - Impair Defenses",
};

public static Vuln DomainTrustIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configuração Insegura de Confiança de Domínio",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As confianças de domínio estão configuradas com ajustes de segurança fracos, incluindo confianças bidirecionais onde unidirecionais seriam suficientes, e filtragem SID desabilitada em confianças externas. As confianças de floresta carecem de controles de segurança adequados.",
    ProofOfConcept = "1. Mapeadas relações de confiança de domínio\n2. Identificados ajustes fracos de confiança\n3. Demonstrado abuso de confiança\n4. Mapeadas rotas de escalação de privilégios",
    Impact = "As vulnerabilidades de confiança permitem:\n- Abuso de relações de confiança\n- Ataques entre domínios\n- Escalação de privilégios\n- Comprometimento de floresta\n- Acesso não autorizado a recursos",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Auditar relações de confiança\n2. Habilitar filtragem SID\n3. Remover confianças desnecessárias\n4. Configurar autenticação seletiva\n5. Monitorar atividade de confiança\n6. Documentar confianças necessárias",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1482",
    MitreTechniques = "T1482 - Domain Trust Discovery",
};

public static Vuln HyperVSecurity => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades de Segurança em Host Hyper-V",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os servidores host Hyper-V têm múltiplas configurações incorretas de segurança incluindo acesso administrativo excessivo, isolamento de rede fraco e endurecimento inadequado do host. As interfaces de administração de máquinas virtuais são acessíveis a partir de redes não autorizadas.",
    ProofOfConcept = "1. Enumeradas permissões do Hyper-V\n2. Identificadas brechas no isolamento de rede\n3. Acessado interfaces de administração\n4. Demonstrados potenciais escapes de VM",
    Impact = "As vulnerabilidades do Hyper-V permitem:\n- Comprometimento de máquinas virtuais\n- Acesso ao sistema host\n- Bypass de isolamento de rede\n- Controle de infraestrutura\n- Ataques entre VMs",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Implementar endurecimento do host\n2. Configurar isolamento de rede\n3. Restringir acesso de administração\n4. Habilitar inicialização segura\n5. Revisões regulares de segurança\n6. Monitorar atividades do host",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1578",
    MitreTechniques = "T1578 - Modify Cloud Compute Infrastructure",
};

public static Vuln WSUSTargeting => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configurações Incorretas de Direcionamento WSUS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O direcionamento do Windows Server Update Services (WSUS) está mal configurado, permitindo que os sistemas recebam atualizações inadequadas ou percam patches críticos. Os grupos de computadores estão mal configurados e as aprovações automáticas são excessivamente permissivas.",
    ProofOfConcept = "1. Analisadas regras de direcionamento WSUS\n2. Identificados grupos mal configurados\n3. Demonstrado bypass de atualização\n4. Documentadas inconsistências de patches",
    Impact = "Os problemas de direcionamento WSUS permitem:\n- Perda de atualizações de segurança\n- Patching inconsistente\n- Instabilidade do sistema\n- Bypass de controles de segurança\n- Manipulação de atualizações",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "1. Revisar regras de direcionamento\n2. Configurar grupos apropriadamente\n3. Implementar fluxo de trabalho de aprovação\n4. Monitorar conformidade de atualizações\n5. Auditorias regulares de configuração\n6. Documentar políticas de direcionamento",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1072",
    MitreTechniques = "T1072 - Software Deployment Tools",
};
public static Vuln ADFSSecurityIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configurações Incorretas de Segurança no ADFS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os Serviços de Federação do Active Directory (ADFS) têm múltiplas configurações incorretas de segurança incluindo certificados fracos de assinatura de tokens, confianças de parte confiável excessivas e protocolos de autenticação inseguros habilitados.",
    ProofOfConcept = "1. Revisada configuração do ADFS\n2. Identificadas configurações fracas\n3. Testada assinatura de tokens\n4. Demonstrada potencial manipulação de tokens",
    Impact = "As vulnerabilidades do ADFS permitem:\n- Falsificação de tokens\n- Bypass de autenticação\n- Abuso de confiança de federação\n- Acesso não autorizado\n- Roubo de identidade",
    CVSS3 = 9.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Revisar configurações do ADFS\n2. Fortalecer segurança de tokens\n3. Auditar partes confiáveis\n4. Habilitar protocolos seguros\n5. Monitorar atividade de federação\n6. Revisões regulares de segurança",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1556",
    MitreTechniques = "T1556 - Modify Authentication Process",
};

public static Vuln ConstrainedDelegation => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Abuso de Delegação Restrita",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Múltiplas contas de serviço estão configuradas com delegação restrita para serviços sensíveis. Esta configuração de delegação pode ser abusada para escalação de privilégios e acesso não autorizado a serviços.",
    ProofOfConcept = "1. Enumeradas configurações de delegação\n2. Identificados serviços vulneráveis\n3. Demonstrado abuso de delegação\n4. Criada rota de escalação de privilégios",
    Impact = "O abuso de delegação permite:\n- Personificação de serviço\n- Escalação de privilégios\n- Movimento lateral\n- Acesso não autorizado\n- Comprometimento de conta de serviço",
    CVSS3 = 8.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Revisar configurações de delegação\n2. Remover delegações desnecessárias\n3. Implementar privilégio mínimo\n4. Monitorar uso de delegação\n5. Revisões regulares de configuração\n6. Documentar delegações necessárias",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1558",
    MitreTechniques = "T1558 - Steal or Forge Kerberos Tickets",
};

public static Vuln DNSZoneTransfer => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades de Transferência de Zona DNS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os servidores DNS estão configurados para permitir transferências de zona para servidores não autorizados. As restrições de transferência de zona não estão configuradas adequadamente, permitindo a potencial enumeração da estrutura de rede interna.",
    ProofOfConcept = "1. Testadas configurações de transferência de zona\n2. Transferidas zonas com sucesso\n3. Mapeada infraestrutura interna\n4. Documentada informação exposta",
    Impact = "Os problemas de transferência de zona permitem:\n- Enumeração de rede\n- Mapeamento interno\n- Identificação de alvos\n- Planejamento de ataques\n- Divulgação de informação",
    CVSS3 = 7.5,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    Remediation = "1. Restringir transferências de zona\n2. Configurar ACLs de transferência\n3. Habilitar criptografia de transferência\n4. Monitorar consultas DNS\n5. Auditorias regulares de DNS\n6. Documentar transferências autorizadas",
    RemediationComplexity = RemediationComplexity.Low,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1590",
    MitreTechniques = "T1590 - Gather Victim Network Information",
};

public static Vuln DFSSharePermissions => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades de Permissões em Compartilhamentos DFS",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os compartilhamentos do Sistema de Arquivos Distribuído (DFS) têm permissões mal configuradas permitindo acesso não autorizado a dados sensíveis. As permissões de compartilhamento e NTFS são inconsistentes, e o acesso privilegiado não está restrito adequadamente.",
    ProofOfConcept = "1. Enumeradas estruturas DFS\n2. Mapeadas permissões de compartilhamento\n3. Identificadas inconsistências de acesso\n4. Demonstrado acesso não autorizado",
    Impact = "Os problemas de permissões DFS permitem:\n- Acesso não autorizado a dados\n- Divulgação de informação sensível\n- Manipulação de dados\n- Movimento lateral\n- Escalação de privilégios",
    CVSS3 = 8.2,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
    Remediation = "1. Auditar permissões DFS\n2. Alinhar permissões de compartilhamento/NTFS\n3. Remover acesso excessivo\n4. Implementar monitoramento de acesso\n5. Revisões regulares de permissões\n6. Documentar acesso necessário",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1039",
    MitreTechniques = "T1039 - Data from Network Shared Drive",
};
public static Vuln NetworkDeviceMisconfig => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Configurações Incorretas de Segurança em Dispositivos de Rede",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "Os dispositivos de rede (switches, roteadores, firewalls) têm múltiplas configurações incorretas de segurança incluindo controles de acesso fracos, protocolos de administração inseguros e configurações inadequadas de registro.",
    ProofOfConcept = "1. Escaneados dispositivos de rede\n2. Identificados protocolos inseguros\n3. Encontrados controles de acesso fracos\n4. Demonstrado acesso não autorizado",
    Impact = "As configurações incorretas de dispositivos permitem:\n- Administração não autorizada\n- Comprometimento do controle de rede\n- Interceptação de tráfego\n- Bypass de segurança\n- Manipulação de infraestrutura",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Implementar protocolos seguros\n2. Configurar controles de acesso\n3. Habilitar registro apropriado\n4. Backups regulares de configuração\n5. Monitorar acesso a dispositivos\n6. Documentar linhas base seguras",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1200",
    MitreTechniques = "T1200 - Hardware Additions",
};

public static Vuln AzureADConnectIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Problemas de Segurança do Azure AD Connect",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "A configuração do Azure AD Connect contém vulnerabilidades de segurança incluindo versões desatualizadas, permissões fracas de conta de serviço e armazenamento inseguro de credenciais. As configurações de sincronização potencialmente expõem dados sensíveis.",
    ProofOfConcept = "1. Revisada configuração do AAD Connect\n2. Identificados problemas de privilégios\n3. Encontradas exposições de credenciais\n4. Mapeadas rotas potenciais de ataque",
    Impact = "Os problemas do AAD Connect permitem:\n- Roubo de credenciais\n- Abuso de sincronização de diretório\n- Comprometimento de identidade híbrida\n- Escalação de privilégios\n- Acesso a recursos na nuvem",
    CVSS3 = 9.1,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:H",
    Remediation = "1. Atualizar AAD Connect\n2. Proteger contas de serviço\n3. Revisar configurações de sincronização\n4. Monitorar atividades de sincronização\n5. Revisões regulares de configuração\n6. Implementar privilégio mínimo",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1078",
    MitreTechniques = "T1078 - Valid Accounts",
};

public static Vuln SCCMSecurityIssues => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades de Segurança no SCCM",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.Critical,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "O Microsoft System Center Configuration Manager (SCCM) contém múltiplas configurações incorretas de segurança incluindo permissões excessivas de cliente, pontos de distribuição não seguros e configurações vulneráveis de implantação de software.",
    ProofOfConcept = "1. Analisados permissões do SCCM\n2. Identificadas configurações vulneráveis\n3. Testado abuso de implantação\n4. Demonstrada escalação de privilégios",
    Impact = "As vulnerabilidades do SCCM permitem:\n- Implantação não autorizada de software\n- Comprometimento do sistema\n- Distribuição de malware\n- Ataques a toda a rede\n- Manipulação de configuração",
    CVSS3 = 9.8,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    Remediation = "1. Revisar permissões do SCCM\n2. Proteger pontos de distribuição\n3. Implementar controles de implantação\n4. Monitorar atividades de cliente\n5. Auditorias regulares de segurança\n6. Documentar linhas base seguras",
    RemediationComplexity = RemediationComplexity.High,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "Critical",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1072",
    MitreTechniques = "T1072 - Software Deployment Tools",
};

public static Vuln RemoteAccessPolicy => new Vuln
{
    Template = true,
    Language = Language.English,
    Name = "Vulnerabilidades em Política de Acesso Remoto",
    CreatedDate = DateTime.UtcNow,
    ModifiedDate = DateTime.UtcNow,
    Risk = VulnRisk.High,
    Status = VulnStatus.Open,
    cve = "N/A",
    Description = "As políticas de acesso remoto têm fraquezas de segurança incluindo requisitos fracos de autenticação, falta de autenticação multifator e restrições de acesso insuficientes. As políticas de VPN e área de trabalho remota não estão adequadamente fortalecidas.",
    ProofOfConcept = "1. Revisadas políticas de acesso\n2. Testado bypass de autenticação\n3. Identificadas brechas em políticas\n4. Demonstrado acesso não autorizado",
    Impact = "As fraquezas em políticas permitem:\n- Acesso remoto não autorizado\n- Bypass de autenticação\n- Evasão de políticas\n- Infiltração de rede\n- Roubo de credenciais",
    CVSS3 = 8.6,
    CVSSVector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
    Remediation = "1. Implementar MFA\n2. Fortalecer políticas de acesso\n3. Configurar restrições de acesso\n4. Habilitar registro apropriado\n5. Revisões regulares de políticas\n6. Monitorar acesso remoto",
    RemediationComplexity = RemediationComplexity.Medium,
    RemediationPriority = RemediationPriority.High,
    JiraCreated = false,
    OWASPRisk = "High",
    OWASPImpact = "Severe",
    OWASPLikehood = "High",
    OWASPVector = "",
    MitreValues = "T1133",
    MitreTechniques = "T1133 - External Remote Services",
};
}