//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cervantes.Web.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MudResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MudResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Cervantes.Web.Localization.MudResources", typeof(MudResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MudDataGrid_AddFilter {
            get {
                return ResourceManager.GetString("MudDataGrid_AddFilter", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Apply {
            get {
                return ResourceManager.GetString("MudDataGrid_Apply", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Cancel {
            get {
                return ResourceManager.GetString("MudDataGrid_Cancel", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Clear {
            get {
                return ResourceManager.GetString("MudDataGrid_Clear", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_CollapseAllGroups {
            get {
                return ResourceManager.GetString("MudDataGrid_CollapseAllGroups", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Column {
            get {
                return ResourceManager.GetString("MudDataGrid_Column", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Columns {
            get {
                return ResourceManager.GetString("MudDataGrid_Columns", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Contains {
            get {
                return ResourceManager.GetString("MudDataGrid_Contains", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_EndsWith {
            get {
                return ResourceManager.GetString("MudDataGrid_EndsWith", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Equals {
            get {
                return ResourceManager.GetString("MudDataGrid_Equals", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_ExpandAllGroups {
            get {
                return ResourceManager.GetString("MudDataGrid_ExpandAllGroups", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_False {
            get {
                return ResourceManager.GetString("MudDataGrid_False", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Filter {
            get {
                return ResourceManager.GetString("MudDataGrid_Filter", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_FilterValue {
            get {
                return ResourceManager.GetString("MudDataGrid_FilterValue", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Group {
            get {
                return ResourceManager.GetString("MudDataGrid_Group", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Hide {
            get {
                return ResourceManager.GetString("MudDataGrid_Hide", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_HideAll {
            get {
                return ResourceManager.GetString("MudDataGrid_HideAll", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Is {
            get {
                return ResourceManager.GetString("MudDataGrid_Is", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsAfter {
            get {
                return ResourceManager.GetString("MudDataGrid_IsAfter", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsBefore {
            get {
                return ResourceManager.GetString("MudDataGrid_IsBefore", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsEmpty {
            get {
                return ResourceManager.GetString("MudDataGrid_IsEmpty", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsNot {
            get {
                return ResourceManager.GetString("MudDataGrid_IsNot", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsNotEmpty {
            get {
                return ResourceManager.GetString("MudDataGrid_IsNotEmpty", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsOnOrAfter {
            get {
                return ResourceManager.GetString("MudDataGrid_IsOnOrAfter", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_IsOnOrBefore {
            get {
                return ResourceManager.GetString("MudDataGrid_IsOnOrBefore", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_MoveDown {
            get {
                return ResourceManager.GetString("MudDataGrid_MoveDown", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_MoveUp {
            get {
                return ResourceManager.GetString("MudDataGrid_MoveUp", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_NotContains {
            get {
                return ResourceManager.GetString("MudDataGrid_NotContains", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_NotEquals {
            get {
                return ResourceManager.GetString("MudDataGrid_NotEquals", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Operator {
            get {
                return ResourceManager.GetString("MudDataGrid_Operator", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_RefreshData {
            get {
                return ResourceManager.GetString("MudDataGrid_RefreshData", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Save {
            get {
                return ResourceManager.GetString("MudDataGrid_Save", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_ShowAll {
            get {
                return ResourceManager.GetString("MudDataGrid_ShowAll", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Sort {
            get {
                return ResourceManager.GetString("MudDataGrid_Sort", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_StartsWith {
            get {
                return ResourceManager.GetString("MudDataGrid_StartsWith", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_True {
            get {
                return ResourceManager.GetString("MudDataGrid_True", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Ungroup {
            get {
                return ResourceManager.GetString("MudDataGrid_Ungroup", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Unsort {
            get {
                return ResourceManager.GetString("MudDataGrid_Unsort", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Value {
            get {
                return ResourceManager.GetString("MudDataGrid_Value", resourceCulture);
            }
        }
        
        internal static string MudDataGridPager_RowsPerPage {
            get {
                return ResourceManager.GetString("MudDataGridPager_RowsPerPage", resourceCulture);
            }
        }
        
        internal static string MudDataGrid_Loading {
            get {
                return ResourceManager.GetString("MudDataGrid_Loading", resourceCulture);
            }
        }
        
        internal static string MudDataGridPager_AllItems {
            get {
                return ResourceManager.GetString("MudDataGridPager_AllItems", resourceCulture);
            }
        }
    }
}
