//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cervantes.Web.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Cervantes.Client.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        internal static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        internal static string workspaces {
            get {
                return ResourceManager.GetString("workspaces", resourceCulture);
            }
        }
        
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        internal static string tasks {
            get {
                return ResourceManager.GetString("tasks", resourceCulture);
            }
        }
        
        internal static string vulns {
            get {
                return ResourceManager.GetString("vulns", resourceCulture);
            }
        }
        
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        internal static string reportTemplates {
            get {
                return ResourceManager.GetString("reportTemplates", resourceCulture);
            }
        }
        
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        internal static string español {
            get {
                return ResourceManager.GetString("español", resourceCulture);
            }
        }
        
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        internal static string archived {
            get {
                return ResourceManager.GetString("archived", resourceCulture);
            }
        }
        
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        internal static string blackbox {
            get {
                return ResourceManager.GetString("blackbox", resourceCulture);
            }
        }
        
        internal static string graybox {
            get {
                return ResourceManager.GetString("graybox", resourceCulture);
            }
        }
        
        internal static string whitebox {
            get {
                return ResourceManager.GetString("whitebox", resourceCulture);
            }
        }
        
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        internal static string createProject {
            get {
                return ResourceManager.GetString("createProject", resourceCulture);
            }
        }
        
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        internal static string findingsId {
            get {
                return ResourceManager.GetString("findingsId", resourceCulture);
            }
        }
        
        internal static string selectClient {
            get {
                return ResourceManager.GetString("selectClient", resourceCulture);
            }
        }
        
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string projectCreated {
            get {
                return ResourceManager.GetString("projectCreated", resourceCulture);
            }
        }
        
        internal static string projectCreatedError {
            get {
                return ResourceManager.GetString("projectCreatedError", resourceCulture);
            }
        }
        
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        internal static string noFiles {
            get {
                return ResourceManager.GetString("noFiles", resourceCulture);
            }
        }
        
        internal static string uploadFile {
            get {
                return ResourceManager.GetString("uploadFile", resourceCulture);
            }
        }
        
        internal static string addAttachment {
            get {
                return ResourceManager.GetString("addAttachment", resourceCulture);
            }
        }
        
        internal static string addAttachmentError {
            get {
                return ResourceManager.GetString("addAttachmentError", resourceCulture);
            }
        }
        
        internal static string deleteAttachment {
            get {
                return ResourceManager.GetString("deleteAttachment", resourceCulture);
            }
        }
        
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        internal static string deleteMessageIntro {
            get {
                return ResourceManager.GetString("deleteMessageIntro", resourceCulture);
            }
        }
        
        internal static string attachmentDeleted {
            get {
                return ResourceManager.GetString("attachmentDeleted", resourceCulture);
            }
        }
        
        internal static string attachmentDeletedError {
            get {
                return ResourceManager.GetString("attachmentDeletedError", resourceCulture);
            }
        }
        
        internal static string targetCreated {
            get {
                return ResourceManager.GetString("targetCreated", resourceCulture);
            }
        }
        
        internal static string targetCreatedError {
            get {
                return ResourceManager.GetString("targetCreatedError", resourceCulture);
            }
        }
        
        internal static string deleteClient {
            get {
                return ResourceManager.GetString("deleteClient", resourceCulture);
            }
        }
        
        internal static string projectDeleted {
            get {
                return ResourceManager.GetString("projectDeleted", resourceCulture);
            }
        }
        
        internal static string projectDeletedError {
            get {
                return ResourceManager.GetString("projectDeletedError", resourceCulture);
            }
        }
        
        internal static string deleteMember {
            get {
                return ResourceManager.GetString("deleteMember", resourceCulture);
            }
        }
        
        internal static string memberDeleted {
            get {
                return ResourceManager.GetString("memberDeleted", resourceCulture);
            }
        }
        
        internal static string memberDeletedError {
            get {
                return ResourceManager.GetString("memberDeletedError", resourceCulture);
            }
        }
        
        internal static string deleteNote {
            get {
                return ResourceManager.GetString("deleteNote", resourceCulture);
            }
        }
        
        internal static string deletedNote {
            get {
                return ResourceManager.GetString("deletedNote", resourceCulture);
            }
        }
        
        internal static string deletedNoteError {
            get {
                return ResourceManager.GetString("deletedNoteError", resourceCulture);
            }
        }
        
        internal static string deleteTarget {
            get {
                return ResourceManager.GetString("deleteTarget", resourceCulture);
            }
        }
        
        internal static string deletedTarget {
            get {
                return ResourceManager.GetString("deletedTarget", resourceCulture);
            }
        }
        
        internal static string deletedTargetError {
            get {
                return ResourceManager.GetString("deletedTargetError", resourceCulture);
            }
        }
        
        internal static string contactName {
            get {
                return ResourceManager.GetString("contactName", resourceCulture);
            }
        }
        
        internal static string contactEmail {
            get {
                return ResourceManager.GetString("contactEmail", resourceCulture);
            }
        }
        
        internal static string contactPhone {
            get {
                return ResourceManager.GetString("contactPhone", resourceCulture);
            }
        }
        
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        internal static string projectInformation {
            get {
                return ResourceManager.GetString("projectInformation", resourceCulture);
            }
        }
        
        internal static string projectName {
            get {
                return ResourceManager.GetString("projectName", resourceCulture);
            }
        }
        
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        internal static string projectDescription {
            get {
                return ResourceManager.GetString("projectDescription", resourceCulture);
            }
        }
        
        internal static string addMember {
            get {
                return ResourceManager.GetString("addMember", resourceCulture);
            }
        }
        
        internal static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        internal static string targets {
            get {
                return ResourceManager.GetString("targets", resourceCulture);
            }
        }
        
        internal static string addTarget {
            get {
                return ResourceManager.GetString("addTarget", resourceCulture);
            }
        }
        
        internal static string assignedTo {
            get {
                return ResourceManager.GetString("assignedTo", resourceCulture);
            }
        }
        
        internal static string risk {
            get {
                return ResourceManager.GetString("risk", resourceCulture);
            }
        }
        
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        internal static string attachments {
            get {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }
        
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        internal static string uploadedBy {
            get {
                return ResourceManager.GetString("uploadedBy", resourceCulture);
            }
        }
        
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        internal static string generateReport {
            get {
                return ResourceManager.GetString("generateReport", resourceCulture);
            }
        }
        
        internal static string addAttachmentBtn {
            get {
                return ResourceManager.GetString("addAttachmentBtn", resourceCulture);
            }
        }
        
        internal static string addNoteBtn {
            get {
                return ResourceManager.GetString("addNoteBtn", resourceCulture);
            }
        }
        
        internal static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }
        
        internal static string editProject {
            get {
                return ResourceManager.GetString("editProject", resourceCulture);
            }
        }
        
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        internal static string projectEdited {
            get {
                return ResourceManager.GetString("projectEdited", resourceCulture);
            }
        }
        
        internal static string projectEditedError {
            get {
                return ResourceManager.GetString("projectEditedError", resourceCulture);
            }
        }
        
        internal static string projectDetails {
            get {
                return ResourceManager.GetString("projectDetails", resourceCulture);
            }
        }
        
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        internal static string selectMembers {
            get {
                return ResourceManager.GetString("selectMembers", resourceCulture);
            }
        }
        
        internal static string userAdded {
            get {
                return ResourceManager.GetString("userAdded", resourceCulture);
            }
        }
        
        internal static string userAddedError {
            get {
                return ResourceManager.GetString("userAddedError", resourceCulture);
            }
        }
        
        internal static string userExists {
            get {
                return ResourceManager.GetString("userExists", resourceCulture);
            }
        }
        
        internal static string noteAdded {
            get {
                return ResourceManager.GetString("noteAdded", resourceCulture);
            }
        }
        
        internal static string noteAddedError {
            get {
                return ResourceManager.GetString("noteAddedError", resourceCulture);
            }
        }
        
        internal static string editClient {
            get {
                return ResourceManager.GetString("editClient", resourceCulture);
            }
        }
        
        internal static string deleteLogo {
            get {
                return ResourceManager.GetString("deleteLogo", resourceCulture);
            }
        }
        
        internal static string clientEdited {
            get {
                return ResourceManager.GetString("clientEdited", resourceCulture);
            }
        }
        
        internal static string clientEditedError {
            get {
                return ResourceManager.GetString("clientEditedError", resourceCulture);
            }
        }
        
        internal static string logoDeleted {
            get {
                return ResourceManager.GetString("logoDeleted", resourceCulture);
            }
        }
        
        internal static string logoDeletedError {
            get {
                return ResourceManager.GetString("logoDeletedError", resourceCulture);
            }
        }
        
        internal static string createClient {
            get {
                return ResourceManager.GetString("createClient", resourceCulture);
            }
        }
        
        internal static string clientCreated {
            get {
                return ResourceManager.GetString("clientCreated", resourceCulture);
            }
        }
        
        internal static string clientCreatedError {
            get {
                return ResourceManager.GetString("clientCreatedError", resourceCulture);
            }
        }
        
        internal static string clientDeleted {
            get {
                return ResourceManager.GetString("clientDeleted", resourceCulture);
            }
        }
        
        internal static string clientDeletedError {
            get {
                return ResourceManager.GetString("clientDeletedError", resourceCulture);
            }
        }
        
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        internal static string locked {
            get {
                return ResourceManager.GetString("locked", resourceCulture);
            }
        }
        
        internal static string darkMode {
            get {
                return ResourceManager.GetString("darkMode", resourceCulture);
            }
        }
        
        internal static string mfaEnabled {
            get {
                return ResourceManager.GetString("mfaEnabled", resourceCulture);
            }
        }
        
        internal static string deleteUser {
            get {
                return ResourceManager.GetString("deleteUser", resourceCulture);
            }
        }
        
        internal static string userDeleted {
            get {
                return ResourceManager.GetString("userDeleted", resourceCulture);
            }
        }
        
        internal static string userDeletedError {
            get {
                return ResourceManager.GetString("userDeletedError", resourceCulture);
            }
        }
        
        internal static string createUser {
            get {
                return ResourceManager.GetString("createUser", resourceCulture);
            }
        }
        
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        internal static string selectRole {
            get {
                return ResourceManager.GetString("selectRole", resourceCulture);
            }
        }
        
        internal static string editUser {
            get {
                return ResourceManager.GetString("editUser", resourceCulture);
            }
        }
        
        internal static string recentProjects {
            get {
                return ResourceManager.GetString("recentProjects", resourceCulture);
            }
        }
        
        internal static string recentClients {
            get {
                return ResourceManager.GetString("recentClients", resourceCulture);
            }
        }
        
        internal static string recentVulns {
            get {
                return ResourceManager.GetString("recentVulns", resourceCulture);
            }
        }
        
        internal static string recentDocuments {
            get {
                return ResourceManager.GetString("recentDocuments", resourceCulture);
            }
        }
        
        internal static string projectStatus {
            get {
                return ResourceManager.GetString("projectStatus", resourceCulture);
            }
        }
        
        internal static string vulnStatus {
            get {
                return ResourceManager.GetString("vulnStatus", resourceCulture);
            }
        }
        
        internal static string vulnSeverity {
            get {
                return ResourceManager.GetString("vulnSeverity", resourceCulture);
            }
        }
        
        internal static string tasksStatus {
            get {
                return ResourceManager.GetString("tasksStatus", resourceCulture);
            }
        }
        
        internal static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        internal static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        internal static string critical {
            get {
                return ResourceManager.GetString("critical", resourceCulture);
            }
        }
        
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        internal static string resolved {
            get {
                return ResourceManager.GetString("resolved", resourceCulture);
            }
        }
        
        internal static string outOfScope {
            get {
                return ResourceManager.GetString("outOfScope", resourceCulture);
            }
        }
        
        internal static string accepted {
            get {
                return ResourceManager.GetString("accepted", resourceCulture);
            }
        }
        
        internal static string confirmed {
            get {
                return ResourceManager.GetString("confirmed", resourceCulture);
            }
        }
        
        internal static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        internal static string backlog {
            get {
                return ResourceManager.GetString("backlog", resourceCulture);
            }
        }
        
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        internal static string toDo {
            get {
                return ResourceManager.GetString("toDo", resourceCulture);
            }
        }
        
        internal static string inProgress {
            get {
                return ResourceManager.GetString("inProgress", resourceCulture);
            }
        }
        
        internal static string blocked {
            get {
                return ResourceManager.GetString("blocked", resourceCulture);
            }
        }
        
        internal static string passwordLengthMessage {
            get {
                return ResourceManager.GetString("passwordLengthMessage", resourceCulture);
            }
        }
        
        internal static string passwordLowercaseMessage {
            get {
                return ResourceManager.GetString("passwordLowercaseMessage", resourceCulture);
            }
        }
        
        internal static string passwordUppercaseMessage {
            get {
                return ResourceManager.GetString("passwordUppercaseMessage", resourceCulture);
            }
        }
        
        internal static string passwordNumberMessage {
            get {
                return ResourceManager.GetString("passwordNumberMessage", resourceCulture);
            }
        }
        
        internal static string passwordSpecialMessage {
            get {
                return ResourceManager.GetString("passwordSpecialMessage", resourceCulture);
            }
        }
        
        internal static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        internal static string userEdited {
            get {
                return ResourceManager.GetString("userEdited", resourceCulture);
            }
        }
        
        internal static string userEditedError {
            get {
                return ResourceManager.GetString("userEditedError", resourceCulture);
            }
        }
        
        internal static string loginDescription {
            get {
                return ResourceManager.GetString("loginDescription", resourceCulture);
            }
        }
        
        internal static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string orgSaved {
            get {
                return ResourceManager.GetString("orgSaved", resourceCulture);
            }
        }
        
        internal static string orgSavedError {
            get {
                return ResourceManager.GetString("orgSavedError", resourceCulture);
            }
        }
        
        internal static string createReportTemplate {
            get {
                return ResourceManager.GetString("createReportTemplate", resourceCulture);
            }
        }
        
        internal static string reportTemplateCreated {
            get {
                return ResourceManager.GetString("reportTemplateCreated", resourceCulture);
            }
        }
        
        internal static string reportTemplateCreatedError {
            get {
                return ResourceManager.GetString("reportTemplateCreatedError", resourceCulture);
            }
        }
        
        internal static string reportTemplate {
            get {
                return ResourceManager.GetString("reportTemplate", resourceCulture);
            }
        }
        
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        internal static string createdDate {
            get {
                return ResourceManager.GetString("createdDate", resourceCulture);
            }
        }
        
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        internal static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        internal static string backupDataMessage {
            get {
                return ResourceManager.GetString("backupDataMessage", resourceCulture);
            }
        }
        
        internal static string backupAttachmentsMessage {
            get {
                return ResourceManager.GetString("backupAttachmentsMessage", resourceCulture);
            }
        }
        
        internal static string backupSuccessfull {
            get {
                return ResourceManager.GetString("backupSuccessfull", resourceCulture);
            }
        }
        
        internal static string backupError {
            get {
                return ResourceManager.GetString("backupError", resourceCulture);
            }
        }
        
        internal static string restoreDataMessage {
            get {
                return ResourceManager.GetString("restoreDataMessage", resourceCulture);
            }
        }
        
        internal static string restoreAttachmentsMessage {
            get {
                return ResourceManager.GetString("restoreAttachmentsMessage", resourceCulture);
            }
        }
        
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        internal static string checklist {
            get {
                return ResourceManager.GetString("checklist", resourceCulture);
            }
        }
        
        internal static string dataVault {
            get {
                return ResourceManager.GetString("dataVault", resourceCulture);
            }
        }
        
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        internal static string createTask {
            get {
                return ResourceManager.GetString("createTask", resourceCulture);
            }
        }
        
        internal static string target {
            get {
                return ResourceManager.GetString("target", resourceCulture);
            }
        }
        
        internal static string selectTarget {
            get {
                return ResourceManager.GetString("selectTarget", resourceCulture);
            }
        }
        
        internal static string editTask {
            get {
                return ResourceManager.GetString("editTask", resourceCulture);
            }
        }
        
        internal static string deleteTask {
            get {
                return ResourceManager.GetString("deleteTask", resourceCulture);
            }
        }
        
        internal static string taskCreated {
            get {
                return ResourceManager.GetString("taskCreated", resourceCulture);
            }
        }
        
        internal static string taskCreatedError {
            get {
                return ResourceManager.GetString("taskCreatedError", resourceCulture);
            }
        }
        
        internal static string taskUpdated {
            get {
                return ResourceManager.GetString("taskUpdated", resourceCulture);
            }
        }
        
        internal static string taskUpdatedError {
            get {
                return ResourceManager.GetString("taskUpdatedError", resourceCulture);
            }
        }
        
        internal static string taskDeleted {
            get {
                return ResourceManager.GetString("taskDeleted", resourceCulture);
            }
        }
        
        internal static string taskDeletedError {
            get {
                return ResourceManager.GetString("taskDeletedError", resourceCulture);
            }
        }
        
        internal static string selectUser {
            get {
                return ResourceManager.GetString("selectUser", resourceCulture);
            }
        }
        
        internal static string taskDetails {
            get {
                return ResourceManager.GetString("taskDetails", resourceCulture);
            }
        }
        
        internal static string taskDescription {
            get {
                return ResourceManager.GetString("taskDescription", resourceCulture);
            }
        }
        
        internal static string targetAdded {
            get {
                return ResourceManager.GetString("targetAdded", resourceCulture);
            }
        }
        
        internal static string targetExists {
            get {
                return ResourceManager.GetString("targetExists", resourceCulture);
            }
        }
        
        internal static string targetAddedError {
            get {
                return ResourceManager.GetString("targetAddedError", resourceCulture);
            }
        }
        
        internal static string targetDeleted {
            get {
                return ResourceManager.GetString("targetDeleted", resourceCulture);
            }
        }
        
        internal static string targetDeletedError {
            get {
                return ResourceManager.GetString("targetDeletedError", resourceCulture);
            }
        }
        
        internal static string addNote {
            get {
                return ResourceManager.GetString("addNote", resourceCulture);
            }
        }
        
        internal static string noteDeleted {
            get {
                return ResourceManager.GetString("noteDeleted", resourceCulture);
            }
        }
        
        internal static string noteDeletedError {
            get {
                return ResourceManager.GetString("noteDeletedError", resourceCulture);
            }
        }
        
        internal static string editNote {
            get {
                return ResourceManager.GetString("editNote", resourceCulture);
            }
        }
        
        internal static string noteEdited {
            get {
                return ResourceManager.GetString("noteEdited", resourceCulture);
            }
        }
        
        internal static string noteEditedError {
            get {
                return ResourceManager.GetString("noteEditedError", resourceCulture);
            }
        }
        
        internal static string attachmentAdded {
            get {
                return ResourceManager.GetString("attachmentAdded", resourceCulture);
            }
        }
        
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        internal static string editTarget {
            get {
                return ResourceManager.GetString("editTarget", resourceCulture);
            }
        }
        
        internal static string targetEdited {
            get {
                return ResourceManager.GetString("targetEdited", resourceCulture);
            }
        }
        
        internal static string targetEditedError {
            get {
                return ResourceManager.GetString("targetEditedError", resourceCulture);
            }
        }
        
        internal static string targetImport {
            get {
                return ResourceManager.GetString("targetImport", resourceCulture);
            }
        }
        
        internal static string executiveSummary {
            get {
                return ResourceManager.GetString("executiveSummary", resourceCulture);
            }
        }
        
        internal static string targetImported {
            get {
                return ResourceManager.GetString("targetImported", resourceCulture);
            }
        }
        
        internal static string targetImportedError {
            get {
                return ResourceManager.GetString("targetImportedError", resourceCulture);
            }
        }
        
        internal static string createChecklist {
            get {
                return ResourceManager.GetString("createChecklist", resourceCulture);
            }
        }
        
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        internal static string issues {
            get {
                return ResourceManager.GetString("issues", resourceCulture);
            }
        }
        
        internal static string platform {
            get {
                return ResourceManager.GetString("platform", resourceCulture);
            }
        }
        
        internal static string deletedChecklist {
            get {
                return ResourceManager.GetString("deletedChecklist", resourceCulture);
            }
        }
        
        internal static string deletedChecklistError {
            get {
                return ResourceManager.GetString("deletedChecklistError", resourceCulture);
            }
        }
        
        internal static string checklistReport {
            get {
                return ResourceManager.GetString("checklistReport", resourceCulture);
            }
        }
        
        internal static string checklistReportError {
            get {
                return ResourceManager.GetString("checklistReportError", resourceCulture);
            }
        }
        
        internal static string checklistEdited {
            get {
                return ResourceManager.GetString("checklistEdited", resourceCulture);
            }
        }
        
        internal static string checklistEditedError {
            get {
                return ResourceManager.GetString("checklistEditedError", resourceCulture);
            }
        }
        
        internal static string owaspThreatAgentFactors {
            get {
                return ResourceManager.GetString("owaspThreatAgentFactors", resourceCulture);
            }
        }
        
        internal static string owaspTechnicalImpactFactors {
            get {
                return ResourceManager.GetString("owaspTechnicalImpactFactors", resourceCulture);
            }
        }
        
        internal static string owaspVulnerabilityFactors {
            get {
                return ResourceManager.GetString("owaspVulnerabilityFactors", resourceCulture);
            }
        }
        
        internal static string owaspBusinessImpactFactors {
            get {
                return ResourceManager.GetString("owaspBusinessImpactFactors", resourceCulture);
            }
        }
        
        internal static string skillLevel {
            get {
                return ResourceManager.GetString("skillLevel", resourceCulture);
            }
        }
        
        internal static string noTechnicalSkills {
            get {
                return ResourceManager.GetString("noTechnicalSkills", resourceCulture);
            }
        }
        
        internal static string securityPenetrationSkills {
            get {
                return ResourceManager.GetString("securityPenetrationSkills", resourceCulture);
            }
        }
        
        internal static string someTechnicalSkills {
            get {
                return ResourceManager.GetString("someTechnicalSkills", resourceCulture);
            }
        }
        
        internal static string advancedComputerUser {
            get {
                return ResourceManager.GetString("advancedComputerUser", resourceCulture);
            }
        }
        
        internal static string motive {
            get {
                return ResourceManager.GetString("motive", resourceCulture);
            }
        }
        
        internal static string lowReward {
            get {
                return ResourceManager.GetString("lowReward", resourceCulture);
            }
        }
        
        internal static string possibleReward {
            get {
                return ResourceManager.GetString("possibleReward", resourceCulture);
            }
        }
        
        internal static string highReward {
            get {
                return ResourceManager.GetString("highReward", resourceCulture);
            }
        }
        
        internal static string fullAccess {
            get {
                return ResourceManager.GetString("fullAccess", resourceCulture);
            }
        }
        
        internal static string specialAccess {
            get {
                return ResourceManager.GetString("specialAccess", resourceCulture);
            }
        }
        
        internal static string someAccess {
            get {
                return ResourceManager.GetString("someAccess", resourceCulture);
            }
        }
        
        internal static string noAccess {
            get {
                return ResourceManager.GetString("noAccess", resourceCulture);
            }
        }
        
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        internal static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        internal static string authenticatedUsers {
            get {
                return ResourceManager.GetString("authenticatedUsers", resourceCulture);
            }
        }
        
        internal static string anonymousUsers {
            get {
                return ResourceManager.GetString("anonymousUsers", resourceCulture);
            }
        }
        
        internal static string intranetUsers {
            get {
                return ResourceManager.GetString("intranetUsers", resourceCulture);
            }
        }
        
        internal static string developerUsers {
            get {
                return ResourceManager.GetString("developerUsers", resourceCulture);
            }
        }
        
        internal static string opportunity {
            get {
                return ResourceManager.GetString("opportunity", resourceCulture);
            }
        }
        
        internal static string lossConfidentiality {
            get {
                return ResourceManager.GetString("lossConfidentiality", resourceCulture);
            }
        }
        
        internal static string allDataDisclosed {
            get {
                return ResourceManager.GetString("allDataDisclosed", resourceCulture);
            }
        }
        
        internal static string extensiveCriticalDataDisclosed {
            get {
                return ResourceManager.GetString("extensiveCriticalDataDisclosed", resourceCulture);
            }
        }
        
        internal static string extensiveNonSensitiveDataDisclosed {
            get {
                return ResourceManager.GetString("extensiveNonSensitiveDataDisclosed", resourceCulture);
            }
        }
        
        internal static string minimalNonSensitiveDataDisclosed {
            get {
                return ResourceManager.GetString("minimalNonSensitiveDataDisclosed", resourceCulture);
            }
        }
        
        internal static string minimalCriticalDataDisclosed {
            get {
                return ResourceManager.GetString("minimalCriticalDataDisclosed", resourceCulture);
            }
        }
        
        internal static string lossIntegrity {
            get {
                return ResourceManager.GetString("lossIntegrity", resourceCulture);
            }
        }
        
        internal static string minimalSlightlyCorrupt {
            get {
                return ResourceManager.GetString("minimalSlightlyCorrupt", resourceCulture);
            }
        }
        
        internal static string minimalSeriouslyCorrupt {
            get {
                return ResourceManager.GetString("minimalSeriouslyCorrupt", resourceCulture);
            }
        }
        
        internal static string extensiveSlightlyCorrupt {
            get {
                return ResourceManager.GetString("extensiveSlightlyCorrupt", resourceCulture);
            }
        }
        
        internal static string extensiveSeriouslyCorrupt {
            get {
                return ResourceManager.GetString("extensiveSeriouslyCorrupt", resourceCulture);
            }
        }
        
        internal static string allCorrupt {
            get {
                return ResourceManager.GetString("allCorrupt", resourceCulture);
            }
        }
        
        internal static string lossAvailability {
            get {
                return ResourceManager.GetString("lossAvailability", resourceCulture);
            }
        }
        
        internal static string minimalSecondaryServices {
            get {
                return ResourceManager.GetString("minimalSecondaryServices", resourceCulture);
            }
        }
        
        internal static string minimalPrimaryServices {
            get {
                return ResourceManager.GetString("minimalPrimaryServices", resourceCulture);
            }
        }
        
        internal static string extensiveSecondaryServices {
            get {
                return ResourceManager.GetString("extensiveSecondaryServices", resourceCulture);
            }
        }
        
        internal static string extensivePrimaryServices {
            get {
                return ResourceManager.GetString("extensivePrimaryServices", resourceCulture);
            }
        }
        
        internal static string allServicesLost {
            get {
                return ResourceManager.GetString("allServicesLost", resourceCulture);
            }
        }
        
        internal static string fullyTraceable {
            get {
                return ResourceManager.GetString("fullyTraceable", resourceCulture);
            }
        }
        
        internal static string possiblyTraceable {
            get {
                return ResourceManager.GetString("possiblyTraceable", resourceCulture);
            }
        }
        
        internal static string completelyAnonymous {
            get {
                return ResourceManager.GetString("completelyAnonymous", resourceCulture);
            }
        }
        
        internal static string easeDiscovery {
            get {
                return ResourceManager.GetString("easeDiscovery", resourceCulture);
            }
        }
        
        internal static string easeExploit {
            get {
                return ResourceManager.GetString("easeExploit", resourceCulture);
            }
        }
        
        internal static string awareness {
            get {
                return ResourceManager.GetString("awareness", resourceCulture);
            }
        }
        
        internal static string intrusionDetection {
            get {
                return ResourceManager.GetString("intrusionDetection", resourceCulture);
            }
        }
        
        internal static string difficult {
            get {
                return ResourceManager.GetString("difficult", resourceCulture);
            }
        }
        
        internal static string practicallyImpossible {
            get {
                return ResourceManager.GetString("practicallyImpossible", resourceCulture);
            }
        }
        
        internal static string automatedTools {
            get {
                return ResourceManager.GetString("automatedTools", resourceCulture);
            }
        }
        
        internal static string theoretical {
            get {
                return ResourceManager.GetString("theoretical", resourceCulture);
            }
        }
        
        internal static string financialDamage {
            get {
                return ResourceManager.GetString("financialDamage", resourceCulture);
            }
        }
        
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        internal static string hidden {
            get {
                return ResourceManager.GetString("hidden", resourceCulture);
            }
        }
        
        internal static string obvious {
            get {
                return ResourceManager.GetString("obvious", resourceCulture);
            }
        }
        
        internal static string publicKnowledge {
            get {
                return ResourceManager.GetString("publicKnowledge", resourceCulture);
            }
        }
        
        internal static string notLogged {
            get {
                return ResourceManager.GetString("notLogged", resourceCulture);
            }
        }
        
        internal static string loggedNoReview {
            get {
                return ResourceManager.GetString("loggedNoReview", resourceCulture);
            }
        }
        
        internal static string loggedReviewed {
            get {
                return ResourceManager.GetString("loggedReviewed", resourceCulture);
            }
        }
        
        internal static string activeDetection {
            get {
                return ResourceManager.GetString("activeDetection", resourceCulture);
            }
        }
        
        internal static string bankruptcy {
            get {
                return ResourceManager.GetString("bankruptcy", resourceCulture);
            }
        }
        
        internal static string brandDamage {
            get {
                return ResourceManager.GetString("brandDamage", resourceCulture);
            }
        }
        
        internal static string minimalDamage {
            get {
                return ResourceManager.GetString("minimalDamage", resourceCulture);
            }
        }
        
        internal static string lossGoodwill {
            get {
                return ResourceManager.GetString("lossGoodwill", resourceCulture);
            }
        }
        
        internal static string lossMajorAccounts {
            get {
                return ResourceManager.GetString("lossMajorAccounts", resourceCulture);
            }
        }
        
        internal static string minorViolation {
            get {
                return ResourceManager.GetString("minorViolation", resourceCulture);
            }
        }
        
        internal static string clearViolation {
            get {
                return ResourceManager.GetString("clearViolation", resourceCulture);
            }
        }
        
        internal static string highViolation {
            get {
                return ResourceManager.GetString("highViolation", resourceCulture);
            }
        }
        
        internal static string oneIndividual {
            get {
                return ResourceManager.GetString("oneIndividual", resourceCulture);
            }
        }
        
        internal static string hundredsPeople {
            get {
                return ResourceManager.GetString("hundredsPeople", resourceCulture);
            }
        }
        
        internal static string thousandsPeople {
            get {
                return ResourceManager.GetString("thousandsPeople", resourceCulture);
            }
        }
        
        internal static string milionsPeople {
            get {
                return ResourceManager.GetString("milionsPeople", resourceCulture);
            }
        }
        
        internal static string significantEffectProfit {
            get {
                return ResourceManager.GetString("significantEffectProfit", resourceCulture);
            }
        }
        
        internal static string minorEffectProfit {
            get {
                return ResourceManager.GetString("minorEffectProfit", resourceCulture);
            }
        }
        
        internal static string costFixVuln {
            get {
                return ResourceManager.GetString("costFixVuln", resourceCulture);
            }
        }
        
        internal static string likelihoodScore {
            get {
                return ResourceManager.GetString("likelihoodScore", resourceCulture);
            }
        }
        
        internal static string impactScore {
            get {
                return ResourceManager.GetString("impactScore", resourceCulture);
            }
        }
        
        internal static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        internal static string physical {
            get {
                return ResourceManager.GetString("physical", resourceCulture);
            }
        }
        
        internal static string adjacent {
            get {
                return ResourceManager.GetString("adjacent", resourceCulture);
            }
        }
        
        internal static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        internal static string attackVector {
            get {
                return ResourceManager.GetString("attackVector", resourceCulture);
            }
        }
        
        internal static string attackComplexity {
            get {
                return ResourceManager.GetString("attackComplexity", resourceCulture);
            }
        }
        
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }

        internal static string changed {
            get {
                return ResourceManager.GetString("changed", resourceCulture);
            }
        }
        
        internal static string unchanged {
            get {
                return ResourceManager.GetString("unchanged", resourceCulture);
            }
        }
        
        internal static string privilegesRequired {
            get {
                return ResourceManager.GetString("privilegesRequired", resourceCulture);
            }
        }
        
        internal static string userInteraction {
            get {
                return ResourceManager.GetString("userInteraction", resourceCulture);
            }
        }
        
        internal static string scope {
            get {
                return ResourceManager.GetString("scope", resourceCulture);
            }
        }
        
        internal static string confidentiality {
            get {
                return ResourceManager.GetString("confidentiality", resourceCulture);
            }
        }
        
        internal static string integrity {
            get {
                return ResourceManager.GetString("integrity", resourceCulture);
            }
        }
        
        internal static string availability {
            get {
                return ResourceManager.GetString("availability", resourceCulture);
            }
        }
        
        internal static string createVuln {
            get {
                return ResourceManager.GetString("createVuln", resourceCulture);
            }
        }
        
        internal static string exploitation {
            get {
                return ResourceManager.GetString("exploitation", resourceCulture);
            }
        }
        
        internal static string remediation {
            get {
                return ResourceManager.GetString("remediation", resourceCulture);
            }
        }
        
        internal static string impact {
            get {
                return ResourceManager.GetString("impact", resourceCulture);
            }
        }
        
        internal static string poc {
            get {
                return ResourceManager.GetString("poc", resourceCulture);
            }
        }
        
        internal static string complexity {
            get {
                return ResourceManager.GetString("complexity", resourceCulture);
            }
        }
        
        internal static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        internal static string selectVulnCategory {
            get {
                return ResourceManager.GetString("selectVulnCategory", resourceCulture);
            }
        }
        
        internal static string selectProject {
            get {
                return ResourceManager.GetString("selectProject", resourceCulture);
            }
        }
        
        internal static string vulnCategory {
            get {
                return ResourceManager.GetString("vulnCategory", resourceCulture);
            }
        }
        
        internal static string loadVuln {
            get {
                return ResourceManager.GetString("loadVuln", resourceCulture);
            }
        }
        
        internal static string selectVuln {
            get {
                return ResourceManager.GetString("selectVuln", resourceCulture);
            }
        }
        
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string vulnCreated {
            get {
                return ResourceManager.GetString("vulnCreated", resourceCulture);
            }
        }
        
        internal static string vulnCreatedError {
            get {
                return ResourceManager.GetString("vulnCreatedError", resourceCulture);
            }
        }
        
        internal static string editVuln {
            get {
                return ResourceManager.GetString("editVuln", resourceCulture);
            }
        }
        
        internal static string deletedVuln {
            get {
                return ResourceManager.GetString("deletedVuln", resourceCulture);
            }
        }
        
        internal static string deletedVulnError {
            get {
                return ResourceManager.GetString("deletedVulnError", resourceCulture);
            }
        }
        
        internal static string deleteVuln {
            get {
                return ResourceManager.GetString("deleteVuln", resourceCulture);
            }
        }
        
        internal static string advancedFilters {
            get {
                return ResourceManager.GetString("advancedFilters", resourceCulture);
            }
        }
        
        internal static string modifiedDate {
            get {
                return ResourceManager.GetString("modifiedDate", resourceCulture);
            }
        }
        
        internal static string searchCVE {
            get {
                return ResourceManager.GetString("searchCVE", resourceCulture);
            }
        }
        
        internal static string searchCVELoadError {
            get {
                return ResourceManager.GetString("searchCVELoadError", resourceCulture);
            }
        }
        
        internal static string detailsVuln {
            get {
                return ResourceManager.GetString("detailsVuln", resourceCulture);
            }
        }
        
        internal static string noProject {
            get {
                return ResourceManager.GetString("noProject", resourceCulture);
            }
        }
        
        internal static string lossAccountability {
            get {
                return ResourceManager.GetString("lossAccountability", resourceCulture);
            }
        }
        
        internal static string remediationComplexity {
            get {
                return ResourceManager.GetString("remediationComplexity", resourceCulture);
            }
        }
        
        internal static string remediationPriority {
            get {
                return ResourceManager.GetString("remediationPriority", resourceCulture);
            }
        }
        
        internal static string noStatus {
            get {
                return ResourceManager.GetString("noStatus", resourceCulture);
            }
        }
        
        internal static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        internal static string vulnImport {
            get {
                return ResourceManager.GetString("vulnImport", resourceCulture);
            }
        }
        
        internal static string messageVulnImport1 {
            get {
                return ResourceManager.GetString("messageVulnImport1", resourceCulture);
            }
        }
        
        internal static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        internal static string messageVulnImport2 {
            get {
                return ResourceManager.GetString("messageVulnImport2", resourceCulture);
            }
        }
        
        internal static string noFileSelected {
            get {
                return ResourceManager.GetString("noFileSelected", resourceCulture);
            }
        }
        
        internal static string vulnImported {
            get {
                return ResourceManager.GetString("vulnImported", resourceCulture);
            }
        }
        
        internal static string taskEdited {
            get {
                return ResourceManager.GetString("taskEdited", resourceCulture);
            }
        }
        
        internal static string taskEditedError {
            get {
                return ResourceManager.GetString("taskEditedError", resourceCulture);
            }
        }
        
        internal static string vulnImportedError {
            get {
                return ResourceManager.GetString("vulnImportedError", resourceCulture);
            }
        }
        
        internal static string executiveSummarySaved {
            get {
                return ResourceManager.GetString("executiveSummarySaved", resourceCulture);
            }
        }
        
        internal static string executiveSummarySavedError {
            get {
                return ResourceManager.GetString("executiveSummarySavedError", resourceCulture);
            }
        }
        
        internal static string noRolePermission {
            get {
                return ResourceManager.GetString("noRolePermission", resourceCulture);
            }
        }
    }
}
